herd/herdtools7

defs.sh
jingle/AArch64Arch_jingle.ml
jingle/ARMArch_jingle.ml
jingle/BellArch_jingle.ml
jingle/CArch_jingle.ml
jingle/PPCArch_jingle.ml
jingle/arch.ml
jingle/callMap.mll
jingle/gen_theme.ml
jingle/libdir/Linux.call
jingle/libdir/Linux2AArch64.map
jingle/parseMap.mll

Hi Luc,
This PR consists of a new tool called "gen_theme" which generates a theme for jingle to do litmus translation.
Also I "fixed" some problems like labels and register allocations in jingle, so as a result I could translate the currently litmus tests from Linux Kernel (C) to AArch64. Although I didn't check whether we can get the same results for both side (i.e. the correctness of the translation), but I think it's a good time for you to review the code, and see if I did something wrong.

[RFC] Litmus translation

---

lib/PPCLexer.mll
lib/PPCParser.mly

lib: PPC: Add 'codevar' support

---

jingle/libdir/Linux.call
jingle/libdir/Linux2AArch64.map

Add a few more rules:
* if-expression
* Addition in WRITE_ONCE()
* atomic_{cmp}xchg_*()
* atomic_inc() // using stadd

jingle: libdir: Add more rules to support translation from C

---

herd/AArch64Sem.ml

Avoid generating those useless write events. More for aesthetics than anything else.

[herd] AArch64, no write event to the ZR register.

---

lib/AArch64Base.ml
lib/ARMBase.ml
lib/BellBase.ml
lib/CBase.ml
lib/MIPSBase.ml
lib/PPCBase.ml
lib/RISCVBase.ml
lib/X86Base.ml
lib/X86_64Base.ml
lib/archBase.mli
litmus/KSkel.ml
litmus/arch_litmus.mli
litmus/compCond.ml
litmus/compCond.mli
litmus/preSi.ml
litmus/skel.ml
litmus/switch.ml
litmus/switch.mli

Correct some dysfunctions of -mode presi.
Mostly introduced while adding target X86_64.

Correct preSi

---

catalogue/aarch64/shelf.py
catalogue/aarch64/tests/LB+rel+BEQ.litmus
catalogue/aarch64/tests/LB+rel+BEQ2.litmus
catalogue/aarch64/tests/LB+rel+BEQ3.litmus
catalogue/aarch64/tests/LB+rel+CSEL.litmus
catalogue/aarch64/tests/LB+rel+CSEL2.litmus
catalogue/aarch64/tests/LB+rel+CSEL3.litmus
herd/AArch64Sem.ml
herd/libdir/aarch64deps.cat
herd/variant.ml
herd/variant.mli

This PR adjusts the semantics of CSEL.

[herd] CSEL semantics

---

.gitignore

Following https://github.com/herd/herdtools7/pull/30

[.gitignore]: added swp to gitignore

---

herd/AArch64Sem.ml

This PR features a significant  change in HW management of the access and dirty bits. Those are now treated independently by test-and-set operation on pte's. This provides more behaviours than the previous monolithic approach, at a certain price in running time. The reason of this lower performance is the numerous choices introduced by test-and-set operations.
+ AF update is attempted unconditionally and performed when
valid bit is set and AF unset
+ DB update is attempted when appropriate (DB unset and write
decided to be performed) and succeeds when DB unset.

[herd] KVM,AArch64 Use test-and-set for updating the AF and DB bits,

---

.gitignore

Low risk patch to handle OSX annoyance

[git]: Added DS_Store to gitignore

---

Makefile
_tags
defs.sh
dune-build.sh
internal/dune
internal/test_herd.ml
ocb-build.sh

This PR replaces the temporary regression-testing mechanism with something more extendable to e.g. testing the catalogue.

Add test_herd binary, to run regression tests of herd7

---

lib/tests/uint_test.ml
lib/uint.ml
lib/uint.mli

This PR contains:
- Cleanups & documentation for the `Uint` module
- Tests for `Uint.Uint128.mul`.

[lib] Clean up Uint128

---

herd/ARMSem.ml

Simplify internal dependencies of the few implemented predicated instructions (ie loads, stores and moves).

[herd] Adjust internal dependencies for ARM (AArch32).

---

litmus/skel.ml

Simplified code that avoids an extra different treatment for arrays while logging final states.

[litmus] Fix array printing in outcomes for standard mode.

---

internal/herd_regression_test.ml

Prior to this PR, `herd_regression_test` would read a directory, sort it, and then test all the litmuses within it. However, this will Stack Overflow for large directories, such as those generated by `diy7`.
This PR removes that restriction by iterating over the directory, file by file. However, to retain sorted output for `make test` and related uses, it still reads & sorts the first 1000 entries. For example:
```sh
% _build/default/internal/herd_regression_test.exe -herd-path _build/install/default/bin/herd7 -libdir-path ./herd/libdir -litmus-dir herd/tests/instructions/AArch64/ show
'_build/install/default/bin/herd7' '-set-libdir' './herd/libdir' 'herd/tests/instructions/AArch64/A04.litmus'
'_build/install/default/bin/herd7' '-set-libdir' './herd/libdir' …
```

[internal] herd_regression_test can test large numbers of litmuses

---

herd/archExtra_herd.ml
herd/eventsMonad.ml
herd/machModelChecker.ml
herd/mem.ml
herd/memUtils.ml
herd/memUtils.mli

Implement arrays in mixed-size mode.

[herd] Array mixed

---

herd/modelUtils.ml

Control dependency is now defined as follows:
+ Given iico_data, rf from register to register (rf-reg)
and control from read event in condition  to any event in alternative
of an "if" construct.
+ Ctrl starts with iico from memory location, followed by
a possibly empty sequence of iico_data, rf-reg and control, and ends in
a control relation.
With respect to previous definition, this amounts to add "control" steps
in the middle chain of elementary relations.

[herd] C, extend the definition of control dependency.

---

litmus/preSi.ml

[litmus] Add const qualifier in generated code to appease gcc

---

herd/AArch64Sem.ml

Postindex addition applies to virtual address, not to
physical (effective) address. Thanks to `M.delay_kont`,
the fix is surprisingly simple.

[herd] KVM, AArch64, fix postindex.

---

herd/AArch64Sem.ml

And fault when accessing PTE from EL0.
Notice that PTE flags of PTE addresses
cannot be changed at the moment, hence
`-variant precise` is mandatory for meaningful
experiments

[herd] Check execution level when accessing PTE.

---

herd/AArch64Sem.ml
herd/eventsMonad.ml
lib/op.ml
lib/op.mli
lib/symbValue.ml

[herd] Kvm arrays

---

herd/archExtra_herd.ml
herd/constraints.ml
herd/tests/instructions/AArch64.neon/V45.litmus
herd/tests/instructions/AArch64.neon/V45.litmus.expected
herd/tests/instructions/AArch64/L013.litmus
herd/tests/instructions/AArch64/L013.litmus.expected
litmus/compCond.ml
litmus/skel.ml

Fix various problems with arrays occuring in final condition.

[herd&litmus] Array equal

---

herd/archExtra_herd.ml
herd/constraints.ml
herd/eventsMonad.ml
herd/top_herd.ml
lib/CapabilityConstant.ml
lib/UInt128Constant.ml
lib/constant.ml
lib/constant.mli
lib/int32Constant.ml
lib/int64Constant.ml
lib/parsedConstant.ml
lib/scalar.mli
lib/symbConstant.ml
lib/symbValue.ml
lib/value.mli

This PR fixes various problems originating in herd technique to represent integers with an unique type, while tests can specify a variety of integer types.

[herd] Fix default print.

---

herd/AArch64Sem.ml
herd/machModelChecker.ml
herd/model.ml
herd/model.mli
lib/dirtyBit.mli
lib/dirtyBit.mll
litmus/crossrun.ml
litmus/dumpRun.ml
litmus/libdir/kvm-x86_64.cfg
litmus/litmus.ml
litmus/preSi.ml

This PR restores a functional `-mode kvm` mode for the X86_64 architecture.

[litmus] Kvm x86 64

---

gen/diyone.ml

Some command line options of diyone were not completely functional. Fix them.

[gen] Diyone options

---

litmus/ASMLang.ml
litmus/CLang.ml
litmus/CTarget.ml
litmus/skel.ml
litmus/top_klitmus.ml
litmus/top_litmus.ml

This PR fixes a bug reported by @akiyks (issue #227).
It also replaces the  non-uniform code by more uniform code.

[litmus] Fix klitmus bug.

---

herd/AArch64Arch_herd.ml
herd/ARMArch_herd.ml
herd/BellArch_herd.ml
herd/CArch_herd.ml
herd/MIPSArch_herd.ml
herd/PPCArch_herd.ml
herd/RISCVArch_herd.ml
herd/X86Arch_herd.ml
herd/X86_64Arch_herd.ml
herd/X86_64Sem.ml
herd/arch_herd.mli
herd/event.ml
herd/machModelChecker.ml
lib/memoryType.ml
lib/memoryType.mli

Implement memory types in herd. The only instance is X86_64 memory types.

[herd] X86 herd memtype

---

gen/X86_64Arch_gen.ml
gen/X86_64Compile_gen.ml
herd/X86_64Arch_herd.ml
herd/X86_64Sem.ml
lib/X86_64Base.ml
lib/X86_64Lexer.mll
lib/X86_64Parser.mly
litmus/X86_64Compile_litmus.ml

Partial implementation (no herd yet) of X86_64 cache line flush instructions.

[litmus+gen] X86 clflush

---

gen/X86_64Arch_gen.ml
gen/X86_64Compile_gen.ml
gen/archExtra_gen.ml
lib/X86_64Lexer.mll

This PR add clflush to arbitrary address (ie different from all other address in test) to the X86_64 generator.

[gen] X86_64 clflushother

---

INSTALL.md

add installation tips to reduce beginners' confusion.

[doc]add installation tips to reduce beginners' confusion.

---

gen/AArch64Compile_gen.ml
gen/cycle.ml
gen/namer.ml

Fix some regressions in generators. Also slightly simplify systematic naming of tests.

Fix `-variant self` option of generators

---

herd/AArch64Sem.ml

This change adds support for translation and other memory features for
DC instructions by VA. DC instructions by set and way bypass this.

[herd] Lift memop for DC by VA instructions

---

herd/herd.ml
herd/itimer.ml
herd/itimer.mli
herd/parseTest.ml
herd/valconstraint.ml
lib/genParserUtils.ml
lib/misc.ml
lib/misc.mli
litmus/CGenParser_litmus.ml

Use a specific exception for timeouts

[herd] Exception timeout

---

litmus/preSi.ml

Simplify generated code and consider the infrequent case of tests with no shared variable. Elaborates on PR #284.

[litmus] Fix presi-kvm mode

---

herd/mem.ml
herd/tests/instructions/AArch64.mixed/M008.litmus
herd/tests/instructions/AArch64.mixed/M008.litmus.expected

Fix a bug in memory equation solving. The bug occurred in mixed-size mode.

[herd] Fix bug in mixed-size memory solving.

---

gen/AArch64Arch_gen.ml
gen/cycle.ml
gen/edge.ml
gen/fence.mli
gen/oneRMW.ml
gen/oneRMW.mli

Implementing the semantics of AMO instructions into DIY so that the post condition can consider this when determining its values

semantics for AMO instructions in DIY

---

litmus/libdir/_hash.c
litmus/libdir/_instance.c

This PR fixes a bug which leaded to different hash values for identical keys.

[litmus] Fix hash init

---

gen/cycle.ml

[gen] The check po_pred is _strict_ po-before

---

litmus/libdir/_aarch64/self.c

The fixed sequence is the one from documentation, B2-146.

[litmus] Fix synchronisation sequence for modifying code.

---

herd/AArch64Sem.ml
herd/branch.ml
herd/mem.ml
herd/semExtra.ml
herd/tests/instructions/AArch64/L022.litmus
herd/tests/instructions/AArch64/L022.litmus.expected
herd/tests/instructions/AArch64/L023.litmus
herd/tests/instructions/AArch64/L023.litmus.expected
herd/tests/instructions/AArch64/L024.litmus
herd/tests/instructions/AArch64/L024.litmus.expected
herd/tests/instructions/AArch64/L025.litmus
herd/tests/instructions/AArch64/L025.litmus.expected
lib/label.ml
lib/label.mli
lib/misc.ml
lib/misc.mli
litmus/ASMLang.ml
litmus/CArch_litmus.ml
litmus/archExtra_litmus.ml
litmus/arch_litmus.mli
litmus/compile.ml
litmus/libdir/_aarch64/getret.c
litmus/libdir/_aarch64/self.c
litmus/libdir/_instance.c
litmus/preSi.ml
litmus/skel.ml
litmus/skelUtil.ml
litmus/top_klitmus.ml

Extension of branch instructions, including branch and link,  to standard mode.
- Branch and link instructions for herd in standard mode.
- Register indirect branches for litmus, with targets given as initial values.

[herd,litmus] Branch no self

---

herd/valconstraint.ml
lib/op.ml
lib/op.mli

Cosmetic change, mostly concerns debug messages.

[herd] Better printing of binary operators

---

gen/AArch64Arch_gen.ml
gen/AArch64Compile_gen.ml
gen/CCompile_gen.ml
gen/alt.ml
gen/archExtra_gen.ml
gen/builder.mli
gen/code.ml
gen/code.mli
gen/config.ml
gen/cycle.ml
gen/diy.ml
gen/dumpAll.ml
gen/edge.ml
gen/final.ml
gen/lexUtil.mli
gen/lexUtil.mll
gen/topUtils.ml
gen/top_gen.ml
gen/variant_gen.ml
gen/variant_gen.mli
herd/variant.ml
herd/variant.mli

Adapt generators for BBM specific tests.

[gen] Diy bbm

---

tools/segment.sh

The purpose of this script is to segment a large configuration file and run it with diy7. This was made in order to be able to generate more tests for certain configuration files and to reduce run time for certain large configuration files.

Segmenting large configuration files

---

gen/alt.ml
gen/edge.ml

A quick PR that complements PR #336.

[gen] Do not consider `Store` edge direction in compatibility checks

---

lib/AArch64Op.ml
lib/archOp.ml
lib/symbValue.ml

Note: operation result is a scalar that can be used
for testing validity, permissions etc.

[herd] Arithmetic and operator on pteval's

---

Makefile
herd/archExtra_herd.ml
herd/tests/instructions/ARM/A001.litmus
herd/tests/instructions/ARM/A001.litmus.expected
herd/tests/instructions/ARM/A002.litmus
herd/tests/instructions/ARM/A002.litmus.expected

PR #359  uncovered a bug. Fix and regression tests.

[herd] Fix arm neg

---

tools/logState.ml

Equality is checked on fields that matters: name, hash, and list of outcomes.
As a matter of fact, this equality is used to check the internal consistency of _herd_ logs. Test results that differ in other fields such as time or conditions) should be considered the same.
Also notice that in case of equality, one of the results is discarded. Otherwise a sum is attempted,

[tools] More tolerant equality for test results.

---

herd/tests/instructions/AArch64/A19.litmus
herd/tests/instructions/AArch64/A19.litmus.expected
lib/AArch64Base.ml

This PR adds a test to PR #365.

Ldur fix with test

---

tools/condUtils.ml
tools/logConstr.ml
tools/logState.ml

Option `-show X` is now working on logs that contain array elements.

[tools] More powerful mcompare

---

herd/machAction.ml

In effect, the `inv-domain` relation is useful as a relation
between TLBI events and PTE accesses.
Relating TLBI events with (initial) physical addresses does
not make sense, while relating  TLBI events with virtual adresses
is useless, as no event whose location is virtual exists
in `-variant kvm` mode.
Notice that `inv-domain` does not applies to page table
accesses in mode `-variant pte2`. Anyway, as far as herd is concerned,
the TLBI instruction does not apply to PTE addresses.

[herd] Simplify the inv-domain relation.

---

litmus/switch.ml

Bug reported by @octurion (Alexandros Tasos), see issue #382.

[litmus] Fix implementation of the implies operator

---

litmus/option.ml
litmus/option.mli

Implementation and documentation were contradictory. Follow documentation.

[litmus] Option `-proc ...` implies `-affinity incr1`

---

herd/parseTest.ml

Configuration parameters (including variants) are set by command-line
options and configuration file settings. Some parameters
can be re-defined in test source and take precedence.
This PR limit the scope of initial configuration parameters, so as
to ensure overriding. The change may be useful in the future when
parameters other than variants are overridden in test source

[herd] Wider overriding by test configuration.

---

tools/madd.ml
tools/mdiag.ml
tools/msort.ml

[tools] Add short description for madd7, mdiag7 and msort7

---

herd/tests/instructions/AArch64/L035.litmus
herd/tests/instructions/AArch64/L035.litmus.expected
herd/tests/instructions/AArch64/L036.litmus
herd/tests/instructions/AArch64/L036.litmus.expected
herd/tests/instructions/AArch64/L037.litmus
herd/tests/instructions/AArch64/L037.litmus.expected
herd/tests/instructions/AArch64/L038.litmus
herd/tests/instructions/AArch64/L038.litmus.expected
herd/tests/instructions/AArch64/L039.litmus
herd/tests/instructions/AArch64/L039.litmus.expected
herd/tests/instructions/AArch64/L040.litmus
herd/tests/instructions/AArch64/L040.litmus.expected

A few tests that exercice potential differences in dependencies between swap instruction with different or same source and target registers.

[herd] A few tests that check SWP instruction internal dependencies.

---

herd/event.ml
herd/machModelChecker.ml

[herd] Define the si relation for FAULT events

---

herd/libdir/aarch64.cat
herd/machModelChecker.ml

[herd] Avoid po relation between events of the same instance

---

Makefile
herd/AArch64Sem.ml
herd/CAV12.ml
herd/archExtra_herd.ml
herd/dir.ml
herd/dir.mli
herd/event.ml
herd/eventsMonad.ml
herd/machAction.ml
herd/mem.ml
herd/memUtils.ml
herd/monad.mli
herd/tests/instructions/AArch64.self/S18.litmus
herd/tests/instructions/AArch64.self/S18.litmus.expected
herd/tests/instructions/AArch64.self/S19.litmus
herd/tests/instructions/AArch64.self/S19.litmus.expected
herd/tests/instructions/AArch64.self/S20.litmus
herd/tests/instructions/AArch64.self/S20.litmus.expected
lib/faultType.ml
lib/faultType.mli
lib/stateParser.mly

Followup to PR #444, with changed dependencies.

[herd] Undefined instructions, continued

---

tools/lexLog_tools.mll

[tools] Add mcompare support for labels as values in postconditions

---

herd/tests/instructions/AArch64.kvm/A011.litmus
herd/tests/instructions/AArch64.kvm/A011.litmus.expected

[herd] Fix aarch64 unit test for MMU:Permission faults

---

herd/libdir/aarch64deps.cat

[AArch64 cat] adjust cat file after better redefinition of ADDR set

---

Makefile
herd/tests/instructions/AArch64/L048.litmus
herd/tests/instructions/AArch64/L048.litmus.expected

This new test combines conditional branch (with displacement) and the new condition GT. It tests some code that was modified during rebase.

[test] One more test

---

herd/tests/instructions/AArch64/L052.litmus
herd/tests/instructions/AArch64/L052.litmus.expected
lib/symbValue.ml

This feature complements "adding offset to symbolic location".

[herd] Subtract offset from symbolic location

---

lib/misc.ml
lib/misc.mli

This is neither urgent nor very important for me, but I somehow did it.

[lib] Update Misc with 4.08.1 stdlib updates

---

gen/alt.ml

See this [comment](https://github.com/herd/herdtools7/issues/531#issuecomment-1450311869).

[gen] Wider default mode for diy

---

doc/gen.tex
doc/x86-rfi.conf
gen/alt.ml

[gen] Fix diy default

---

doc/gen.tex

[doc] Typo

---

herd/AArch64Sem.ml
herd/archExtra_herd.ml
herd/mem.ml
herd/tests/instructions/AArch64.kvm/F000.litmus
herd/tests/instructions/AArch64.kvm/F000.litmus.expected
herd/tests/instructions/AArch64.kvm/F001.litmus
herd/tests/instructions/AArch64.kvm/F001.litmus.expected
herd/tests/instructions/AArch64.kvm/F002.litmus
herd/tests/instructions/AArch64.kvm/F002.litmus.expected
herd/tests/instructions/AArch64.kvm/F003.litmus
herd/tests/instructions/AArch64.kvm/F003.litmus.expected

Fault handler never executes at EL0.

[herd] Fix handler at el0

---

herd/libdir/asl.cat

Cosmetic changes so that nobody take this file as authoritative.

[asl] Add WIP warning to asl cat file

---

INSTALL.md
asllib/bitvector.ml
asllib/bitvector.mli
asllib/dune
asllib/tests/bitvector.ml
asllib/tests/dune
herd/AArch64ASLSem.ml
herd/ASLSem.ml
herd/constraints.ml
herdtools7.opam
lib/ASLScalar.ml
lib/ASLValue.ml
lib/dune
lib/symbValue.ml
lib/value.mli

Introduce an new dependency upon the Zarith library.

[herd,asl] ASL integers as arbitrary precision integers

---

asllib/bitvector.ml
asllib/bitvector.mli
asllib/tests/bitvector.ml

Bug were in conversion from and to arbitrary precision integers.

[asl] Fix a few bugs in implementation of bitvectors

---

asllib/Parser.mly
asllib/StaticInterpreter.ml
asllib/libdir/stdlib.asl
herd/AArch64ASLSem.ml
herd/ASLSem.ml
herd/tests/instructions/AArch64.ASL/SXTW01.litmus
herd/tests/instructions/AArch64.ASL/SXTW01.litmus.expected
lib/AArch64Parser.mly
lib/ASLBase.ml
lib/ASLScalar.ml
lib/capabilityScalar.ml
lib/int128Scalar.ml
lib/op.ml
lib/op.mli
lib/scalar.mli
lib/symbValue.ml

~~Depend on PR #626.~~
Warning, discrepancy with standard herd, hence the draft status.

[herd,asl]  ASL implementations of the UBFM and SBFM instructions.

---

litmus/libdir/mips-qemu.cfg
litmus/libdir/ppc-qemu.cfg

Three architectures: RISVC (update), PPC  and MIPS (creations).

[litmus] Configuration files for qemu crossrun

---

asllib/AST.mli
asllib/ASTUtils.ml
asllib/ASTUtils.mli
asllib/PP.ml
asllib/PP.mli
asllib/Parser.mly
asllib/Serialize.ml
asllib/Typing.ml
asllib/diet.ml
asllib/diet.mli
asllib/error.ml
asllib/tests/asl.t/overlapping-slices.asl
asllib/tests/asl.t/run.t
asllib/tests/asl/required/nested-bitfields.asl
asllib/tests/bad-types.t
asllib/tests/types.ml
asllib/types.ml
herd/tests/instructions/ASL/bitfields1.litmus.expected

This PR wants to fix the following bitfield related issues:

[asl] Implement nested bitfields

---

herd/AArch64ASLSem.ml
herd/AArch64Annot.ml
herd/AArch64Arch_herd.ml
herd/AArch64Sem.ml
herd/ASLAction.ml
herd/ASLSem.ml
herd/libdir/asl-pseudocode/implementations.asl
herd/tests/instructions/AArch64.ASL/LDAPR.litmus
herd/tests/instructions/AArch64.ASL/LDAPR.litmus.expected
herd/tests/instructions/AArch64.ASL/LDAR.litmus
herd/tests/instructions/AArch64.ASL/LDAR.litmus.expected
herd/tests/instructions/AArch64.ASL/STLR.litmus
herd/tests/instructions/AArch64.ASL/STLR.litmus.expected
herd/tests/instructions/AArch64.ASL/SWP+TWO.litmus
herd/tests/instructions/AArch64.ASL/SWP+TWO.litmus.expected
lib/AArch64Base.ml

Implement release and acquire properties on loads (`LDAR` and `LDAPR`), stores (`STLR`), swaps (`SWPA`, `SWPL`, `SWPAL`) and compare and swaps (`CASA`, `CASL`, `CASAL`).

[asl] release acquire

---

asllib/Interpreter.ml
asllib/Interpreter.mli
herd/AArch64ASLSem.ml
herd/ASLSem.ml
herd/herd.ml
herd/libdir/asl-pseudocode/implementations.asl
herd/libdir/asl-pseudocode/patches.asl
herd/mem.ml
herd/tests/instructions/AArch64.ASL/LXSX.litmus
herd/tests/instructions/AArch64.ASL/LXSX.litmus.expected
lib/AArch64Base.ml
lib/symbValue.ml
lib/symbValue.mli

[asl] Implement load-reserve store conditional

---

asllib/ASLSemanticsReference.mld
asllib/Interpreter.ml

See #651 and [@jalglave's comment](https://github.com/herd/herdtools7/pull/651#issuecomment-1714161117)
Notice that I don't want to merge into `master` but into `asldoc-LHSExpr` (i.e. into #651 ).

[asl] Transliteration -- Hadrien patches

---

herd/AArch64ASLSem.ml
herd/ASLAction.ml
herd/ASLSem.ml
herd/libdir/asl-pseudocode/implementations.asl
herd/libdir/asl.cat
herd/mem.ml
herd/tests/instructions/AArch64.ASL/FENCES.litmus
herd/tests/instructions/AArch64.ASL/FENCES.litmus.expected

Implementation is quite straightforward: emit appropriate events.

[asl] Fence instructions

---

asllib/ASLSemanticsReference.mld
asllib/ASLTypingReference.mld
asllib/Interpreter.ml
asllib/Interpreter.mli
asllib/Native.ml
asllib/Native.mli
asllib/Typing.ml
asllib/Typing.mli
asllib/aslseq.ml
asllib/env.mli
asllib/index.html
asllib/index.mld
asllib/instrumentation.ml
herd/ASLSem.ml

hi @HadrienRenaud please could you look at this first attempt at transliterating LHS expressions? In particular Rule.LETuple but all the rest too.
Thanks in advance,
Jade

Further transliteration of ASL semantics rules and start of transliteration of ASL typing rules

---

asllib/AST.mli
asllib/ASTUtils.ml
asllib/ASTUtils.mli
asllib/Interpreter.ml
asllib/Native.ml
asllib/PP.ml
asllib/Parser.mly
asllib/Parser0.mly
asllib/Serialize.ml
asllib/StaticEnv.ml
asllib/StaticEnv.mli
asllib/StaticInterpreter.ml
asllib/Typing.ml
asllib/diet.ml
asllib/env.ml
asllib/error.ml
asllib/libdir/stdlib.asl
asllib/storage.ml
asllib/tests/asl.t/run.t
asllib/tests/asl.t/type_satisfaction_illegal_f3.asl
asllib/tests/asl.t/type_satisfaction_illegal_f4.asl
asllib/tests/asl/required/constrained-integer-types-example.asl
asllib/tests/asl/required/lexpr-concat.asl
asllib/tests/asl/required/nested-bitfields.asl
asllib/tests/asl/required/operator_precedence.asl
asllib/tests/asl/required/static.asl
asllib/tests/asl/required/stdlib.asl
asllib/tests/asl/required/subtypes-with.asl
asllib/tests/division.t
asllib/types.ml

[asl] Small various features

---

asllib/Interpreter.ml
asllib/Typing.ml
asllib/aslref.ml
asllib/dune
asllib/tests/asl.t/division.t
asllib/tests/asl.t/run.t
asllib/tests/asl/required/array-with-enums.asl
asllib/tests/asl/required/array.asl
asllib/tests/bad-types.t
asllib/tests/division.t
asllib/tests/dune
asllib/types.ml

[asl] Arrays indexed by enumerations and short-circuit evaluation

---

asllib/ASLRefREADME.mld
asllib/ASLTypingReference.mld
asllib/Typing.ml
asllib/instrumentation.ml
asllib/tests/ASLSemanticsReference.t/run.t

hi @HadrienRenaud please review and edit as needed, then merge and deploy on the web page.
Thanks in advance,
Jade

Progress on left-hand-side expressions typing rules

---

asllib/ASLSemanticsReference.mld
asllib/ASLTypingReference.mld
asllib/Typing.ml
asllib/instrumentation.ml
asllib/types.ml

@HadrienRenaud please could you have a look?
thanks in advance,
Jade

Further transliteration of typing rules

---

asllib/ASLTypingReference.mld

hi @HadrienRenaud please merge and deploy when you can.
Thanks in advance,
Jade

Fix formatting for web

---

asllib/ASLSemanticsReference.mld

hi @HadrienRenaud please merge and deploy when you can!
Thanks,
Jade

Fix to ASLRef web

---

asllib/Interpreter.ml
asllib/Native.ml
asllib/Typing.ml
asllib/backend.mli
asllib/tests/asl.t/run.t
herd/ASLSem.ml
herd/libdir/asl-pseudocode/implementations.asl
herd/tests/instructions/AArch64.ASL/CAS03.litmus
herd/tests/instructions/AArch64.ASL/CAS03.litmus.expected
lib/ASLOp.ml

This PR fixes a bug whose root cause was partial oversight of  requested size by memory reads.

[herd,asl] Fix asl cas

---

litmus/preSi.ml

Symbolic locations in outcome were yielding C compilation errors.
Fix consists in using appropriate code from fault recognition.

[litmus] Fix regression in `-mode presi`

---

litmus/preSi.ml

At the moment pointer to code is possible only for architecture with fixed-size instructions. For those, the size of instructions is defined in the file `instruction.h`.
Hence consider that no pointer to code can be saved or handled in any way when the file `instruction.h` does not exist.

[litmus] Limit pointer to code (presi/kvm mode)

---

herd/mem.ml
herd/semExtra.ml
herd/tests/instructions/AArch64/L085.litmus
herd/tests/instructions/AArch64/L085.litmus.expected-failure
herd/tests/instructions/AArch64/L086.litmus
herd/tests/instructions/AArch64/L086.litmus.expected
lib/AArch64Base.ml
lib/AArch64Parser.mly
lib/archBase.mli
lib/archUtils.ml
lib/archUtils.mli
lib/instr.ml
litmus/litmusUtils.ml

Semantics is lagging behind (error flagged). However the feature is  useful, as syntax can be used in instruction constant values.

[all] AArch64 ADR insruction accept offset argument

---

catalogue/x86/cats/x86tso-mixed.cat
catalogue/x86/shelf.py
herd-www/Makefile
herd-www/dune

[www] Synchronise x86 model with default

---

gen/cycle.ml

This patch attempts to improve the generation of post-condition for oneloc tests in the generator. Currently some tests generated with diy will generate an incorrect post-condition. One noteable example is CoRR - 
```
AArch64 A
"Rfe PosRR Fre"
Generator=diyone7 (version 7.56+03)
Com=Rf Fr
Orig=Rfe PosRR Fre
{
0:X1=x;
1:X0=x;
}
P0          | P1          ;
MOV W0,#1   | LDR W1,[X0] ;
STR W0,[X1] | LDR W2,[X0] ;
exists (1:X1=1 /\ 1:X2=1)
```
This patch aims to fix this by ensuring that oneloc tests start generating the post condition from the start of a chain of a communication edges, ensuring they are all taken into account in the post condition.

[gen] assign write values in oneloc starting from start of com chain

---

gen/AArch64Compile_gen.ml
herd/AArch64Arch_herd.ml
herd/AArch64Sem.ml
jingle/AArch64Arch_jingle.ml
lib/AArch64Base.ml
lib/AArch64Parser.mly
litmus/AArch64Compile_litmus.ml

Our "index" addressing includes post-indexed and pre-indexed modes.

[herd] More rational implementation of indexed addressing

---

Makefile
asllib/AST.mli
asllib/Interpreter.ml
asllib/Typing.ml
asllib/doc/.gitignore
asllib/doc/ASL.bib
asllib/doc/ASLRefProgress.tex
asllib/doc/ASLSemanticsReference.tex
asllib/doc/ASLSyntaxReference.tex
asllib/doc/ASLTypingReference.tex
asllib/doc/ASLmacros.tex
asllib/doc/Makefile
asllib/doc/control.tex
asllib/doc/disclaimer.tex
asllib/doc/notice.tex
asllib/tests/ASLTypingReference.t/TypingRule.TypeSatisfaction1.asl
asllib/tests/ASLTypingReference.t/TypingRule.TypeSatisfaction2.asl
asllib/tests/ASLTypingReference.t/TypingRule.TypeSatisfaction3.asl
asllib/tests/ASLTypingReference.t/run.t
asllib/types.ml

@Roman-Manevich and @HadrienRenaud: please review asap and add edits as needed.

ASLRef formal: rebase

---

litmus/AArch64Compile_litmus.ml

Nitpicking on lowercase assembly mnemonics.

[litmus] Nitpicking on lowercase mnemonics

---

.github/workflows/build-www.yml
herd-www/Makefile
herd-www/catalogue_to_json.py
herd-www/dune

The artifact `www` can be built by explicit action.

Add github action to build herd-www

---

litmus/dumpRun.ml
litmus/libdir/_utils.c
litmus/preSi.ml
litmus/skel.ml
litmus/skelUtil.ml
litmus/topology.ml

+ Fix a divide by zero bug (`-mode std -a 0`)
+ Share topologies.

[litmus] Clean affinity modes.

---

litmus/skel.ml

This PR aims to let `litmus7` execute tests that initialise memory locations with labels.
Firstly, this following is now possible to run in the standard mode.
```
AArch64 test1
{
int64_t 1:X2;
0:X1=x; 1:X1=x;
0:X2=P1:l1;
0:X3=z; 1:X3=z; 1:X9=P1:l0;
z=P1:l0;
}
P0          |P1           ;
MOV W0,#1   | LDR X2,[X3] ;
STR W0,[X1] | BR X2       ;
DMB ISH     |l1:          ;
STR X2,[X3] | ISB         ;
| LDR W5,[X1] ;
|l0:          ;
| CMP X2,X9   ;
| CSET W4,NE  ;
locations [1:X2;1:X4;1:X5]
exists 1:X4=1 /\ 1:X5=0
```
```
litmus7 -mode std test.litmus -o <output_dir>
```
Secondly, this following is now possible to run in the standard mode with `-variant self`. To this end, the implementation computes labels from the execution context each time upon the use. (Note that the first commit in this …

[litmus] Permit initializing shared-memory locations with labels

---

herd-www/jerd.ml

[www] Fix herd-ww build

---

asllib/Interpreter.ml
asllib/Native.ml
asllib/PP.mli
asllib/backend.mli
herd/AArch64ASLSem.ml
herd/ASLAction.ml
herd/ASLSem.ml
herd/event.ml
herd/libdir/asl.cat
herd/monad.mli
herd/tests/instructions/AArch64.ASL/BRANCH09.litmus
herd/tests/instructions/AArch64.ASL/BRANCH09.litmus.expected
herd/tests/instructions/AArch64.ASL/BRANCH10.litmus
herd/tests/instructions/AArch64.ASL/BRANCH10.litmus.expected
lib/ASLBase.ml
lib/InnerTransRel.ml
lib/InnerTransRel.mli

Branching event added before the selected branch of ASL conditional statement and before loop bodies.

[asl] Add branching event in choice operation

---

.github/workflows/check-build-www.yml

In practice a periodic adaptation of build-www, with no output artifact. See also PR #821.

[action] Periodic check www build

---

litmus/preSi.ml

Combination of options `-mode presi -ascall false` was producing C code that could not compile when there is no exported labels in code.
**Notice:** If some labels need to be exported legitimately, then the setting `-ascall true` applies without notice.

[litmus] Fix wrong behavior in presi mode

---

litmus/libdir/armv8+sve-qemu.cfg

Fix unfortunate typo and a lacking eol at the end.

[litmus] Fix sve+qemu litmus configuration file

---

asllib/ASTUtils.mli
asllib/Typing.ml
asllib/tests/lca.t
asllib/tests/regressions.t/array-lca.asl
asllib/tests/regressions.t/duplicate_expr_record.asl
asllib/tests/regressions.t/rdiv_checks.asl
asllib/tests/regressions.t/run.t
asllib/tests/typing.t/TPositive4-4.asl
asllib/tests/typing.t/run.t
asllib/types.ml

[ASL] Fixing some bugs and some refacto

---

Makefile

One benefit is the systematic test of the AARch64 asl implementation. Extra time devoted to test actions looks bearable.

[herd] Test aarch64 asl

---

herd/AArch64Arch_herd.ml
herd/AArch64Sem.ml
herd/tests/instructions/AArch64.sve/V23.litmus
herd/tests/instructions/AArch64.sve/V23.litmus.expected
herd/tests/instructions/AArch64.sve/V24.litmus
herd/tests/instructions/AArch64.sve/V24.litmus.expected
herd/tests/instructions/AArch64.sve/V25.litmus
herd/tests/instructions/AArch64.sve/V25.litmus.expected
herd/tests/instructions/AArch64.sve/V26.litmus
herd/tests/instructions/AArch64.sve/V26.litmus.expected
jingle/AArch64Arch_jingle.ml
lib/AArch64Base.ml
lib/AArch64Lexer.mll
lib/AArch64Parser.mly
lib/metaConst.ml
lib/metaConst.mli
litmus/AArch64Compile_litmus.ml

Add the AArch64 SVE instructions `RDVL` and `ADDVL`.

More SVE instructions

---

doc/gen.tex

[doc] Document -`relaxlist`

---

Makefile

`make test-local` is adequate in case no internet connection is available.

[test] Add a `test-local` entry.

---

herd-www/jerd.ml

[www] Follow herd small configuration change

---

asllib/Typing.ml
asllib/doc/ASLFormal.tex
asllib/doc/ASLRefProgress.tex
asllib/doc/ASLSemanticsReference.tex
asllib/doc/ASLSyntaxReference.tex
asllib/doc/ASLTypingReference.tex
asllib/doc/ASLmacros.tex
asllib/doc/disclaimer.tex
asllib/instrumentation.ml
asllib/tests/ASLTypingReference.t/TypingRule.BuiltinAggregateTypes.asl
asllib/tests/ASLTypingReference.t/TypingRule.BuiltinExceptionType.asl
asllib/tests/ASLTypingReference.t/TypingRule.EnumerationType.asl
asllib/tests/regressions.t/concat-empty.asl
asllib/tests/regressions.t/run.t
asllib/types.ml

[asl][typing] Typing Reference Pre-Beta step 4

---

herd-www/jerd.ml

[www] Follow PR #893

---

litmus/preSi.ml
litmus/skel.ml
litmus/skelUtil.ml

Fix a few print glitches. Followup to PR #847.

[litmus] Fix litmus label printing

---

asllib/Interpreter.ml

Nicer coding for PR #909. From @HadrienRenaud's [comment](https://github.com/herd/herdtools7/pull/909#discussion_r1691158588).

[herd,asl] Nicer coding for PR #909

---

doc/litmus.tex

Small addition to the documentation.

[doc] Document litmus `-c11 <bool>` command line option

---

asllib/AST.mli
asllib/Parser.mly
asllib/doc/ASLFormal.tex
asllib/doc/ASLRefProgress.tex
asllib/doc/ASLSemanticsReference.tex
asllib/doc/ASLSyntaxReference.tex
asllib/doc/ASLTypingReference.tex
asllib/doc/ASLmacros.tex
asllib/tests/ASLSyntaxReference.t/expr1.asl
asllib/tests/ASLSyntaxReference.t/expr2.asl
asllib/tests/ASLSyntaxReference.t/run.t

* Addressed comments given in a recent review.
* The list of case alterantives must be non-empty.

[asl][syntax reference] Addressing feedback

---

litmus/AArch64Compile_litmus.ml

The fixed instructions are load instructions (including load pair instructions) and the branch if zero/if not zero instructions  (`CBZ` and `CBNZ`).

[litmus] Correct handling of the XZR register for a few instructions.

---

lib/CBase.ml

@akiyks noticed I introduced a regression in c0ce66d75f482f5386036783e9a44dc588fed515 (PR #865). In the version previous to that commit, `atomic_add_unless` could be used even if not properly defined in the *.bell file.
This PR restores the previous behavior, but it also allows to "redefine" the `atomic_add_unless` macro in the *.bell file.

[LKMM] Fix regression of atomic_add_unless 

---

asllib/StaticEnv.ml
asllib/StaticEnv.mli
asllib/StaticModel.ml
asllib/Typing.ml
asllib/doc/ASLmacros.tex
asllib/doc/AssignableExpressions.tex
asllib/doc/Expressions.tex
asllib/doc/GlobalDeclarations.tex
asllib/doc/GlobalStorageDeclarations.tex
asllib/doc/LocalStorageDeclarations.tex
asllib/doc/PatternMatching.tex
asllib/doc/PrimitiveOperations.tex
asllib/doc/RelationsOnTypes.tex
asllib/doc/Statements.tex
asllib/doc/StaticEvaluation.tex
asllib/doc/SubprogramCalls.tex
asllib/doc/SubprogramDeclarations.tex
asllib/doc/SymbolicEquivalenceTesting.tex
asllib/doc/Syntax.tex
asllib/doc/TypeDeclarations.tex
asllib/doc/TypeSystemUtilities.tex
asllib/doc/Types.tex
asllib/error.ml
asllib/instrumentation.ml
asllib/types.ml

Asl catchup and fixes

---

asllib/StaticEnv.ml
asllib/Typing.ml
asllib/doc/ASLmacros.tex
asllib/doc/AssignableExpressions.tex
asllib/doc/ErrorCodes.tex
asllib/doc/Expressions.tex
asllib/doc/GlobalStorageDeclarations.tex
asllib/doc/TypeSystemUtilities.tex
asllib/instrumentation.ml

* Synchronize for #1016 
* Synchronize for #1018

ASL synchronize reference with the implementation

---

lib/AArch64Lexer.mll

[all] Small typo

---

gen/AArch64Compile_gen.ml

This PR allows address dependencies to land on code locations when DC's or IC's are present only. This is necessary to allow tests such as the following to be generated:
```
AArch64 MP.RF+dmb.st+addr-dc.cvau-dsb.ish-ic.ivau-dsb.ish-isb
Variant=ifetch
{
0:X0=instr:"NOP";
0:X1=P1:L0; 1:X1=P1:L0;
0:X3=y; 1:X3=y;
1:X9=0;
}
P0          | P1                ;
STR W0,[X1] | LDR W2,[X3]       ;
DMB ST      | EOR W6,W2,W2      ;
MOV W2,#1   | ADD X1,X1,W6,SXTW ;
STR W2,[X3] | DC CVAU,X1        ;
| DSB ISH           ;
| IC IVAU,X1        ;
| DSB ISH           ;
| ISB               ;
|L0:                ;
| B over            ;
| MOV W9,#1         ;
|over:              ;
exists 1:X2=1 /\ 1:X9=0
```
This PR allows a very similar test to be generated, with the following command and output:
`diyone7 …

[gen] allow address dependencies landing on code location

---

catalogue/bpf/cfgs/new-web.cfg
catalogue/bpf/shelf.py
herd-www/Makefile
herd-www/www/index.html

This commit updates the www Makefile and index.html to allow the web simulator work with BPF memory models.

[herd] BPF: Add support for website

---

asllib/AST.mli
asllib/ASTUtils.ml
asllib/Interpreter.ml
asllib/PP.ml
asllib/Parser.mly
asllib/Serialize.ml
asllib/TopoSort.ml
asllib/Typing.ml
asllib/builder.ml
asllib/doc/ASLmacros.tex
asllib/doc/AbstractSyntax.tex
asllib/doc/GlobalDeclarations.tex
asllib/doc/Specifications.tex
asllib/doc/Statements.tex
asllib/instrumentation.ml
asllib/tests/pragma.t/pragma.asl
asllib/tests/pragma.t/pragma_invalid.asl
asllib/tests/pragma.t/pragma_invalid_stmt.asl
asllib/tests/pragma.t/run.t

This PR adds:
* The `S_Pragma` and `D_Pragma` AST nodes
* Type checking of pragma arguments
* Interpretation semantics of pragmas (semantically a `pass;`)

[asl][reference] Add pragma AST, typing and semantics

---

herd/tests/instructions/AArch64.self/NORUN
herd/tests/instructions/AArch64/A236.litmus
herd/tests/instructions/AArch64/A236.litmus.expected
herd/tests/instructions/AArch64/L086.litmus

[herd] Fix a few glitches in tests

---

.github/workflows/run-litmus-x86_64.yml

Run litmus on some x86_64 tests every sunday.

[ci] Action to run litmus on x86_64 tests

---

asllib/Typing.ml
asllib/doc/GlobalDeclarations.tex
asllib/doc/Statements.tex
asllib/doc/Syntax.tex
asllib/error.ml
asllib/tests/pragma.t/run.t

This PR aims to clarify what pragmas are and raise a warning when a pragma is seen by aslref.

[asl][reference] Clarify pragma usage in the spec

---

.github/workflows/build-www.yml
.github/workflows/check-build-www.yml
.github/workflows/run-litmus-x86_64.yml

CI build-www was failing, I took the opportunity to update all workflows to setup-ocaml v3.

[ci] Update all ci workflows to setupocamlv3

---

.github/workflows/run-litmus.yml

This is an adaptation of run-litmus-x86_64.yml for aarch64.

[ci] Add action to run litmus-aarch64-test

---

asllib/Parser.mly
asllib/doc/ASLmacros.tex
asllib/doc/AbstractSyntax.tex
asllib/doc/Bitfields.tex
asllib/doc/Expressions.tex
asllib/doc/GlobalDeclarations.tex
asllib/doc/GlobalStorageDeclarations.tex
asllib/doc/PatternMatching.tex
asllib/doc/PrimitiveOperations.tex
asllib/doc/Slicing.tex
asllib/doc/Statements.tex
asllib/doc/SubprogramCalls.tex
asllib/doc/SubprogramDeclarations.tex
asllib/doc/Syntax.tex
asllib/doc/TypeDeclarations.tex
asllib/doc/Types.tex
asllib/doc/doclint.py

* Updated reference to reflect removed of ++ operator and names of parameteric productions
* Fixed a typo in the implementation
* Removed an unused parametric production in the parser

[asl][reference] updated reference to synchronize with #1159

---

herd/AArch64Sem.ml

[herd] Fix CASP branching condition typo

---

asllib/doc/RelationsOnTypes.tex
asllib/doc/dictionary.txt
asllib/tests/ASLTypingReference.t/TypingRule.SubtypeSatisfaction.bad1.asl
asllib/tests/ASLTypingReference.t/TypingRule.SubtypeSatisfaction.bad2.asl
asllib/tests/ASLTypingReference.t/run.t

Added two examples including explanations.

Clarify subtyle typing error related to subtype-satisfaction

---

asllib/doc/RelationsOnTypes.tex
asllib/doc/SymbolicSubsumptionTesting.tex
asllib/doc/Types.tex
asllib/doc/doclint.py

Updated the reference to synchronize with PR#1205.

ASL reference synchronize for 1205

---

dune-workspace.versions

[test] Extend `make versions` to include OCaml 5.3

---

asllib/doc/Bitfields.tex
asllib/doc/LexicalStructure.tex
asllib/doc/PrimitiveOperations.tex
asllib/doc/Slicing.tex
asllib/doc/Statements.tex
asllib/doc/SymbolicEquivalenceTesting.tex
asllib/doc/dictionary.txt
asllib/doc/doclint.py
asllib/tests/ASLSemanticsReference.t/SemanticsRule.SliceFromZero.asl
asllib/tests/ASLSemanticsReference.t/SemanticsRule.SliceLength.asl
asllib/tests/ASLSemanticsReference.t/SemanticsRule.SliceRange.asl
asllib/tests/ASLSemanticsReference.t/SemanticsRule.Slices.asl
asllib/tests/ASLSemanticsReference.t/run.t
asllib/tests/ASLTypingReference.t/TypingRule.BitfieldSliceToPositions.asl
asllib/tests/ASLTypingReference.t/TypingRule.CheckPositionsInWidth.bad.asl
asllib/tests/ASLTypingReference.t/TypingRule.DisjointSlicesToPositions.bad.asl
asllib/tests/ASLTypingReference.t/TypingRule.EGetFields.asl
asllib/tests/ASLTypingReference.t/run.t

Added examples and fixed a few bugs.

ASL-716 accessibility enhancements phase 6: examples

---

tools/miaou.ml

Due to production constraints, **miaou** may now produce tex code that latex does not accept.
Use new option `-stdlatex true` when miaou output is for direct LaTeX consumption.

[tools] New `-stdlatex <bool>` option for miaou

---

asllib/doc/ASLmacros.tex
asllib/doc/SideEffects.tex
asllib/doc/dictionary.txt
asllib/doc/doclint.py
asllib/tests/ASLTypingReference.t/TypingRule.CheckSymbolicallyEvaluable.asl
asllib/tests/ASLTypingReference.t/TypingRule.MaxTimeFrame.asl
asllib/tests/ASLTypingReference.t/TypingRule.SESIsBefore.asl
asllib/tests/ASLTypingReference.t/TypingRule.SESIsBefore.bad.asl
asllib/tests/ASLTypingReference.t/TypingRule.SESIsDeterministic.asl
asllib/tests/ASLTypingReference.t/TypingRule.SESIsDeterministic.bad.asl
asllib/tests/ASLTypingReference.t/TypingRule.SESIsPure.asl
asllib/tests/ASLTypingReference.t/TypingRule.SESIsPure.bad1.asl
asllib/tests/ASLTypingReference.t/TypingRule.SESIsPure.bad2.asl
asllib/tests/ASLTypingReference.t/TypingRule.SideEffectIsPure.asl
asllib/tests/ASLTypingReference.t/TypingRule.TimeFrame.asl
asllib/tests/ASLTypingReference.t/TypingRule.TimeFrameGDK.asl
asllib/tests/ASLTypingReference.t/TypingRule.TimeFrameLDK.asl
asllib/tests/ASLTypingReference.t/run.t

* Added examples to the Side Effects chapter.

ASL-716 accessibility enhancements phase 16: examples and fixes

---

herd/mem.ml
herd/valconstraint.ml

This PR fixes two problems found while writing  PR #1258.
1. Iterate solver steps on dependency cycles.
2. Handle independant equations that "define" the same variable several times.

[herd,solver] Fix topological solver

---

asllib/doc/ASLRefALP3.1ChangeLog.tex
asllib/doc/dictionary.txt

For the following:
- https://github.com/herd/herdtools7/pull/1275
- https://github.com/herd/herdtools7/pull/1276
- https://github.com/herd/herdtools7/pull/1277
- https://github.com/herd/herdtools7/pull/1278
- https://github.com/herd/herdtools7/pull/1279
- https://github.com/herd/herdtools7/pull/1280
- https://github.com/herd/herdtools7/pull/1282
- https://github.com/herd/herdtools7/pull/1283
- https://github.com/herd/herdtools7/pull/1290
- https://github.com/herd/herdtools7/pull/1294
- https://github.com/herd/herdtools7/pull/1295

[asl][reference] Update changelog

---

tools/miaou.ml

Allocation of events names by *miaou* was wrong. As an example `let erel = (brel & (crel ; drel)) ; rel` was translated as:
```
There is a *e-rel* from an Effect E~1~ to an Effect E~2~ if all of the following apply:
-   E~3~ b-follows E~1~.
-   E~1~ c-rel E~3~.
-   There is a d-rel from E~3~ to E~3~.
-   E~3~ relates E~2~.
```
Which is wrong, as `E~3`. stands for two different events. A simple allocating function with global state fixes the issue, yielding:
```
There is a *e-rel* from an Effect E~1~ to an Effect E~2~ if all of the following apply:
-   E~3~ b-follows E~1~.
-   E~1~ c-rel E~4~.
-   There is a d-rel from E~4~ to E~3~.
-   E~3~ relates E~2~.
```

[tools,miaou] Use simple gensym for events names.

---

tools/miaou.ml

The description of some relations that involve the relation `[evts]` was wrong. For instance consider:
```
let erel = ([X & R]&rel)
```
The tool **miaou** yielded:
```
There is a *e-rel* from an Effect E~1~ to an Effect E~2~ if all of the following apply:
-   E~1~ is X event.
-   E~1~ is a Memory Read Effect.
-   E~1~ relates E~2~.
```
Which is wrong, the above description correponding to `[X&R];rel`.
With this PR, we have the correct description:
```
There is a *e-rel* from an Effect E~1~ to an Effect E~2~ if all of the following apply:
-   E~1~ is X event.
-   E~1~ is a Memory Read Effect.
-   E~1~ and E~2~ are the same Effect.
-   E~1~ relates E~2~.
```
In the general case, the relation `[evts]` description should refer to two events. It can be done by replacing `[evts]` by `[evts] & …

[tools] Fix description of the set-lifting relation.

---

asllib/doc/ASL.bib
asllib/doc/ASLmacros.tex
asllib/doc/AbstractSyntax.tex
asllib/doc/Expressions.tex
asllib/doc/LexicalStructure.tex
asllib/doc/SideEffects.tex
asllib/doc/SubprogramDeclarations.tex
asllib/doc/Types.tex
asllib/libdir/stdlib.asl
asllib/tests/ASLDefinition.t/Accessor.asl
asllib/tests/ASLDefinition.t/EvaluationOrder.asl
asllib/tests/ASLSyntaxReference.t/expr2.asl
asllib/tests/ASLTypingReference.t/TypingRule.SubprogramTypesClash.asl
asllib/tests/ASLTypingReference.t/TypingRule.SubprogramTypesClash.bad1.asl
asllib/tests/ASLTypingReference.t/TypingRule.TypecheckDecl.asl
asllib/tests/explicit-parameters.t/explicit-parameters.asl
asllib/tests/regressions.t/func2.asl
asllib/tests/regressions.t/func3.asl
asllib/tests/regressions.t/getter_sub_tuple.asl
asllib/tests/regressions.t/getter_subfield.asl
asllib/tests/regressions.t/getter_subfields.asl
asllib/tests/regressions.t/getter_subslice.asl
asllib/tests/regressions.t/getter_without_setter.asl
asllib/tests/regressions.t/nonempty-getter-called-without-slices.asl
asllib/tests/regressions.t/nonempty-setter-called-without-slices.asl
asllib/tests/regressions.t/pstate-exp.asl
asllib/tests/regressions.t/setter_bitfields.asl
asllib/tests/regressions.t/setter_subfield.asl
asllib/tests/regressions.t/setter_subslice.asl
asllib/tests/stdlib.t/run.t

Fixed for comments raised during a PDF review.

[asl][reference] fixes

---

asllib/doc/ASLFormal.tex
asllib/doc/ASLReference.tex
asllib/doc/AbstractSyntax.tex
asllib/doc/Bitfields.tex
asllib/doc/CatchingExceptions.tex
asllib/doc/Expressions.tex
asllib/doc/PatternMatching.tex
asllib/doc/PrimitiveOperations.tex
asllib/doc/Statements.tex
asllib/doc/dictionary.txt

* Moved the `Bitvector Slicing` chapter before the `Bitfields` chapter.
* Addressed extra comments made for [PR #1377](https://github.com/herd/herdtools7/pull/1377)

[asl][reference] addressing suggestions

---

asllib/Parser.mly
asllib/doc/SubprogramDeclarations.tex
asllib/doc/Syntax.tex
asllib/tests/recursive.t/procedure-hits-limit.asl
asllib/tests/recursive.t/procedure-no-limit.asl
asllib/tests/recursive.t/procedure-simple.asl
asllib/tests/recursive.t/run.t

These mirror recurse limits on functions.

[ASL-861] Permit recurse limits on procedures

---

lib/innerRel.ml

Generic version of PR #1406 by @HadrienRenaud: transitive closure and strongly connected component scanning (`ssc_kont`) now share the same generic code for performing  dfs and scc computation.
Given code complexity,  writing it once looks  better, in particular as regards maintenance.

[lib] Improve transitive closure, generic code.

---

asllib/dune
dune
dune-install.sh

Attempt to fix a [bug](https://github.com/herd/herdtools7/pull/1416#issuecomment-3251217698) reported by @akiyks and a [bug](https://github.com/herd/herdtools7/pull/1416#issuecomment-3252155225) reported by @maranget.

Revert build changes from #1416

---

.github/workflows/check-opam-minimals.yml

[test] Remove push activation

---

asllib/Interpreter.ml
asllib/aslref.ml
asllib/tests/regressions.t/asl0-error-handling-time.asl
asllib/tests/regressions.t/run.t

- Fix `aslref --version`
- Use `error_handling_time` consistently during interpretation

[asl] A couple of minor fixes

---

herd/AArch64ASLSem.ml
herd/libdir/asl.cat

This PR gathers optmisations and bug fixes performed during the development of the ASL+VMSA branch.
It particular, it includes a fix of the computation of the `ADDR` event set.

[herd,asl,cat] Squash of asl.cat enhancements
