- herd/CSem.ml
On some architectures, there exists atomic memory operations which will
be run directly at memory controller after issued by a CPU. Such an
operation doesn't return a value to a register, therefore the load part
is not treated as a load by barriers. In order to differ this kind of
operations, we mark the load part of a non-value-return atomic as
"noreturn" annotation. The memory model's cat file can add special rules
to it afterwards.
> C/Linux: Mark the load of non-value-return atomics as "noreturn"

- herd/X86Sem.ml
- lib/X86Base.ml
- lib/X86Lexer.mll
- lib/X86Parser.mly
- litmus/X86Compile_litmus.ml
- litmus/skel.ml
Added movb, movw etc instructions to litmus' x86 parser for writing mixed-size litmus tests. Also truncated the sentinel value in some cases.
> x86 mixed-size: new instructions, truncated sentinel

- jingle/gen_theme.ml
- jingle/libdir/Linux.call
- jingle/libdir/Linux2AArch64.map
- jingle/parseMap.mll
"Func sequence" is a series of functions concatenated by vertical bars
"|" (or pipes). It provides a way to compose functions in defined in map
file to get another function. For example:
"acq_rel" : "acquire | release"
, this defines a new function named "acq_rel", whose behavior is simply
doing a "release" on a rule after an "acquire", IOW, first apply
"acquire" function to a rule A, get a intermediate rule B, and then
applying "release" function to rule B, get a final rule C.
For example, if we define two funcs:
"release" : "store:STR" -> "store:STLXR"
"acquire" : "load:LDXR" -> "load:LDAXR"
, then we can get a new func via func sequence (or composing funcs):
"acq_rel" : "acquire | release"
and mapping for xchg_relaxed():
"%r = xchg_relaxed(%x, constvar:c);" -> "MOV %tmp,&c; …
> jingle: gen_theme: Support func sequence

- lib/misc.ml
split_on_char should skip the 'sep', so we need to change "k" with
"(k+1)" in hit branch
> Lib: Misc: Fix split_on_char

- jingle/libdir/Linux2PPC.map
This will generate a theme file based on Linux.call file and we can
convert a Linux litmus to PPC assembly one with the help of the theme
file.
Currently, we are only able to translate litmus tests in Linux kernel.
Signed-off-by: Paul E. McKenney <paulmck@linux.ibm.com>
> jingle: libdir: Add Linux2PPC.map

- litmus/runUtils.ml
Attempt to fix #21, though there are probably more principled versions, and I haven't been able to test this as exhaustively as I'd like.  (It gives the right response on macOS, though may need a bit more checking on other *nix.)
Commit message reads thusly:
`/mach_kernel` hasn't existed for several macOS revisions, so the
existing detection heuristic (checking that `/mach_kernel` exists) fails on
modern macOS.
This change replaces that detection logic with a test to make sure that
1) the system is a Unix system; and 2) `uname -s` is `Darwin`.
Ideally, I'd have used `Unix` to execute `uname -s` and read its stdout,
but the `Unix` library is unavailable (herdtools7 targeting things other
than *nix!)
> Hopefully-improved macOS detector

- lib/CParser.mly
In C language, a "(void) expr;" statement is used for executing "expr"
while discarding the return value of "expr". And currently herd doesn't
support this kind of statement.
In order to support the following litmus test, this functionality is
added.
C Atomic-set-observable-to-RMW
{
atomic_t v = ATOMIC_INIT(1);
}
P0(atomic_t *v)
{
(void)atomic_add_unless(v,1,0);
}
P1(atomic_t *v)
{
atomic_set(v, 0);
}
locations [v]
exists
(v=2)
The implementation is quite simple: we convert the "(void) expr;"
statement into a StoreReg whose destination is register named "", since
no one can declare a identifier named "", so we don't need to worry
about the side effect of storing to this register.
> [herd,C] support "(void) expr;" statement

- herd/AArch64Sem.ml
- herd/event.ml
- herd/eventsMonad.ml
- herd/libdir/deps.cat
- herd/modelUtils.ml
- herd/monad.mli
Have stronger dependencies by adding some iico_ctrl internal dependencies and by including iico_ctrl in addr/data dependencies and in transition relation history reconstruction.
> Intra-dependency changes for AArch64

- .pre-commit-config.yaml
This should help ensure that changes being committed definitely don't break anything, but allowing e.g. documentation to be updated without triggering a rebuild.
From here, I want to add some tests, then add a similar pre-commit hook to run those via `make test` or similar.
> Run `make all` at pre-commit when changing OCaml & Dune files

- .pre-commit-config.yaml
- herdtools7.opam
This PR fixes the version in `herdtools7.opam`, and adds a [pre-commit](https://pre-commit.com) check to run `opam lint` on commits that change it.
> [all] Lint opam

- litmus/dumpRun.ml
QEMU is an environment variable used by the arm-run script itself.
> Use ARM_RUN variable for KVM run.sh, instead of QEMU

- herd/AArch64Sem.ml
- herd/machAction.ml
- lib/fault.ml
- lib/fault.mli
This field is used to differentiate different kinds of faults that can
happen on the same memory location.
> Add string field to Fault

- gen/AArch64Compile_gen.ml
Currently, using diy with address or data dependencies generates litmus tests where some addresses have no tag. From what I have observed it doesn't change anything functionnally, as the missing tags are the default ones, but there may be other cases.
In any case, having all addresses be tagged seems better for consistency.
> [AArch64 MTE] Fix tag init on DpAddr and DpData

- herd/Version_herd.ml
- herd/herd.ml
- herd/lexConf_herd.mll
- herd/opts.ml
- herd/opts.mli
Also remove Version_herd.ml, because libdir is now defined in opts.ml.
This means that the binary can be run as, e.g.
% _build/herd/herd.native -set-libdir=./herd/libdir foo.litmus
Comparing with & without the flag:
% _build/install/default/bin/herd7 -libdir
/Users/ethmor02/share/herdtools7/herd
% _build/install/default/bin/herd7 -set-libdir=./herd/libdir -libdir
./herd/libdir
> [herd] Add a flag -set-libdir to set the libdir

- lib/AArch64Lexer.mll
- lib/AArch64Parser.mly
Following https://github.com/herd/herdtools7/pull/30
This patch upstreams support for the HINT instruction. This
instruction has specific meaning allocated on a case by case basis, or
otherwise implemented as a NOP, as noted here:
https://developer.arm.com/docs/ddi0596/e/base-instructions-alphabetic-order/hi
nt-hint-instruction
> HINTs as Nops in AArch64

- litmus/libdir/kvm-aarch64.cfg
Building kvm-aarch64 with GCC >= 10.1.0 needs the flag
-mno-outline-atomics. Thus, the ability to optionally enable a flag is
required. This fix is based on upstream kvm-unit-tests,
https://gitlab.com/kvm-unit-tests/kvm-unit-tests/-/commit/4e40b0232355a78234281cd42a8df2cecd30643b.
> [litmus] Add an optional-ccopt Makefile macro to kvm-aarch64.cfg

- gen/AArch64Compile_gen.ml
- herd/AArch64Arch_herd.ml
- herd/AArch64Sem.ml
- herd/unittests/AArch64/A04.litmus
- herd/unittests/AArch64/A08.litmus
- jingle/AArch64Arch_jingle.ml
- lib/AArch64Base.ml
- lib/AArch64Parser.mly
- litmus/AArch64Compile_litmus.ml
This commit upstreams support for LDR (immediate) with post-indexed
write to the address. This commit also upstreams inline barrel shifters
for the LDR instruction.
This commit also upstreams unittests for these examples
Following https://github.com/herd/herdtools7/pull/31
> [all]: LDR(Immediate) post-indexed write + LDR barrel shifters

- herd/unittests/AArch64/A117.litmus
- herd/unittests/AArch64/A118.litmus
- herd/unittests/AArch64/A119.litmus
- herd/unittests/AArch64/A120.litmus
- herd/unittests/AArch64/A121.litmus
- herd/unittests/AArch64/A122.litmus
- herd/unittests/AArch64/A123.litmus
- herd/unittests/AArch64/A124.litmus
- herd/unittests/AArch64/A125.litmus
- lib/AArch64Parser.mly
Added support for labels, unittests also provided.
The label_addr production rule will be extended later to support
numeric addresses.
Following https://github.com/herd/herdtools7/pull/32
> [herd]: Updated label support for BNE,BEQ,CBZ,CBNZ,B,and BL

- lib/AArch64Lexer.mll
- lib/AArch64Parser.mly
Following: https://github.com/herd/herdtools7/pull/31
This patch upstreams the HLT instruction in AArch64.
This instruction is used to enter debug mode, which we don't model here - deferred to NOP.
https://developer.arm.com/docs/ddi0596/b/base-instructions-alphabetic-order/hlt-halt-instruction
> [lib]: HALTs as Nops in AArch64

- herd/AArch64Arch_herd.ml
- herd/AArch64Sem.ml
- herd/unittests/AArch64/A51.litmus
- herd/unittests/AArch64/A52.litmus
- herd/unittests/AArch64/A53.litmus
- herd/unittests/AArch64/A54.litmus
- herd/unittests/AArch64/A55.litmus
- herd/unittests/AArch64/A56.litmus
- herd/unittests/AArch64/A57.litmus
- jingle/AArch64Arch_jingle.ml
- lib/AArch64Base.ml
- lib/AArch64Lexer.mll
- lib/AArch64Parser.mly
- lib/machSize.ml
- lib/machSize.mli
- litmus/AArch64Compile_litmus.ml
following https://github.com/herd/herdtools7/pull/30
This patch upstreams support for the MOVZ operation in AArch64
with logical shift left (LSL)  operand:
movz Wn, #imm{, LSL #shift1}
movz Xn, #imm{, LSL #shift2}
where shift1 is 0 or 16 for 32-bit register
where shift2 is 0, 16, 32, 48 for 64-bit register
> Added MOVZ operation with barrel shift operands

- litmus/libdir/_aarch64/kvm-headers.h
- litmus/libdir/_aarch64/kvm-unit-tests/patches/0002-Add-regions-for-DEVICE_nGRE-and-NORMAL_WT-in-MAIR_EL.patch
Memory attributes in the PTE are encoded through indirections to
MAIR_ELx. This change fixes the indices within MAIR_EL1 that
correspond to the right memory attribute. In addition, it substitutes
the hardcoded values with defined macros.
> [litmus] Fix memory attribute setting for kvm-aarch64

- herd/unittests/AArch64/L001.litmus.expected
The recent commit 60eb4359aa2da588db2b caused a regression, this fixes it
> [fix] fix regression caused by other regression fix

- lib/CParser.mly
Following https://github.com/herd/herdtools7/pull/31
Consider functions such as:
```
void *P0(int *x) {
...
}
```
which are passed to pthread_create functions as commonplace in
concurrent c11 code.
This patch adds the ability to parse `void *` like `void`, that is, we
accept functions with the `void *` or `void` signature but do not yet
act on the semantics of functions.
This patch is needed to work with compiler friendly tests.
> Added void star as ret type for C functions

- herd/event.ml
- herd/machAction.ml
- herd/machModelChecker.ml
+ Confine definition to `machAction.ml`.
+ Two events are related by `alias` when:
- Both accesses are PTE accesses
- And the oa fields of accessed values are equal.
> [herd] Reformulate the `alias` relation.

- Makefile
- _tags
- defs.sh
- internal/dune
- internal/lib/channel.ml
- internal/lib/channel.mli
- internal/lib/command.ml
- internal/lib/command.mli
- internal/lib/dune
- internal/lib/filesystem.ml
- internal/lib/filesystem.mli
- internal/lib/test.ml
- internal/lib/test.mli
- internal/lib/tests/channel_test.ml
- internal/lib/tests/command_test.ml
- internal/lib/tests/dune
- internal/lib/tests/filesystem_test.ml
- internal/lib/tests/test_test.ml
- internal/test_herd.ml
- ocb-build.sh
- ocb-test.sh
This PR is the first in a series that will add `test_herd_diycross` and `test_herd_catalogue`, for testing `herd` with `diycross` and against the Catalogue respectively.
It is being sent as a separate PR because it already introduces multiple new concepts (a new library, tests written in OCaml for testing that library directly), so this will be enough to review on its own.
If approved, future PRs will further extract "running `herd` against an expected output" to a library.
Where possible, functions are named similarly to standard library functions (e.g. `Channel.iter_lines` like `List.iter`).
I have been using exceptions instead of error values, because to my current understanding, that is more "the OCaml way".
`Command.run_with_stdout` is called that because later PRs will include …
> [herd] Extract parts of test_herd to a library internal_lib

- gen/CCompile_gen.ml
- gen/variant_gen.ml
- gen/variant_gen.mli
Following https://github.com/herd/herdtools7/pull/33
Added the option to generate C tests without the Volatile option.
Volatile is not currently used for any other reason than to prevent
compiler optimisations to be applied in litmus. If we are to use such
optimisations we must trust they are correct.
This patch removes the qualifier on types as it is not needed in this
case.
No unittests are provided but you can run test the implementation by
running
diy7 -arch C -variant NoVolatile
and check the output C tests do not have volatile qualified types,
you can check these are then accepted by Herd using
herd7 -model rc11.cat *.litmus
We can follow this up with tests once the infrastructure to do this exists.
> [diy]: Add NoVolatile value to Variant.t in diy

- litmus/dumpRun.ml
This is required to avoid errors in non-bash shells.
Closes #96.
> [litmus] Add shebang to comp.sh and run.sh

- Makefile
This PR:
- Adds a `check-deps` phony target.
- Checks that `opam` is installed.
- Checks that `menhir` and `stdint` are installed.
- If `D=dune`, check that `dune` is installed.
- If `D=ocb`, check that `ocamlbuild` and `ocamlfind` are installed.
- Performs this check before `make build`.
> [all] Add `make check-deps` to ensure dependencies are installed

- Makefile
- internal/herd_diycross_regression_test.ml
- internal/herd_regression_test.ml
This PR:
- Adds informative messages to tests passing, saying what kind of test passed.
- Removes "Tests OK" messages from `herd_regression_test` and `herd_diycross_regression_test`, instead only printing messages on failure. This is similar to other tools such as `dune runtest`.
The output of `make test` used to be:
dune runtest
_build/internal/herd_regression_test.native <flags and stuff>
Tests OK
_build/internal/herd_diycross_regression_test.native <flags and stuff>
Tests OK
It is now:
dune runtest
OCaml unit tests: OK
_build/internal/herd_regression_test.native <flags and stuff>
herd7 AArch64 instructions tests: OK
_build/internal/herd_diycross_regression_test.native <flags and stuff>
herd7 AArch64 diycross7 tests: OK
> [test] Move "Tests OK" messages from herd_*_test to Makefile

- .pre-commit-config.yaml
This PR:
- Changes the pre-commit `make all` for `make test`. We have tests now, so we should run them, and commits that break tests should not be allowed.
- Correspondingly triggers a `make test` if any `.litmus` or `.litmus.expected` files change.
> [all] Replace pre-commit `make all` with `make test`

- herd/AArch64Sem.ml
- lib/AArch64Base.ml
- lib/AArch64Lexer.mll
- lib/AArch64Parser.mly
- lib/symbValue.ml
More specifically, this PR implements:
- Clearing of AF and DBM bits with BIC and {LD,ST}CLR instructions.
- New instruction BIC (and BICS).
> More handling of Page Table Entry from code

- herd/BellAction.ml
- herd/CAction.ml
- herd/action.mli
- herd/machAction.ml
- herd/machModelChecker.ml
- herd/model.ml
- herd/model.mli
- herd/parseTest.ml
- lib/dirtyBit.mli
- lib/dirtyBit.mll
- lib/misc.ml
- lib/misc.mli
Permissions first apply to the pteval accessed and extend to events.
- ReadOnly
(af:1 || (af:0 && HA)) && (db:0 && (!HD || (dmb:0 && HD)))
- ReadWrite
(af:1 || (af:0 && HA)) && (db:1 || (db:0 && dbm:1 && HD)))
Cat models initial environemnt is now enriched by two
new sets of events `ReadOnly` and `ReadWrite`.
Permissions are not obvious for initial writes as HA/HD (wich may
vary per core) may be unkown. In case where all test threads have the
same settings of HA and HD, those are taken for initial writes.
Otherwise there is a fatal failure.
> [herd] KVM, consider permissions of PTE acccesses.

- herd/AArch64Sem.ml
- herd/opts.ml
- herd/parseTest.ml
- herd/parseTest.mli
- herd/semExtra.ml
- herd/variant.ml
- herd/variant.mli
- lib/miscParser.ml
- lib/miscParser.mli
- lib/testVariant.ml
- lib/testVariant.mli
- litmus/litmus.ml
- litmus/option.ml
- litmus/option.mli
- litmus/preSi.ml
- litmus/top_litmus.ml
- litmus/top_litmus.mli
- litmus/variant_litmus.ml
- litmus/variant_litmus.mli
This PR introduces "variants" in the metadata of tests. This is done by using a "Variant" field.
Writing
```
Variant=<tags>
```
Has the same effect as adding option `-variant <tags>` at the end the the command line. As a consequence, variants from the test take precedence over the variants from the command line.
> Variant in test metadata

- herd/AArch64Sem.ml
- herd/unittests/AArch64/A58.litmus
- herd/unittests/AArch64/A58.litmus.expected
- herd/unittests/AArch64/A95.litmus
- herd/unittests/AArch64/A95.litmus.expected
Consider the following:
```
ADD W1, W0, W0, lsl #1;
```
when `0:X0=1`
the final result `0:X1=3` should always occur,
however `0:X1=4` occurs since a single variable `v` is used
when the registers are the same, when two variables are required.
This patch fixes the above for `I_OP3` and adds a `MOVZ` test
missed before.
>  [herd]: Fix same-register I_OP3 barrel shift bug

- herd/AArch64Arch_herd.ml
- herd/AArch64Sem.ml
- herd/unittests/AArch64/A18.litmus
- herd/unittests/AArch64/A18.litmus.expected
- jingle/AArch64Arch_jingle.ml
- lib/AArch64Base.ml
- lib/AArch64Lexer.mll
- lib/AArch64Parser.mly
- litmus/AArch64Compile_litmus.ml
This patch upstreams support for the ldur instruction in AArch64
This does an unscaled load. Unittests are provided.
Following https://github.com/herd/herdtools7/pull/31
> [lib]: LDUR instruction in AArch64

- Makefile
This PR implements [a request](https://github.com/herd/herdtools7/pull/104#issuecomment-721822069) from PR #104.
Especially for long test commandlines, e.g. regression tests, the output should be more readable.
The output of `make test` used to be:
sh ./dune-build.sh $HOME
dune runtest
OCaml unit tests: OK
_build/default/internal/herd_regression_test.exe \
-herd-path _build/install/default/bin/herd7 \
-libdir-path ./herd/libdir \
-litmus-dir ./herd/unittests/AArch64 \
test
herd7 AArch64 instructions tests: OK
_build/default/internal/herd_diycross_regression_test.exe \
-herd-path _build/install/default/bin/herd7 \
-diycross-path _build/install/default/bin/diycross7 \
-libdir-path ./herd/libdir \
-expected-dir ./herd/unittests/AArch64.diycross \
-arch AArch64 \
-relaxlist 'Pod**,Fenced**' \ …
> [test] Add spacing between tests

- gen/AArch64Arch_gen.ml
- gen/AArch64Compile_gen.ml
- gen/cycle.ml
- gen/edge.ml
- gen/final.ml
- gen/topUtils.ml
- gen/top_gen.ml
More KVM related features for generators
- Release (L) and Acquire (both of them, A and Q) combine with PTE writes and reads.
- Address and data dependencies to and from PTE accesses, clarify size issue.
- Observation of chains of PTE writes, either by local observers or by reading final value of PTE.
> Kvm diy reloaded

- INSTALL.md
- Makefile
- _tags
- defs.sh
- lib/CapabilityConstant.ml
- lib/dune
- lib/tests/dune
- lib/tests/uint_test.ml
- lib/uint.ml
- lib/uint.mli
To remove our dependency on the external `stdint` library, this PR creates a module `Uint`, to implement the relevant API from `Stdint`, using pure OCaml. It should also be extendable to 256-bit or larger Unsigned Integers when we need them.
> Replace stdint with homegrown uint library

- herd/archExtra_herd.ml
- herd/top_herd.ml
- litmus/preSi.ml
- litmus/skelUtil.ml
- tools/condPP.ml
- tools/condPP.mli
- tools/lexLog_tools.mll
- tools/logState.ml
- tools/logState.mli
This permits correct final conditions for tests that describe behaviours in tables. Consider for instance two logs A an B, where A and B contain the outcome `0:X0=0 /\ fault (P0,x)`, with B containing the additional outcome `0:X0=0`. That is, the absence of `fault(P0,x)` is left implicit. Then, the comparison mechanics of `mcompare` will yield the conditon `exists 0:X0=0` to encode the outcomes present in B and absent in A. This is not correct as `0:X0=0 /\ Fault(p0,x)` does match this condition. With explicit fault absence, `mcompare` will produce the correct condition:
```
exists 0:X0=0 /\ ~Fault(P0,x)
```
Legacy logs are handled by the `sum` tools, identical outcomes up to having or not having explicit absent faults are considered equal and their number of occurrences are summed. The …
> Explicit markers for the absence of faults for observed faults in tools output logs.

- defs.sh
- internal/lib/base.ml
- internal/lib/base.mli
- internal/lib/command.ml
- internal/lib/command.mli
- internal/lib/compare.ml
- internal/lib/compare.mli
- internal/lib/ocamlString.ml
- internal/lib/ocamlString.mli
- internal/lib/shelf.ml
- internal/lib/shelf.mli
- internal/lib/tests/base_test.ml
- internal/lib/tests/command_test.ml
- internal/lib/tests/compare_test.ml
- internal/lib/tests/dune
- internal/lib/tests/ocamlString_test.ml
- internal/lib/tests/shelf_test.ml
This PR adds a module `Shelf`, to work with `shelf.py` Catalogue files using OCaml.
To do this, this PR also:
- Adds a module `Base`, to extend builtin modules, and backport modules from future versions of OCaml.
- Adds a module `Compare`, to house utilities for writing or generating `compare` functions.
- Adds a module `OcamlString`, to house utilities for writing or generating `to_ocaml_string` functions.
- Extends `Command` with `run_with_stdin_and_stdout`, to run runtime-generated Python scripts on `shelf.py` files.
This PR is a part of Issue #123, implementing regression-testing of the Catalogue.
Regarding the name `to_ocaml_string`, I also considered a name like `repr` like Python's `__repr__` ("internal representation"); what do you think? The contract of `to_ocaml_string` is that …
> [internal_lib] Add module Shelf

- Makefile
This builds the test binaries with the same profile as `make build`, which stops Dune from rebuilding them, resulting in faster pre-commits.
> [test] Run `dune runtest` with --profile=release

- defs.sh
- internal/binaries_of_dune
- internal/lib/sexp.ml
- internal/lib/sexp.mli
- internal/lib/tests/dune
- internal/lib/tests/sexp_test.ml
**Summary**: Replace manual lists in `defs.sh` with a new script that reads from Dune files, `binaries_of_dune`.
Currently, there are two places that binaries are defined:
- For Dune, they are in a given directory's `dune` file.
- For OCamlBuild, they are in `defs.sh`.
These two sources of truth have become out-of-sync before (commit e2837555c73417ac9f207c863298ccbf7890be16, PR #63), and as more tests are added to the project, the risk of error increases.
This commit makes OCB use Dune files as the single source of truth. To do this, this PR:
- Adds a module `Sexp`, to parse Dune files (and other S-expressions).
- Adds tests for `Sexp`.
- Adds a binary `binaries_of_dune` to extract executables and tests from Dune files. To avoid bootstrapping issues from the need for compilation, this …
> [build] Mirror Dune and OCamlBuild configs

- lib/lexScan.mli
- lib/misc.ml
- lib/misc.mli
- lib/miscParser.ml
- lib/miscParser.mli
- lib/procsUser.ml
- lib/procsUser.mli
- litmus/AArch64Compile_litmus.ml
- litmus/ARMCompile_litmus.ml
- litmus/ASMLang.ml
- litmus/CLang.ml
- litmus/KSkel.ml
- litmus/LISACompile.ml
- litmus/LISALang.ml
- litmus/MIPSCompile_litmus.ml
- litmus/PPCCompile_litmus.ml
- litmus/RISCVCompile_litmus.ml
- litmus/X86Compile_litmus.ml
- litmus/X86_64Compile_litmus.ml
- litmus/XXXCompile_litmus.mli
- litmus/compile.ml
- litmus/language.ml
- litmus/libdir/_aarch64/kvm_fault_handler.c
- litmus/libdir/_aarch64/kvm_user_stacks.c
- litmus/preSi.ml
- litmus/skel.ml
- litmus/template.ml
Tests metadata may specify EL0 mode for a comma separated list of thread names:
`EL0=P<i1>,P<i2>,...`
Switch to EL0 is performed at the beginning of thread code (by `eret`
with proper setting of `sp_el0` (per cpu user stack), `elr_el1`
(next instruction after eret) and spsr_el1 (all zero).
Return to EL1 is performed by a system call `svc`. Handler code changes
saved pstate so as to fool kvm infrastructure and return to EL1. Surprisingly
it looks as if the trick is working.
Notice that stacks are different in EL0 and EL1 mode, which may
cause problems (not yet observed). Namely, thread code is in a function body.
Switch to EL0 is performed as late as possible, so as
to alleviate the risk of a reference to stack pointer crossing
this boundary.
> [litmus] Add EL0 mode for KVM AArch64

- herd/AArch64Sem.ml
- herd/parseTest.ml
- lib/PTEVal.ml
- lib/PTEVal.mli
- lib/op.ml
- lib/op.mli
- lib/stateParser.mly
- lib/symbValue.ml
- lib/testHash.ml
- litmus/libdir/_aarch64/kvm-headers.h
- litmus/preSi.ml
- litmus/skelUtil.ml
- tools/lexLog_tools.mll
This field ---AP[1], bit 6 of pteval's--- controls access to virtual memory from exception level EL0. A value of 0 forbids access, a value of 1 allows access.
It is to be noticed that adding a field to pteval's would result in untimely consequences if one does not change the printing of pteval's (print all fields). To avoid those, this PR also includes the following changes.
1. Output by all tools is now changed, fields are not printed when their value is default.
2. For handling old logs, pteval's are normalised to new format internally by tools that consume logs (mcompare, msum..).
3. While computing hashes, a special printing mode is used: old mode for old fields (always print) and new mode for new fields (print when non-default).
> Add el0 field to page table entry value (pteval).

- herd/BellAction.ml
- herd/CAction.ml
- herd/action.mli
- herd/event.ml
- herd/machAction.ml
- herd/machModelChecker.ml
- lib/BellInterpreter.ml
- lib/constant.ml
- lib/constant.mli
- lib/interpreter.ml
Add two Cat primitives, in order to implement one of the conditions requiring break-before-make. 
...
- A change of the output address (OA), if the OA of at least one of the old translation table entries and the new translation table entry is writable.
...
> Bbm primitives

- internal/lib/base.ml
- internal/lib/base.mli
- internal/lib/command.ml
- internal/lib/command.mli
- internal/lib/filesystem.ml
- internal/lib/shelf.ml
- internal/lib/testHerd.ml
- internal/lib/tests/base_test.ml
- internal/lib/tests/command_test.ml
The number of functions to run commands has grown to 3:
- `Command.run`,
- `Command.run_with_stdout`,
- `Command.run_with_stdin_and_stdout`.
As upcoming PR (#133) is going to need to use the stderr of a command, this is going to grow to 4, and may eventually have one for each of the full powerset of {`stdin`,`stdout`,`stderr`}.
Instead, this PR implements One True Function, `Command.run`, which takes 3 optional function parameters, one for each of `~stdin`, `~stdout`, and `~stderr`. The named arguments should also be easier to read than positional arguments after a long function name.
This PR also backports `Fun.protect` and `Option.get` from OCaml 4.08.
This PR blocks PR #133, which in-turn blocks PR #94.
> [internal_lib] Unify Command.run* into a single Command.run

- .pre-commit-config.yaml
- catalogue/aarch64-MTE/shelf.py
- catalogue/aarch64/shelf.py
- catalogue/c11popl15/shelf.py
- catalogue/tutorial/shelf.py
- internal/dune
- internal/lib/base.ml
- internal/lib/base.mli
- internal/lint_shelves.ml
- internal/run_built_binary
This PR creates a tool `lint_shelves` to lint shelves.
It also:
- Backports `Option.value` from OCaml 4.08, and fixes errors in some `shelf.py` files.
- Fixes errors with some `shelf.py` files.
- Adds a tool `internal/run_built_binary` to run the most recently built version of a binary under `_build/`.
- Uses the new linter with Pre-Commit.
> [catalogue] Add tool `lint_shelf`, and use it to lint the shelves

- herd/tests/instructions/AArch64/L005.litmus
- herd/tests/instructions/AArch64/L005.litmus.expected-failure
- internal/herd_diycross_regression_test.ml
- internal/herd_regression_test.ml
- internal/lib/testHerd.ml
- internal/lib/testHerd.mli
Setting this patch as a draft so that it isn't merged before #132 which contains the patches included below to make this patch work
This patch unblocks the expected failures in herd#94
This patch depends on changes in herd#132 and should not be merged before #132 
This patch has also been pre-reviewed by @eth-arm as an initial check 
Consider the test `LB003.litmus`:
```
fictional_instruction X0, X1;
```
which should fail in Herd with a parser error, written in
`LB003.litmus.expected-failure`
```
Warning: File "./herd/tests/instructions/AArch64/L003.litmus", line 7, characters 22-24: unexpected 'X0' (in prog) (User error)
```
This patch extends the testing infrastructure to test for expected failures.
This unblocks herd#94, in particular allows us to test an expected failure of Herd.
> [internal_all] Support for expected-failure tests

- herd/archExtra_herd.ml
- herd/eventsMonad.ml
- herd/tests/instructions/AArch64/L006.litmus
- herd/tests/instructions/AArch64/L006.litmus.expected
This PR add (correct) size component to initial writes.
Before, this size was systematically the machine 'natural' size (_e.g._ `Quad` for AArch64).
Now it depends on location type, with location of pointer type being the machine 'natural' size.
> [herd] Fix size component of initial writes.

- jingle/Version_jingle.ml
- jingle/gen_theme.ml
- jingle/jingle.ml
- litmus/Version_litmus.ml
- litmus/klitmus.ml
- litmus/litmus.ml
- litmus/myName.ml
- litmus/option.ml
- litmus/option.mli
- litmus/runUtils.ml
This PR allows setting the libdir for Jingle & Litmus binaries with a flag, `-set-libdir`.
This was added to Herd in commit d465040feb53c1363c8c63868b4b6297195d7ad9.
> [jingle,litmus] Allow setting libdir with -set-libdir

- internal/run_built_binary
This PR allows `internal/run_built_binary` to be run from any directory. Previously, it assumed that it was being run from the project root.
This also uses a portable version of `realpath` or `readlink -f`, because neither `readpath` nor `readlink`'s `-f` flag are guaranteed to exist.
> [internal] Allow run_built_binary to work from any directory

- herd/event.ml
Reference `CAS <Xs>, <Xt>, <Xn>`
- in all cases all of the following apply:
- D1: there is an Intrinsic data dependency from the Register read effect
of Xn to the Memory read effect of the Memory Location addressed by Xn
- C1: there is an Intrinsic control dependency from the Register read
effect of Xs to the Register write effect of Xs
- C2: there is an Intrinsic control dependency from the Memory read effect
of the Memory Location addressed by Xn to the Register write effect of Xs
- if the CAS instruction fails all of the following apply:
- Df1: there is an Intrinsic data dependency from the Memory read effect
of the Memory Location addressed by Xn to the Register write effect of XsD
- if the CAS instruction succeeds all of the following apply:
- Ds1: there is an Intrinsic data …
> [herd] Adjust AArch64 CAS instruction semantics.

- doc/Makefile
This PR allows a user to build the documentation with the LaTeX build system of their choice.
Order of precidence:
- `make LATEX=mytex` will use `mytex`.
- `export LATEX=mytex; make` will use `mytex`.
- `make` with `rubber` in the `PATH` will use `rubber -f`.
- `make` with `latexmk` in the `PATH` will use `latexmk`.
- `make` with nothing suitable in the `PATH` will error.
Rationale: `latexmk` ships with TeX Live, while [`rubber`](https://gitlab.com/latex-rubber/rubber) can be hard to find.
The documentation seems to build fine with `latexmk`.
> [doc] Allow the user to specify a LATEX, with fallbacks

- herd/AArch64Sem.ml
- herd/event.ml
- herd/eventsMonad.ml
- herd/monad.mli
It is more logical to have such an internal dependency from
page table read to db test-and-set, as the latter is attempted
when pteval bits have some values (db:0, dbm:1, valid:1) and not
attempted otherwise.
> Set internal control dependency from PTE read to db test-and-set attempt, replacing data dependency.

- herdtools7.opam
The actual code dependency was removed in commit 8cd04096a8e3203a75b24d7506ea84a82d6ca3d8.
> [build] remove the `stdint` dependency from herdtools7.opam

- herd/BellAction.ml
- herd/CAction.ml
- herd/action.mli
- herd/machAction.ml
- herd/machModelChecker.ml
- lib/PTEVal.ml
- lib/PTEVal.mli
- lib/miscParser.mli
- lib/stateLexer.mll
- lib/stateParser.mly
- litmus/libdir/_aarch64/kvm-headers.h
- litmus/preSi.ml
This series of patches adds support for specifying attributes in the PTE. The motivation is to use to specify cacheability and shareability attributes. For example:
`pte_x = (oa:phy_y,af:1,db:0,dbm:0,attrs:(Normal,Inner-shareable,Inner-write-back,Outer-write-back))`
These attributes are used to annotate Access Actions and the corresponding events. They are also exposed to cat and enable rules that use these annotations.
These annotations are more of a free-form list of strings, without any specific rules of what these strings can be, to allow different architectures to express their own.
> Add free-form attributes (e.g., cacheability, shareability, etc) to the PTE

- herd/eventsMonad.ml
CAS monad primitive now accept a non-deterministic
address argument. This is required for CAS in kvm mode.
> [herd] KVM, fix CAS implementation.

- internal/lib/shelf.ml
On macOS & some Linux distributions `python` is legacy Python 2, and `python3` is Python 3. However, on other Linux distributions `python` is Python 3 and there is no Python 2.
One of the changes from Python 2 to 3 was removing `execfile()` in favor of `exec()`. This commit uses the correct one depending on Python version.
This PR fixes Issue #149.
> [internal_lib] Support parsing shelves on systems with no Python2

- dune-install.sh
- dune-uninstall.sh
- internal/run_built_binary
- ocb-build.sh
- ocb-install.sh
- ocb-uninstall.sh
- version-gen.sh
This PR improves the portability of various shell scripts in the repository:
- The GNU Coreutils and BSD versions of `stat` take different flags, so hopefully do the correct thing on each platform.
- Use `/bin/sh` instead of `/bin/bash`, as `/bin/bash` is not guaranteed to exist.
- Remove the `function` keyword from `run_built_binary`, as that is a "[bashism](https://wiki.ubuntu.com/DashAsBinSh#function)".
This PR fixes Issue #150.
> [build] Make various shell scripts more portable

- herd/AArch64Sem.ml
- herd/archExtra_herd.ml
- herd/eventsMonad.ml
- herd/machAction.ml
- herd/variant.ml
- herd/variant.mli
- lib/PTEVal.ml
- lib/PTEVal.mli
- lib/constant.ml
- lib/constant.mli
- lib/fault.ml
- lib/fault.mli
- lib/op.ml
- lib/op.mli
- lib/symbValue.ml
- tools/alpha.ml
Handle accesses to the page table as ordinary, virtual, accesses. Caveats.
- Access to page table control is more than just page tables attributes.
- Altering the page table entry of page table pages is not supported.
Also notice that the mode is enabled dynamically by variant `-variant pte-squared`.
> Pte squared

- herd/AArch64Sem.ml
This PR fixes a semantic error that was lurking since the introduction
of the SWP instruction.
> [herd] AArch64, do *not* interpret `SWP _,ZR,[_]` as a store.

- lib/tests/uint_test.ml
- lib/uint.ml
This PR implements `Uint.Uint128.shift_right`, the arithmetic right shift.
This PR does not block PR #161, but it does enable `-variant neon` and `-variant morello` to pass non-Neon / non-Morello regression tests that were using arithmetic right shift, e.g. [A63.litmus](https://github.com/herd/herdtools7/blob/3e395ed199f34354c3e3f4d8d66d951e0c6273b8/herd/tests/instructions/AArch64/A63.litmus).
> [lib] Implement shift_right (arithmetic) for Uint.Uint128

- litmus/libdir/_hash.c
- litmus/libdir/_litmus_io.c
- litmus/libdir/_litmus_io.h
- litmus/libdir/x86_64.cfg
- litmus/preSi.ml
- litmus/skel.ml
- litmus/skelUtil.ml
- litmus/topology.ml
- Handle some const and volatile qualifiers,
so as to avoid C compiler warnings.
- Fail (warn) at litime time when not not enough cores
are are available.
- Accept decent default values when topology is unspecified.
> [litmus] Restore preSi mode.

- internal/lib/command.ml
- internal/lib/command.mli
- internal/lib/shelf.ml
- internal/lib/testHerd.ml
This PR changes the `Shelf` parser to automatically detect available Python versions.
It also enriches the `Command.Error` exception with an `error` record type.
> [internal_lib] Detect Python version in Shelf module

- internal/herd_catalogue_regression_test.ml
- internal/herd_diycross_regression_test.ml
- internal/herd_regression_test.ml
- internal/lib/args.ml
- internal/lib/args.mli
- internal/lib/base.ml
- internal/lib/base.mli
- internal/lib/testHerd.ml
- internal/lib/testHerd.mli
This PR:
- Adds a `-variant` flag to `herd_regression_test`.
- Adds a `-conf` flag to `herd_regression_test` and `herd_diycross_regression_test`.
- Adds a `~conf` parameter to all `TestHerd` functions.
- Adds a module for additional argument types & validation, `Args`.
- Rewrites & unifies argument parsing for `herd_regression_test`, `herd_catalogue_regression_test`, and `herd_diycross_regression_test`.
It also:
- Backports `Option.map` from OCaml 4.08 into `Base`.
- Modifies 2 existing Herd regression litmus tests so that they pass under `-variant mixed`.
> [internal] herd_regression_test takes an optional -variant flag

- litmus/compile.ml
- litmus/libdir/_utils.c
- litmus/libdir/_utils.h
- litmus/preSi.ml
- litmus/skel.ml
Handling of array constructs by litmus had been delayed. This PR restores identity of behaviour between the herd and litmus tools.
It also fixes a few missing `const` qualifiers in C code.
> [litmus] Handle array constructs.

- herd/AArch64Sem.ml
- herd/archExtra_herd.ml
- herd/semExtra.ml
- herd/tests/instructions/AArch64/L011.litmus
- herd/tests/instructions/AArch64/L011.litmus.expected
- herd/tests/instructions/AArch64/L012.litmus
- herd/tests/instructions/AArch64/L012.litmus.expected
- herd/top_herd.ml
- lib/CapabilityConstant.ml
- lib/int32Constant.ml
- lib/int64Constant.ml
- lib/op.ml
- lib/op.mli
- lib/parsedConstant.ml
- lib/scalar.mli
- lib/symbValue.ml
- lib/testType.ml
- lib/testType.mli
Use type for printing values in outcomes. This applies mostly to signed integers, which have to be sign-extended to to machine size, and to locations of arrays type, which are now printed as arrays.
> Herd typed print

- herd/tests/instructions/AArch64/A96.litmus
- herd/tests/instructions/AArch64/A96.litmus.expected
This PR adds a herd Instructions Test for `ASR` (Arithmetic Shift Right) on AArch64 to confirm that it performs _arithmetic_ and not _logical_ shifts for negative values.
> [herd] Add an AArch64 test for ASR with a negative initial value

- lib/AArch64Base.ml
- lib/ARMBase.ml
- lib/BellBase.ml
- lib/CBase.ml
- lib/MIPSBase.ml
- lib/PPCBase.ml
- lib/RISCVBase.ml
- lib/X86Base.ml
- lib/X86_64Base.ml
- lib/archBase.mli
- lib/testType.ml
- lib/testType.mli
- litmus/CArch_litmus.ml
- litmus/arch_litmus.mli
- litmus/compile.ml
- litmus/skelUtil.ml
Varying default types for registers. For instance (AArch64), having `locations [0:V0.4S;]` will command printing the final value of vector register V0 of thread 0 as a array of four `int`s.
> [litmus] Type neon registers

- lib/symbValue.ml
This PR limits the number of `Op`s that implicitly act on a `Symbolic Virtual` value's capability.
This restores the behavior prior to commit ef79f22 for the majority of operations.
This change means that some tests unsupported by mixed-mode will fail with a meaningful error message with `-variant mixed`, and won't silently corrupt results with `-variant morello`:
Before:
```sh
% herd7 -variant mixed herd/tests/instructions/AArch64/A139.litmus
Fatal: File "herd/tests/instructions/AArch64/A139.litmus" Adios
Fatal error: exception File "lib/int64Constant.ml", line 53, characters 18-24: Assertion failed
% herd7 -variant morello herd/tests/instructions/AArch64/A139.litmus
Test A139 Allowed
States 1
0:X0=0;
No
Witnesses
Positive: 0 Negative: 1
Condition exists (0:X0=42)
Observation A139 Never …
```
> [lib] SymbValue.unop operates only on Concrete values

- gen/namer.ml
The one addition is adding polarity (_.i.e._ R or W) after internal
edge names, except for the last one.
Thus, the name for cycle `PodWW Rfe PodRR PodRR Fre` is now `MP+po+poR-po`,
replacing the more ambiguous name `MP+po+po-po`.
> [gen] Slightly more descriptive normalised names for tests.

- gen/AArch64Compile_gen.ml
MOV Cn,#i is not recognized by (herd) parser. Such instructions
were nevertheless emitted by generators for stores with
annotation Pc. As stores with annotation Lc command emission
of MOV Xn,#i, which herd accepts, we adopt the same behaviour.
For instance, old behaviour of command `diyone7 -arch AArch64 -variant morello -cond observe -oneloc Pc PosWW Pc Coe` yielded:
```
AArch64 A
"PosWWPcPc CoePcPc"
Generator=diyone7 (version 7.56+02~dev)
Com=Co
Orig=PosWWPcPc CoePcPc
{
uint128_t x;
0:X1=0xffffc0000:x:1;
}
P0          ;
MOV C0,#1   ;
STR C0,[X1] ;
MOV C2,#2   ;
STR C2,[X1] ;
locations [x;]
```
Where instructions `MOV C0,#1` and `MOV C2,#1` are not accepted. New behaviour is:
```
AArch64 A
"PosWWPcPc CoePcPc"
Generator=diyone7 (version 7.56+02~dev)
Com=Co
Orig=PosWWPcPc CoePcPc
{ …
```
> [gen] Fix constant loading (MOV instruction) for Morello.

- herd/archExtra_herd.ml
- lib/CapabilityConstant.ml
- lib/constant.ml
- lib/constant.mli
- lib/int32Constant.ml
- lib/int64Constant.ml
- lib/misc.ml
- lib/misc.mli
- lib/parsedConstant.ml
- lib/scalar.mli
- lib/stateParser.mly
- lib/symbValue.ml
- lib/uint.ml
- lib/uint.mli
- litmus/CArch_litmus.ml
- litmus/KSkel.ml
- litmus/global_litmus.ml
- litmus/outUtils.ml
The change should allow compilation on 32bits platforms,
solving issue #154.
Notice that Uint.Uint64.t may be a more natural choice.
However, this would hinder using the syntactical features
of int64.
> [all] Implement morello capacities with int64.

- lib/tests/uint_test.ml
- lib/uint.ml
- lib/uint.mli
This PR should remove the last 32-bit incompatibilities (Issue #154).
Tested with `make test` on a Raspberry Pi running Raspbian 10 on `armv7l`.
> [lib] Add function Uint.Uint64.of_int64, convert uint_test to use this

- herd/AArch64Sem.ml
- herd/event.ml
- herd/eventsMonad.ml
- herd/machAction.ml
- herd/monad.mli
- lib/symbValue.ml
Do not emit branching events in the direct access to memory case.
When memory accesses involve page table walk, a branching event is inserted between page table read and
(physical) memory access(es). For direct accesses, such as page table access without variant `pte2`, those
branching events are superfluous.
> [herd] KVM, no branch for direct access

- herd/herd.ml
- herd/mem.ml
- lib/op.ml
- lib/op.mli
- lib/symbValue.ml
Some executions fail during the solver phase because a pair
of memory write and read are not matched properly. For instance
one may match a pte write with a 32bits read. Such execution
is better discared than trigerring herd failure.
This is attempted by introducing a specific exception for
operation failure and catching it around calls to solver
in its "memory" phase. For now only masking operation failure
are handled that way.
> [herd] Discard executions with wrong rf matching.

- herd/herd.ml
- herd/mem.ml
- herd/tests/instructions/AArch64/A176.litmus
- herd/tests/instructions/AArch64/A176.litmus.expected
- herd/tests/instructions/AArch64/A177.litmus
- herd/tests/instructions/AArch64/A177.litmus.expected-failure
- herd/tests/instructions/AArch64/A178.litmus
- herd/tests/instructions/AArch64/A178.litmus.expected-failure
- herd/tests/instructions/AArch64/A179.litmus
- herd/tests/instructions/AArch64/A179.litmus.expected-failure
- herd/tests/instructions/AArch64/A180.litmus
- herd/tests/instructions/AArch64/A180.litmus.expected
- herd/tests/instructions/AArch64/A181.litmus
- herd/tests/instructions/AArch64/A181.litmus.expected
- herd/tests/instructions/AArch64/A182.litmus
- herd/tests/instructions/AArch64/A182.litmus.expected
- herd/tests/instructions/AArch64/A183.litmus
- herd/tests/instructions/AArch64/A183.litmus.expected-failure
- herd/valconstraint.ml
- lib/op.ml
- lib/op.mli
- lib/symbValue.ml
Reverts herd/herdtools7#184.
I guess I have a better solution: delaying exceptions in solver to let the opportunity for contradiction to show up.
> Revert "[herd] Discard executions with wrong rf matching." and better solution.

- litmus/preSi.ml
For some reason,  the case was absent in `preSi.ml`.
Notice that the barrier is coded in C, not in assembly
as this is the case for most other architectures.
> [litmus] Inserting synchronisation barrier definition for RISCV.

- Makefile
- herd/archExtra_herd.ml
- herd/mem.ml
- herd/tests/instructions/AArch64.mixed/M000.litmus.expected
- herd/tests/instructions/AArch64.mixed/mixed.cfg
This PR fixes an issue resulting from the combination of `-variant mixed` and arrays. The optimised enumeration is wrong in that particular case. The fix consists in falling back to naive enumeration when some observed location is of array type.
> [herd] Mixed array

- catalogue/demo/shelf.py
This PR removes a reference to a file `catalogue/demo/cats/anarchy.cat`, which was removed in commit 14b60172beeb54d2690dea69b1bb1b9051e3c064.
This dangling reference was causing the `lint-shelves` pre-commit check to fail; this PR means that all pre-commit checks now pass.
> [catalogue] Remove reference to removed file demo/cats/anarchy.cat

- gen/AArch64Compile_gen.ml
- gen/ARMCompile_gen.ml
- gen/BellCompile.ml
- gen/MIPSCompile_gen.ml
- gen/PPCCompile_gen.ml
- gen/RISCVCompile_gen.ml
- gen/X86Compile_gen.ml
- gen/X86_64Compile_gen.ml
- gen/archExtra_gen.ml
- gen/code.ml
- gen/code.mli
- gen/compileCommon.ml
- gen/top_gen.ml
- lib/label.ml
- lib/label.mli
Various kind of test controlled failures occurring as consequences of "real" control dependencies, checked loads and LR/SC unrolled loops where handled by various mechanisms. All those are now controlled by the unique  'event counter' mechanism: successful run of thread `P<n>` is expressed as variable `ok<n>` having the number of controlled events as final value.
Event counter is field `ok` of the state defined in `ArchExtra` (type `st`).
> [gen] Fix ok

- gen/archExtra_gen.ml
- gen/compileCommon.ml
- gen/top_gen.ml
- gen/typBase.ml
- gen/typBase.mli
- lib/machSize.ml
- lib/machSize.mli
- lib/myMap.ml
This PR solves an incompatibility in generated tests  between `ok<n>` variables (counting successful events) and explicit types for tests (option`-type <t>`, useful for mixed-size tests). 
Namely, variables `ok<n>` are of type `int`, regardless of test type.
> [gen] Fix init

- herd/archExtra_herd.ml
- herd/test_herd.ml
- herd/tests/instructions/AArch64.mixed/M001.litmus
- herd/tests/instructions/AArch64.mixed/M001.litmus.expected
- lib/testType.ml
- lib/testType.mli
In mixed size mode with default option `-machsize auto`, initialisations have to be scanned to compute elementary memory size access.
> [herd] Fix machsize

- herd/tests/instructions/AArch64/L014.litmus
- herd/tests/instructions/AArch64/L014.litmus.expected
- lib/CType.ml
- lib/CType.mli
- litmus/KSkel.ml
- litmus/compCond.ml
- litmus/compCond.mli
- litmus/preSi.ml
- litmus/skel.ml
- litmus/skelUtil.ml
Due to "integer promotion" it is safer to convert constants so that they match the type (and sign) of scrutinized location.
> [litmus] Fix logical proposition compilation to C.

- defs.sh
This PR fixes a minor annoyance where running `% make test D=dune` then `% make test D=ocb` will run each OCaml test twice in OCamlbuild mode.
> [build] defs.sh no-longer parses duplicated dune files in _build

- internal/lib/sexp.ml
- internal/lib/tests/sexp_test.ml
This PR allows the `binaries_of_dune` script to parse `dune` files that use line comments.
From [sexplib](https://github.com/janestreet/sexplib#comments), "line comments" start with `;` and end with a newline.
> [internal] Sexp module can parse Dune's line comments

- herd-www/Makefile
This PR fixes `make clean` for `herd-www/`:
- `JSON_SHELVES` and `JSON_SPINES` were used inconsistently, so they are
unified to `JSON_SHELVES`, because "catalogue shelves" is the
terminology used elsewhere in the repo.
- `WWW_LIB` and `WEB_LIB` were used inconsistently, so they were unified
to `WWW_LIB` to match `WWW_CATALOGUE` and `WWW_PROG`.
- `OCBOPT` was used but not defined, so is now removed.
> [herd-www] fix undefined variables in Makefile

- gen/AArch64Arch_gen.ml
- gen/AArch64Compile_gen.ml
- gen/code.ml
- gen/code.mli
- gen/cycle.ml
- gen/final.ml
- gen/topUtils.ml
- gen/top_gen.ml
- gen/variant_gen.ml
- gen/variant_gen.mli
- lib/AArch64Base.ml
This PR adds basic support for the Neon extension.
The user can use the annotation `N1` to `N4` to ask diy to emit Neon instructions.
Current limitations:
- Memory sizes are limited to `uint128`, which could be exceeded by larger instructions (e.g. `st4`). This could be updated to use a larger array type.
- The final condition generated only covers 1 non-sc case. There are several, and some of the generalised final conditions become quite complex. A rough document on the generalised conditions can be found [here](https://docs.google.com/document/d/16jE5fCFCWA1JuSffHELIPbFwOb6Ek13NaGeCtL2Y3p4/edit?usp=sharing).
> [gen] Add support for Neon

- gen/AArch64Arch_gen.ml
- gen/AArch64Compile_gen.ml
- gen/ARMArch_gen.ml
- gen/BellArch_gen.ml
- gen/CArch_gen.ml
- gen/CCompile_gen.ml
- gen/RISCVArch_gen.ml
- gen/X86Arch_gen.ml
- gen/X86_64Arch_gen.ml
- gen/XXXCompile_gen.mli
- gen/archExtra_gen.ml
- gen/atom.mli
- gen/code.ml
- gen/code.mli
- gen/compileCommon.ml
- gen/cycle.ml
- gen/edge.ml
- gen/final.ml
- gen/machAtom.ml
- gen/noSIMD.ml
- gen/noSIMD.mli
- gen/noWide.ml
- gen/topUtils.ml
- gen/top_gen.ml
This PR first completes PR #160 (Neon support for generators), by computing adequate types for locations that are subject to wide accesses, as performed by neon instructions.
It also provides the following improvements:
+ Abstract SIMD operations so as to make them arch dependent.
+ AArch64: SIMD instructions store values n,n+1,... in different "lanes". Previously, teh same value was written to all lanes.
+ Fix `-obs local` mode for SIMD.
+ Simplify value setting code in cycle.ml.
+ Partially check coherence order.
> [gen] Generate  neon-test

- lib/CGenParser_lib.ml
- lib/CTestHash.ml
- lib/CTestHash.mli
- lib/genParser.ml
- lib/lexScan.mli
- lib/lexScan.mll
- lib/memoryType.ml
- lib/memoryType.mli
- lib/misc.ml
- lib/misc.mli
- lib/miscParser.ml
- lib/miscParser.mli
- lib/testHash.ml
- lib/testHash.mli
- litmus/CGenParser_litmus.ml
- litmus/KSkel.ml
- litmus/klitmus.ml
- litmus/libdir/_x86_64/klitmus_memory_type.c
- litmus/top_klitmus.ml
This PR implements IA-32 memory type specifications for `klitmus7`. Namely, changing memory types is doable from a kernel module and probably much more involved from user code.
Memory type specifications are given as  meta-data with key `MT` (or `MemoryType`) and values being list of pairs `<var>:<spec>`, where `<spec>` are IA-32 memory types `WC`, `UC`,  etc.
For instance here is test SB operating on uncached locations:
```
C SB+UC
MT=x:UC y:UC
{}
P0 (volatile int* y,volatile int* x) {
*x = 1;
int r0 = *y;
}
P1 (volatile int* y,volatile int* x) {
*y = 1;
int r0 = *x;
}
exists (0:r0=0 /\ 1:r0=0)
```
> [litmus] Klitmus memory type

- litmus/KBarrier.ml
- litmus/KBarrier.mli
- litmus/KSkel.ml
- litmus/libdir/kbarrier-tb.txt
This option commands absence of synchronisation for the test loop. Intended use is debug.
> [litmus] klitmus, add option `-barrier no`.

- litmus/ASMLang.ml
- litmus/skel.ml
- litmus/top_klitmus.ml
- litmus/top_litmus.ml
This PR improves klitmus, so that it can handle tests written in assembly. This is a straightforward technique to run tests free of compiler interference.
> [litmus] Klitmus x86 64

- litmus/KSkel.ml
- litmus/top_klitmus.ml
Protection against concurrent invocation of tests is relies
on two devices:
+ The run.sh script is protected by locking
on some directory creation.
+ Module invocation is protectected by lokcking
on some atomic variable.
> [litmus] Strive for exclusive execution of klitmus tests.

- litmus/KSkel.ml
- litmus/X86_64Compile_litmus.ml
- litmus/top_klitmus.ml
- litmus/top_litmus.ml
All tools now understand alignment constraints from test meta-data. Unfortunately it does not suffice to implement X86_64 `movntdqa` instruction for all tools as the kernel and kvm-unit-tests do not support SSE.
> [litmus] Klitmus nt

- Makefile
The previous check-deps implementation was created to check that
`stdint` was installed, and assumed the existance of `opam`.
However, we no-longer require `stdint`, and `opam` is not required to be
installed to build herdtools, so now `make check-deps` just checks for
the presence of `ocaml`, `menhir`, and either `dune` or `ocamlbuild` &
`ocamlfind`.
Tested by applying this patch on a machine that has all the required
dependencies, but NOT `opam`.
> [build] `make check-deps` no-longer requires opam

- herd/AArch64Sem.ml
- herd/event.ml
- herd/eventsMonad.ml
- herd/monad.mli
The unwanted `iico_data` relations were from page table entry read to fault event, in the case when the access fails.
> [herd] Fix iico, avoid generating some unwanted iico_data.

- gen/AArch64Arch_gen.ml
- herd/AArch64Arch_herd.ml
- herd/AArch64Sem.ml
- herd/parseTest.ml
- jingle/AArch64Arch_jingle.ml
- jingle/jingle.ml
- lib/AArch64Base.ml
- lib/AArch64Lexer.mll
- lib/AArch64Parser.mly
- lib/MakeAArch64Base.ml
- litmus/AArch64Arch_litmus.ml
- litmus/top_litmus.ml
- tools/toolParse.ml
Morello is an extension of the AArch64 architecture.
The technique is as follows:
1. Instruction printer is now parametrized by a boolean that
commands printing address registers as 'X' or 'C' registers.
Notice the introduction of a functor `MakePP`.
2. The lexer is also parametrized (still by as functor) and
creates `C<NN>` tokens only when `-variant morello` is active.
Notice that the parser does not really change.
> [herd+gen] Use 'C' type registers for addresses in `-variant morello`

- litmus/KSkel.ml
- litmus/klitmus.ml
- litmus/libdir/kbarrier-tb.txt
- litmus/top_klitmus.ml
Barrier "tb" now use the time stamp counter, if available.
Delay is first set statically by option `-delay <N>`. It can
be changed at launch time with the kernel module style
command line option `delay_tb=<N>`.
> [litmus] klitmus, more precise synchronisation barrier.

- lib/Archs.ml
- lib/Archs.mli
- lib/splitter.mll
- litmus/KSkel.ml
- litmus/dumpRun.ml
- litmus/klitmus.ml
- litmus/libdir/_ppc/timebase.c
- litmus/objUtil.ml
- litmus/option.ml
- litmus/option.mli
- litmus/preSi.ml
- litmus/skel.ml
- litmus/skelUtil.ml
- litmus/top_klitmus.ml
- litmus/top_litmus.ml
- litmus/top_litmus.mli
Option `-carch <arch>` was not working properly.
Fixed by a more rational approach to combining the arch read from tests and the one given as an argument to `-carch`.
> [litmus] Klitmus fix

- lib/AST.mli
- lib/interpreter.ml
- lib/modelLexer.mll
- lib/modelParser.mly
Typically rules specified in cat files limit allowed executions of a
litmus test. This patch adds support for also turning the same rules
into assertions that exit the simulation with an error message.
> [herd] Add support for assertions in cat

- herd/machModelChecker.ml
- lib/dirtyBit.mli
- lib/dirtyBit.mll
The HA/HD settings for initial writes are the ones defined
by the global setting (HA or HD with no thread specification).
> [herd] Change ReadOnly for initial writes.

- tools/matrix.mli
- tools/mdiff.ml
This PR re-enables the log intersection behavior of `mdiff7`. This used to be done with the binary `minter7`, which was removed in commit e9362dd8c2262412bd879971cc2a69c4257ccdd6.
> [tools] Add a flag to mdiff7 to change diff behavior, -act

- herd/AArch64Sem.ml
- herd/eventsMonad.ml
- herd/monad.mli
This PR eliminates the failure case of spurious updates before calling the Cat interpreter.
> [herd] No spurious read alone

- herd/AArch64Arch_herd.ml
- herd/ARMArch_herd.ml
- herd/BellArch_herd.ml
- herd/CArch_herd.ml
- herd/MIPSArch_herd.ml
- herd/PPCArch_herd.ml
- herd/RISCVArch_herd.ml
- herd/X86Arch_herd.ml
- herd/X86_64Arch_herd.ml
- herd/archExtra_herd.ml
- herd/arch_herd.mli
- herd/eventsMonad.ml
- herd/mem.ml
This PR introduces the "environment" optimisation for herd. An environment for register values is maintained during code monad generation. Then, reading a register whose value is known yields this value. instead of the default fresh variable. As a result one may anticipate on choices and reduce the number of generated candidate executions.
This should in particular be beneficial for anticipating whether a location is a virtual or page table location.
> [herd] Opt env

- herd/herd.ml
- herd/mem.ml
- herd/opts.ml
- herd/opts.mli
New command-line option `-maxphantom <n>` limits the number
of spurious updates, `<n>` included.
> [herd] Bound total number of spurious updates.

- herd/AArch64Arch_herd.ml
- herd/BellAction.ml
- herd/CAction.ml
- herd/action.mli
- herd/event.ml
- herd/eventsMonad.ml
- herd/explicit.ml
- herd/explicit.mli
- herd/machAction.ml
- herd/mem.ml
The pairing of load-reserve and store-conditional  instructions was too weak in the kvm case., due to the presence of non-explicit atomic accesses in-between. Those non-explicit accesses are emitted when hardware is responsible for updating some fields of page table entries, such as af.
> [herd] Fix load-reserve store-conditional pairs computation

- herd/tests/instructions/AArch64/A172.litmus
- herd/tests/instructions/AArch64/A172.litmus.expected
- herd/tests/instructions/AArch64/A173.litmus
- herd/tests/instructions/AArch64/A173.litmus.expected
- herd/tests/instructions/AArch64/A174.litmus
- herd/tests/instructions/AArch64/A174.litmus.expected
- lib/AArch64Base.ml
Following #30
Consider the following code emitted by LLVM:
```
ldr x1, [sp]
add x2, sp, #8
mov x6, sp
```
Each of which use the stack pointer register as an argument.
This patch upstreams support for the stack pointer register in AArch64,
with tests included.
> [herd/lib]: Added SP Register to AArch64Base

- herd/machModelChecker.ml
This changes the definition of the ctrl relation in `aarch64dep.cat`.
Namely, internal "commit" events should not impact on the ctrl
dependency relation between venets generated by different instructions.
> [herd] PoD set  restricted to branch conditional events

- herd/AArch64Arch_herd.ml
- herd/AArch64Sem.ml
- herd/mem.ml
- herd/variant.ml
- herd/variant.mli
This PR implements single read page table walk. AF and DB write are performed as write of some RMW of which read is the common page table walk read. Notice that the other purpose of this table walk read is to retrieve physical address and permissions.
> [herd] One read for all

- litmus/libdir/_hash.c
- litmus/libdir/_instance.c
- litmus/libdir/_main.c
- litmus/libdir/_presi.c
- litmus/libdir/_presi.h
- litmus/preSi.ml
Hi Luc,
These are some minor clean-ups. I wanted to remove unnecessary functions, use more of the kvm-unit-tests API and avoid some #ifdefs. Feel free reject any of them as they don't fix any bug in particular.
As a more general note, what do you think about moving some of the C code to .c file rather than generating from ocaml? We can also create different versions of some functions to avoid #ifdefs and/or avoid their dynamic generation (for example `postlude` and `postlude_kvm`).
Nikos
> Litmus minor clean-ups

- herd/mem.ml
- herd/variant.ml
- herd/variant.mli
- lib/misc.ml
- lib/misc.mli
This optional optimisation is commanded by the variant `-variant OptRfRMW`. It consists in pruning candidates whose rf relation is such that one rf edge targets more than one load engaged in a atomic (rmw) pair. Namely, those should be discarded later by any cat model that performs atomicity check.
> [lherd] Optimised  rf pruning for atomic pairs.

- herd/machAction.ml
- lib/CType.ml
Kindly reviewed by @relokin 
Consider the C code fragment:
```
void *P0 (...) {
....
}
```
which is the (pthread friendly) format of concurrent C functions. We may
wish to generate this using diy, and so we would need to know to print a
void pointer type. This patch adds the `void` type in lib, which we can
later combine to generate such a code fragment.
> [lib]: Added Void C Type

- Makefile
- herd/machAction.ml
- herd/tests/instructions/C/C01.litmus
- herd/tests/instructions/C/C01.litmus.expected
- herd/tests/instructions/C/C02.litmus
- herd/tests/instructions/C/C02.litmus.expected
- herd/tests/instructions/C/c.cfg
- lib/CLexer.mll
- lib/CParser.mly
- lib/CType.ml
- lib/CType.mli
- litmus/CCompile_litmus.ml
- litmus/KSkel.ml
- litmus/skel.ml
- litmus/skelUtil.ml
Kindly reviewed by @relokin [here](https://github.com/lukeg101/herdtools7/pull/1)
Following our discussion I was unsure about whether to change `strip_volatile/atomic`. I was checking for the case where the user provides the functions malformed types like `Volatile (Volatile t)` which doesn't arise in practice, but would be good to handle against this case.
Consider the following fragment of a litmus C test:
P0 (const int* y,volatile int* x) {
int r0 = *x;
*y = 1;
}
which uses const qualified types. This patch adds parsing support for
const qualified types. Like volatile we do not implement semantics
for const in Herd.
Additionally we add testing infrastructure to automatically test litmus
C tests against the rc11.cat memory model, like we do with AArch64.
As such, unittests are provided …
> [lib]: Added parsing support for the const type

- herd/AArch64Arch_herd.ml
- herd/AArch64Sem.ml
Instruction annotations A,Q and L are used to annotate page table walk read. Notice that this may create read events annotated with release and exclusive events annotated with acquirePC. There are no instructions that generate those annotations directly. Indeed the idea is more to identify the instruction that generates the PTW read than to annotate the PTW read itself.
> [herd] Annotate read of page table entry from instruction annotation.

- litmus/dumpRun.ml
- litmus/libdir/_aarch64/kvm.c.rules
- litmus/libdir/_aarch64/kvm.rules
- litmus/libdir/_aarch64/kvm_user_stacks.c
- litmus/libdir/_hash.c
- litmus/libdir/_main.c
- litmus/libdir/_presi.h
- litmus/libdir/_x86_64/kvm.rules
- litmus/preSi.ml
- litmus/skelUtil.ml
Implement C driver for KVM mode.
Combining options `-mode kvm` and `-driver C` yields one executable file (`run.flat`). Once adapted, this technique should prove convenient for bare metal experiments.
> C driver for KVM

- litmus/dumpRun.ml
- litmus/libdir/_aarch64/kvm-headers.h
- litmus/preSi.ml
As a consequence control of HW management is disabled initially , and reset to disabled after each test that enable it
for the C driver that performs several tests in sequence.
> [litmus] KVM, AArch64 Default is no HW managment of HA and HD bits.

- lib/simpleDumper.ml
- litmus/dumpRun.ml
- litmus/preSi.ml
Those arrays are now shared with options `-driver C` and `-alloc dynamic`.
> [litmus] Shared topology arrays for `-mode presi`.

- gen/cycle.ml
- gen/final.ml
- gen/topUtils.ml
- gen/top_gen.ml
- lib/constant.ml
- lib/misc.ml
- lib/misc.mli
- lib/stateLexer.mll
- lib/stateParser.mly
This change addressing the issues highlighted by issue #68 by adding a new memtag(x) syntax for accessing the physical tag of a given location x.
The herd support for this is built upon the already existing LV (LocationValue) and LL (LocationLocation) comparison operators present in herdtools, with memtag(x) just being syntactical sugar for x.atag, along with logic added to effectively returning a global location for x with the tag updated to the latest physical value. This then allows for direct comparison against the right hand side value/location in the expression, where it was already possible to express a tagged location (e.g. x:red).
The generator changes to support this include tracking of tag writes for a given cycle, and outputting write values into the condition statement, …
> Add memtag() support for checking MTE tag locations in condition statements

- litmus/dumpRun.ml
- litmus/libdir/_hash.c
- litmus/libdir/_main.c
- litmus/libdir/_toh_nostdio.sh
- litmus/objUtil.ml
- litmus/preSi.ml
- litmus/skelUtil.ml
This is not perfect as several occurrences of printf are still present.
However, for now,  no printf should be left in `-more presi`, as this mode is to be used when support is limited.
> [litmus] Remove some printf occurrences in mode `-stdio false`

- gen/AArch64Arch_gen.ml
- gen/AArch64Compile_gen.ml
- gen/machMixed.ml
- gen/variant_gen.ml
- gen/variant_gen.mli
This PR first fixes a long standing bug: the addresses of generated load exclusive/store exclusive were wrong when mixed size modifiers were present.
The PR also adopts a new default behaviour: load exclusive and store exclusive of a generated pair *must* access the same address with the same size.
The restriction is lifted by the options `-variant ConstrainedUnpredicatable` (can be abbreviated as `-variant CU`).
> [gen] Fix Load Reserve Store Conditional effective address bug

- herd/BellAction.ml
- herd/CAction.ml
- herd/CSem.ml
- herd/action.mli
- herd/archExtra_herd.ml
- herd/eventsMonad.ml
- herd/machAction.ml
- herd/mem.ml
- herd/monad.mli
- herd/top_herd.ml
- herd/valconstraint.ml
Fix detection of insufficient loop unrolling. Pruned executions are now excluded from final display as they should (unless `-variant toofar` is specified).
> [herd] Fix loop

- gen/AArch64Arch_gen.ml
Default behaviour benefits from a more then x2 speedup.
> [gen] Control existence of Neon annotations by `-variant neon`.

- herd/tests/instructions/AArch64/A184.litmus
- herd/tests/instructions/AArch64/A184.litmus.expected
- herd/tests/instructions/AArch64/A184.litmus.expected-warn
- internal/herd_catalogue_regression_test.ml
- internal/herd_diycross_regression_test.ml
- internal/herd_regression_test.ml
- internal/lib/command.ml
- internal/lib/command.mli
- internal/lib/testHerd.ml
- internal/lib/testHerd.mli
This PR extends herd regression testing. Exit code are considered with 0 being successful run and not zero being failure. Additionally, standard output and standard error must be as follows:
- If success, then standard output must be non-empty and standard error can be empty or non-empty.
- If failure, then standard output must be empty and standard error must be  non-empty.
Non-empty out channels are checked against their references.
> [test] Regression with warning and exit code

- herd/dune
- herd/herd.ml
- herd/itimer.ml
- herd/itimer.mli
- herd/lexConf_herd.mll
- herd/opts.ml
- herd/opts.mli
- herd/parseTest.ml
- herd/top_herd.ml
The new option specifies a timeout in seconds.
When active, no test will take more than `<sec>`
seconds of processor time.
Notice:
* Tests interrupted by timeout yield no output at all,
* Timeout out applies to each test individually when
herd executes several tests.
> [herd] Add `-timeout <sec>` option.

- tools/msum.ml
In parallel mode, the number of files to sum by a given worker is now bounded (option `-width <int>`. The technique significantly decreases the memory footprint of a worker processes.
> [tools] Reduce memory footprint of the tool `msum7`

- gen/AArch64Arch_gen.ml
- gen/BellArch_gen.ml
- gen/CArch_gen.ml
- gen/RISCVArch_gen.ml
- gen/X86Arch_gen.ml
- gen/X86_64Arch_gen.ml
- gen/atom.mli
- gen/diyone.ml
- gen/edge.ml
- gen/machAtom.ml
- gen/machMixed.ml
- gen/machMixed.mli
- gen/variant_gen.ml
- gen/variant_gen.mli
By default non-overlapping mixed-size accesses across relaxations
with identical source and target locations are discarded.
Some variants command further control:
+ `-variant MixedDisjoint` disable overlap check
+ `-variant MixedStrictOverlap` strengthen overlap check by
rejecting identical accesses.
> [gen]  Enforce mixed-size overlapping accessses

- litmus/AArch64Compile_litmus.ml
Some mnemonics were uppercase, fix them.
> [litmus] By convention, litmus outputs lowercase mnemonics.

- litmus/lexAffinity.mll
Irf and Ifr and more easy to remember for
rf and fr where the read is instruction
fetch (`-variant self` mode).
> [litmus] Recognize Irf and Ifr lexemes in affinity meta-data

- tools/msum.ml
As a consequence of the more rational partition of summed files (PR #297), some of the original input files may be merged at the very last step. Hence all calls to the effective merge function must apply the selection command line arguments such as `-excl <file>`.
> [tools] Fix concurrent msum

- lib/parsedPteVal.ml
The 'oa:' label was missing in page table entry value printout.
> [all] Fix printing bug

- lib/genParserUtils.ml
Faults from location field do not impact hashes; while they do
when occurring in condition.
Code is left unchanged as the discrepancy is minor and that
the few tests that have faults in the location field appear
in many (hardware) logs.
Change may apply in the future, if popular demand exists.
> [all] A comment highlights a (small) discrepancy in hash computation

- herd/archExtra_herd.ml
- herd/eventsMonad.ml
Default values depend upon identifier nature: virtual, pte, etc.
This fix examines all case of identifier, defaulting to zero
in the limited, specific, case of virtual and physical identifiers.
> [herd] Fix default values

- catalogue/aarch64/cats/aarch64-v07.cat
- catalogue/aarch64/tests/LB+CAS-rfi-ctrl+DMBSY.litmus
- catalogue/aarch64/tests/LB+rel+CAS.litmus
- catalogue/aarch64/tests/MP+CAS-rfi-ctrl+acq.litmus
- catalogue/aarch64/tests/MP+rel+CAS-addr.litmus
- catalogue/aarch64/tests/R+CAS+DMBLD.litmus
- catalogue/aarch64/tests/R+CAS-rfi-ctrl+DMBST.litmus
- catalogue/aarch64/tests/SB+CAS-rfi-addr+DMBSY.litmus
- catalogue/aarch64/tests/SB+SWP-rfi-addr+DMBSY.litmus
- catalogue/aarch64/tests/kinds.txt
- herd/libdir/aarch64.cat
- herd/libdir/aarch64deps.cat
This change is a relaxation.
Arm has investigated the weakening of its dependency definitions, in particular
the notion of control dependency. In light of this investigation, Arm has
decided to keep its notion of control dependency strong, but proposes to
introduce a new notion of dependency, called "Pick dependency". Pick
dependencies allow for very targetted ordering, and it is hoped that this will
enable optimisations.
See also: https://www.spinics.net/lists/kernel/msg4028862.html
and the attached tech report entitled "The Ballad of Dependencies".
Motivation
-------------
At the moment the behaviour MP+rel+CAS-addr:
```
AArch64 MP+rel+CAS-addr
{
z=1;
0:X1=x; 0:X3=y;
1:X1=x; 1:X3=y; 1:X8=z;
}
P0           | P1               ;
MOV W0,#1    | LDR W0, [X1]     ;
STR W0,[X3]  | MOV W5, W0 …
```
> [AArch64 cat] Pick dependencies

- herd/AArch64Arch_herd.ml
- herd/AArch64Sem.ml
- herd/CAction.ml
- herd/machAction.ml
- herd/machModelChecker.ml
- lib/interpreter.ml
Check names clashes in the Cat interpreter initial environment, find some, fix them.
> [herd] Safer init env

- herd/BellAction.ml
- herd/CAction.ml
- herd/action.mli
- herd/event.ml
- herd/libdir/aarch64.cat
- herd/libdir/aarch64deps.cat
- herd/libdir/stdlib.cat
- herd/machAction.ml
- herd/machModelChecker.ml
- herd/modelUtils.ml
- herd/tests/instructions/AArch64/L026.litmus
- herd/tests/instructions/AArch64/L026.litmus.expected
- herd/tests/instructions/AArch64/L027.litmus
- herd/tests/instructions/AArch64/L027.litmus.expected
Resolutely use names derived from "branch" to name the ex-commit events.
New names: `B` for all "Branching" events, `BCC` for branching events generated by branch conditional instructions, and `PRED` for internal  branching events.
> [herd] Commit to branch

- tools/lexLog_tools.mll
For the litmus test below herd7 accepts any name as a label
AArch64 test
{
0:X2=x
}
P0               ;
foo:              ;
LDR X1,[X2]      ;
exists(fault(P0:foo,x))
However, tools like msum7 fail to parse the output from herd7.
$> herd7 test.litmus > test.out
$> msum7 test.out
File "test.out", line 3, character 0: Lex error pline
total nouts: 0.00M
> [tools] Allow any name to be used as label for identifying faults

- Makefile
- gen/cycle.ml
- gen/diyone.ml
- gen/edge.ml
- gen/final.ml
- gen/namer.ml
- gen/topUtils.ml
- gen/top_gen.ml
- herd/tests/diycross/AArch64.store/LB+dmb.sy+addrR-pos-store.litmus.expected
- herd/tests/diycross/AArch64.store/LB+dmb.sy+dataW-pos-store.litmus.expected
- herd/tests/diycross/AArch64.store/MP+dmb.sy+addrR-pos-store.litmus.expected
- herd/tests/diycross/AArch64.store/MP+dmb.sy+dataW-pos-store.litmus.expected
- herd/tests/diycross/AArch64.store/S+dmb.sy+addrR-pos-store.litmus.expected
- herd/tests/diycross/AArch64.store/S+dmb.sy+dataW-pos-store.litmus.expected
The `Store` pseudo-edge was removed by commit  7c5461b4bf51da90aca8540343b85c91bff78436 about 4 years ago.
The `Store` pseudo-edge produces a store to location common to the previous and following edges. This store appears at thread code start.
For instance:
```
% diyone7 -arch AArch64 FencedWW Rfe DpAddrdR PosRR Store Fre
AArch64 A
"DMB.SYdWW Rfe DpAddrdR PosRR Store Fre"
Generator=diyone7 (version 7.56+02~dev)
Prefetch=0:x=F,0:y=W,1:y=F,1:x=T
Com=Rf Fr
Orig=DMB.SYdWW Rfe DpAddrdR PosRR Store Fre
{
0:X1=x; 0:X3=y;
1:X0=y; 1:X4=x;
}
P0          | P1                  ;
MOV W0,#2   | MOV W6,#1           ;
STR W0,[X1] | STR W6,[X4]         ;
DMB SY      | LDR W1,[X0]         ;
MOV W2,#1   | EOR W2,W1,W1        ;
STR W2,[X3] | LDR W3,[X4,W2,SXTW] ;
| LDR W5,[X4]         ;
exists ([x]=2 /\ …
```
> [gen] Resurrect the `Store` pseudo-edge

- herd/variant.ml
- herd/variant.mli
Introduce variants `T`_XX_ where _X_ is a decimal digit.
Those variants are usable from cat files with the `if` construct:
```
let r = if "T00" then ... else ...
```
Etc.
> [herd] Add one hundred variants

- herd/BellAction.ml
- herd/CAction.ml
- herd/action.mli
- herd/machAction.ml
- herd/machModelChecker.ml
- lib/AArch64PteVal.ml
Two minor fixes for handling memory attributes.
* create PTE* events for all PTE accesses: implicit/explicit and read/write.
* Introduce one more event PTEMemAttr, a catch all event for all PTE accesses which have one more memory attributes defined.
> Memattrs fixes

- gen/AArch64Arch_gen.ml
- gen/alt.ml
- gen/edge.ml
- herd/AArch64Arch_herd.ml
- herd/AArch64Sem.ml
- lib/AArch64Base.ml
+ Simplify TLBI.ISH lexeme into TLBI (as there are no DSB,ISH here)
+ Option `-variant kvm`  defines .ISH fences.
> [gen] Some enhancements for `-variant kvm`  generators:

- litmus/KSkel.ml
- litmus/doEmitPrintf.ml
- litmus/preSi.ml
- litmus/skel.ml
Some printf implementations fail on long strings. As a workaround we avoid printf when all output consists of strings.
> [litmus] Workaround against some brittle printf implementations.

- herd/AArch64Sem.ml
If complete hardware management of AF and DB bits is active,
and that at least one of the bits is unset, then both bits
are set in one operation.
Previously, four cases were considered, depending on both bits being unset,
exactly one bit being unset, or none. The three "active" case performing
minimal operations. Logic is this simplified at the (small)
price of setting bits that may already be set.
> [herd] Simplify hardware management of AF and DB bits.

- lib/ARMLexer.mll
- lib/ARMParser.mly
Add support for `SUB` and `SUBS` instructions in the 32-bit ARM lexer & parser (which seem to be missing for some reason).
> Parse SUB instruction in the 32-bit ARM lexer & parser

- lib/innerRel.ml
Functions that compute topological orders take a `nodes`
and an `edges` argument that represent the relation to be extended
as orders.
The new code systematically replaces edges by its transitive closure,
yielding a more intuitive and less dangerous semantics.
More precisely consider `nodes = {n1,n2}` and edges = `n1->n3, n3->n2}`.
Then results are:
+ Without transitive closure: `n1->n2` and `n2->n1`
+ With transitive closure `n1->n2` only.
> [herd] Safer linearisations

- herd/AArch64Sem.ml
- herd/opts.ml
- herd/opts.mli
- herd/semExtra.ml
- herd/variant.ml
- herd/variant.mli
- lib/precision.ml
- lib/precision.mli
- lib/testVariant.ml
- lib/testVariant.mli
- litmus/compile.ml
- litmus/libdir/_aarch64/kvm_fault_handler.c
- litmus/option.ml
- litmus/option.mli
- litmus/preSi.ml
- litmus/top_litmus.ml
- litmus/top_litmus.mli
- litmus/variant_litmus.ml
The new possibility `-variant skip` or `-variant faultToNext`
transfers control to the next instruction once fault is handled.
By _handled_ one means:
+ For herd, a fault event is generated.
+ For litmus, scaffold handler is called (once).
As a reminder here are the other imlemented behaviours:
+ `-variant precise`, control is transferred at end of thread code.
+ `-variant imprecise`. Litmus: litmus: adopt default return from handler
behaviour, _i.e._ re-execute the faulty instruction. Herd:
emit fault and re-execute instruction. The instruction is not allowed
to fault again, _i.e._ prune number of consecutive faults to one.
The PR also introduce new names: `-variant precise` becomes `-variant fatal` and `-variant imprecise` becomes `-variant handled`. New names are still recognised in …
> [herd,litmus] Add a new possibility for fault handling in `kvm` mode

- lib/interpreter.ml
"Pairs" are the result `p` of relation matching by pattern `p ++ r`. The operator swaps pair components.
> [herd] The `^-1` (inverse) CAT operator works on pairs

- litmus/libdir/_presi.c
- litmus/libdir/_utils.c
- litmus/litmus.ml
Some error messages and comments refer to `pthread` as `phread`.
This PR corrects the minor typo.
> [litmus] Fix pthread error spelling

- litmus/KSkel.ml
From a report and patch by @akiyks (see #372)
> [klitmus] Remove reference do now unexported function

- herd/ARMArch_herd.ml
- herd/libdir/arm.cat
- herd/libdir/armfences.cat
- herd/tests/instructions/ARM/A003.litmus
- herd/tests/instructions/ARM/A003.litmus.expected
Consider the following store buffering litmus test.
The final state should be forbidden under the arm model.
This patch updates the arm model so that the final state is not
observed.
```
{
0:R2=x; 0:R3=y;
1:R2=y; 1:R3=x;
}
P0           | P1           ;
MOV R0,#1    | MOV R0,#1    ;
STR R0,[R2]  | STR R0,[R2]  ;
DMB ISH      | DMB ISH      ;
LDR R1,[R3]  | LDR R1,[R3]  ;
exists (0:R1=0 /\ 1:R1=0)
```
> [ARM]: Added DMB ISH to arm model

- catalogue/aarch64-MTE-mixed/shelf.py
- catalogue/aarch64-MTE-pick/shelf.py
All MTE books in catalogue use the default aarch64.cat model
> [catalogue] Fix two MTE shelf files

- litmus/dumpRun.ml
- litmus/preSi.ml
Compilation on M1 (`-mode kvm`) reveals some small problems that had long been overlooked.
> [litmus] Fix storage class of some variable in C output

- herd/AArch64Sem.ml
- herd/machAction.ml
In some cases, we need to know if the instruction that generated a
FAULT event had any annotations (for example, was a release
instruction). For this reason, this change adds the annotation
information to the Fault action. Subsequently, it makes sure that herd
considers Fault actions to compute eventsets for architecturally
defined annotations. For good measure, and since we're changing the
Fault action, this change also adds the direction (e.g., read or
write) to it. However, for now we don't do anything with it.
> [herd] Preserve instruction annotations for FAULT events

- doc/gen.tex
- gen/alt.ml
- gen/config.ml
- gen/diy.ml
The new option defines a lower bound for the number of _different_ relaxation candidates that are tested together in `-mix true` mode. It complements the `-maxrelax <n>` options.  Notice that lower and upper bounds are included. As consequence, one tests exactly two candidate relaxations together with `-minrelax 2 -maxrelax 2`.
> [gen] Add -minrelax <n> option to the diy tool.

- herd/libdir/c11_base.cat
- herd/libdir/simple-c11.cat
- herd/libdir/stdlib.cat
This commit fixes a regression by completing commit 9076daa680e4ea550d135837f3940dc9c3e9ed38.
> [herd] Replace `I` by `IW` in cat files.

- gen/CCompile_gen.ml
`atomic_load(x)` is a shortcut for
`atomic_load_explicit(x,memory_order_seq_cst)`
diy generates `atomic_load(x)` calls, however herd does not accept
`atomic_load`, erroring with a message "Macro call atomic_load in CSem"
This patch ensures diy generates `atomic_load_explict(x, seq_cst)` instead
of `atomic_load` so that there is a greater match of tests generated by
diy and tests accepted by Herd
> [gen]: Replace atomic_load gen with atomic_load_explicit

- herd/AArch64Sem.ml
- lib/precision.ml
- lib/precision.mli
MTE provides an asymmetric mode for detecting tag check failures. In particular, when such a mode is configured, only tag checks for load operations are handled in a synchronous (precise) fashion, whereas stores happen asynchronously (imprecise).
This has implications on memory ordering, in that tag checks on loads need to abort execution on the given instruction, but the checks on stores complete asynchronously and the tag check may yet fail at some later time. This can result in different output states from a litmus test running in asymmetric mode depending on the orderings of loads/stores.
An example test that shows such properties is the following:
```
AArch64 MTE-asymmetric
{
0:X0=y:red; 0:X4=x:red; 0:X5=x:green; 0:X6=y:green;
}
P0                 ;
MOV W2,#1          ;
STR W2,[X5] …
```
> [herd] add support for asymmetric MTE fault variant

- Makefile
- herd/AArch64Arch_herd.ml
- herd/AArch64Sem.ml
- herd/ARMSem.ml
- herd/MIPSSem.ml
- herd/PPCSem.ml
- herd/RISCVSem.ml
- herd/archExtra_herd.ml
- herd/branch.ml
- herd/loader.ml
- herd/machAction.ml
- herd/mem.ml
- herd/parseTest.ml
- herd/tests/instructions/AArch64.kvm/A001.litmus
- herd/tests/instructions/AArch64.kvm/A001.litmus.expected
- herd/tests/instructions/AArch64.kvm/A002.litmus
- herd/tests/instructions/AArch64.kvm/A002.litmus.expected
- herd/tests/instructions/AArch64.kvm/A003.litmus
- herd/tests/instructions/AArch64.kvm/A003.litmus.expected
- herd/tests/instructions/AArch64.kvm/A004.litmus
- herd/tests/instructions/AArch64.kvm/A004.litmus.expected
- herd/tests/instructions/AArch64.kvm/A005.litmus
- herd/tests/instructions/AArch64.kvm/A005.litmus.expected
- herd/tests/instructions/AArch64.kvm/kvm.cfg
- herd/tests/instructions/AArch64.self/S06.litmus.expected
- jingle/AArch64Arch_jingle.ml
- lib/AArch64Base.ml
- lib/AArch64Lexer.mll
- lib/AArch64Parser.mly
- litmus/AArch64Compile_litmus.ml
On AArch64 `elr_el1` determines the point at which the fault handler should return to. This means that when an instruction faults we should have an additional event that writes  a label of the current instruction or the instruction address to `elr_el1`. Then, at the end of the fault handler (or otherwise when we execute `eret`), we should jump to the instruction that `elr_el1` points to.
> [herd] Add support for custom fault handlers

- litmus/libdir/_instance.c
- litmus/libdir/_x86_64/kvm-headers.h
Updates to `-mode presi` that follow `-mode kvm` evolution (in particular PR #406).
> [litmus] Fix presi

- lib/AArch64Base.ml
- lib/AArch64Lexer.mll
- lib/procsUser.ml
- lib/procsUser.mli
- litmus/AArch64Arch_litmus.ml
- litmus/AArch64Compile_litmus.ml
- litmus/ARMArch_litmus.ml
- litmus/ASMLang.ml
- litmus/CArch_litmus.ml
- litmus/CLang.ml
- litmus/LISAArch_litmus.ml
- litmus/LISALang.ml
- litmus/MIPSArch_litmus.ml
- litmus/PPCArch_litmus.ml
- litmus/RISCVArch_litmus.ml
- litmus/X86Arch_litmus.ml
- litmus/X86_64Arch_litmus.ml
- litmus/arch_litmus.mli
- litmus/compile.ml
- litmus/handler.ml
- litmus/handler.mli
- litmus/language.ml
- litmus/preSi.ml
- litmus/template.ml
This PR extends the implementation of explicit handlers to EL0.
One of the difficulty to solve is for the actual handler to discriminate between a fault and the final `svc` call. In the first case the user supplied handler should be executed; while in the latter case, a simple branch to end of code should be performed, thereby leaving the exception level at EL1.
> [litmus] Explict handler for EL0 threads

- herd/AArch64Arch_herd.ml
- herd/AArch64Sem.ml
- herd/tests/instructions/AArch64/A24.litmus
- herd/tests/instructions/AArch64/A24.litmus.expected
- herd/tests/instructions/AArch64/A25.litmus
- herd/tests/instructions/AArch64/A25.litmus.expected
- herd/tests/instructions/AArch64/A26.litmus
- herd/tests/instructions/AArch64/A26.litmus.expected
- herd/tests/instructions/AArch64/A27.litmus
- herd/tests/instructions/AArch64/A27.litmus.expected
- jingle/AArch64Arch_jingle.ml
- lib/AArch64Base.ml
- lib/AArch64Lexer.mll
- lib/AArch64Parser.mly
- litmus/AArch64Compile_litmus.ml
This patch adds support for the LDRSB/H AArch64 Instructions
> [all]: Add Load Signed Byte/Half Immediate/Register Instructions

- Makefile
- gen/AArch64Compile_gen.ml
- gen/cycle.ml
- herd/tests/diycross/AArch64.MTE/LB+dmb.sy+amo.ldaddal-polp.litmus.expected
- herd/tests/diycross/AArch64.MTE/LB+dmb.sy+amo.ldaddal-polt.litmus.expected
- herd/tests/diycross/AArch64.MTE/LB+dmb.sypt+amo.ldaddal-polp.litmus.expected
- herd/tests/diycross/AArch64.MTE/LB+dmb.sypt+amo.ldaddal-polt.litmus.expected
- herd/tests/diycross/AArch64.MTE/LB+dmb.sytp+amo.ldaddal-polp.litmus.expected
- herd/tests/diycross/AArch64.MTE/LB+dmb.sytp+amo.ldaddal-polt.litmus.expected
- herd/tests/diycross/AArch64.MTE/LB+dmb.sytt+amo.ldaddal-polp.litmus.expected
- herd/tests/diycross/AArch64.MTE/LB+dmb.sytt+amo.ldaddal-polt.litmus.expected
- herd/tests/diycross/AArch64.MTE/MP+dmb.sy+amo.ldaddal-polp.litmus.expected
- herd/tests/diycross/AArch64.MTE/MP+dmb.sy+amo.ldaddal-polt.litmus.expected
- herd/tests/diycross/AArch64.MTE/MP+dmb.sypt+amo.ldaddal-polp.litmus.expected
- herd/tests/diycross/AArch64.MTE/MP+dmb.sypt+amo.ldaddal-polt.litmus.expected
- herd/tests/diycross/AArch64.MTE/MP+dmb.sytp+amo.ldaddal-polp.litmus.expected
- herd/tests/diycross/AArch64.MTE/MP+dmb.sytp+amo.ldaddal-polt.litmus.expected
- herd/tests/diycross/AArch64.MTE/MP+dmb.sytt+amo.ldaddal-polp.litmus.expected
- herd/tests/diycross/AArch64.MTE/MP+dmb.sytt+amo.ldaddal-polt.litmus.expected
- herd/tests/diycross/AArch64.MTE/MTE.cfg
- herd/tests/diycross/AArch64.MTE/S+dmb.sy+amo.ldaddal-polp.litmus.expected
- herd/tests/diycross/AArch64.MTE/S+dmb.sy+amo.ldaddal-polt.litmus.expected
- herd/tests/diycross/AArch64.MTE/S+dmb.sypt+amo.ldaddal-polp.litmus.expected
- herd/tests/diycross/AArch64.MTE/S+dmb.sypt+amo.ldaddal-polt.litmus.expected
- herd/tests/diycross/AArch64.MTE/S+dmb.sytp+amo.ldaddal-polp.litmus.expected
- herd/tests/diycross/AArch64.MTE/S+dmb.sytp+amo.ldaddal-polt.litmus.expected
- herd/tests/diycross/AArch64.MTE/S+dmb.sytt+amo.ldaddal-polp.litmus.expected
- herd/tests/diycross/AArch64.MTE/S+dmb.sytt+amo.ldaddal-polt.litmus.expected
They were two problems:
1. Memory cell value after the AMO was wrong. This was due to `set_tcell` altering the cell value in state `st`. As far as memtag variant is concerned, there is no reason to do so, as the generated `STG` instruction does not write to the memory location and only change the tag memory. Fixed  in `cycle.ml`.
2. Locations were not adjusted with current tag but with initial tag `0` instead. Fixed in `AArch64Compile_gen.ml`.
> [gen] Fix some bugs related to AMO instructions.

- litmus/AArch64Arch_litmus.ml
- litmus/AArch64Compile_litmus.ml
- litmus/ARMArch_litmus.ml
- litmus/ASMLang.ml
- litmus/CArch_litmus.ml
- litmus/LISAArch_litmus.ml
- litmus/MIPSArch_litmus.ml
- litmus/PPCArch_litmus.ml
- litmus/RISCVArch_litmus.ml
- litmus/X86Arch_litmus.ml
- litmus/X86_64Arch_litmus.ml
- litmus/arch_litmus.mli
- litmus/compile.ml
- litmus/handler.mli
- litmus/hardwareExtra.ml
- litmus/hardwareExtra.mli
- litmus/preSi.ml
- litmus/template.ml
Explicit handlers for EL0 threads are slightly tricky because there is only one slot for two functionalities: execute explicit handler and return to EL1 at end of thread code. This question is solved by using a branch-to-register instruction as handler code and by setting the register according to intended target code.
> [litmus] Simple implementation of explicit handlers from EL0.

- litmus/AArch64Compile_litmus.ml
Small fix that has been neglected for too long.
> [litmus] AArch64, do not emit useless instruction

- herd/libdir/aarch64.cat
The architecture defines a relation called Tag-Ordered-Before for Checked instructions, between the Tag-Check-Read Effect and the Memory Effect generated by that instruction, if any. This Tag-Ordered-Before relation is currently required to be maintained for all Checked instructions. Feedback indicates that Tag-Ordered-Before being maintained for loads is unnecessary for software.
The definition of Tag-ordered-before in Section B2.3 of the spec is changed to read:
If ARMv8.5-MemTag is implemented, a Memory Tag-Check-read R1 is Tag-ordered-before a Checked Memory Write effect W2 generated by the same instruction if and only if all of the following apply:
- there is an Intrinsic data dependendency from R1 to a Conditional-Branching effect B3 generated by the same instruction as R1;
- there …
> [AArch64 MTE] Relaxing Tag-Ordered-Before for Loads

- tools/lexLog_tools.mll
Tag final values `[tag[x] = color` are now recognized.
> [tools] Tools accept tag values in final states

- herd/AArch64Arch_herd.ml
- herd/BellAction.ml
- herd/CAction.ml
- herd/JavaAction.ml
- herd/action.mli
- herd/event.ml
- herd/explicit.ml
- herd/explicit.mli
- herd/machAction.ml
- herd/machModelChecker.ml
Those sets were defined for AArch64 only before. However the concept of explicit and non-explicit accesses looks generic and may appear in any model. Consider for instance "sc-per-location" for explicit accesses.
Of course, the default is for all accesses to be explicit.
> [herd] Define `Exp` and `NExp` sets for all architectures

- herd/libdir/cos-no-opt.cat
- herd/libdir/cos-opt.cat
- herd/libdir/cos.cat
- herd/machModelChecker.ml
- herd/mem.ml
- herd/variant.ml
- herd/variant.mli
That way, using optimisation `-optace true` should not changes output for models that include the `sc per-location` on explict accesses and not on some non-explicit accesses.
> [herd] Limits sc-per-location inner check to explicit accesses

- herd/libdir/cos-ok-opt.cat
- herd/libdir/cos.cat
Some models (namely the LKMM model) use cos-opt.cat directly. Those models cannot include the new co's generator that _requires_ relation `pco` to be computed, which in turn needs option `-optace true`.
Notice that the optmised co's computation introduced by PR #430 is still working, with `cos-opt.cat` now being named `cos-ok-opt.cat`.
> [herd] Restore the `cos-opt.cat` file as it was.

- herd/event.ml
- herd/machModelChecker.ml
- lib/constant.ml
- lib/constant.mli
The effective addresses of herd are pairs of symbols and offset. Conventionally all memory locations reside at page start and different location reside in different pages (litmus in kvm mode follows that convention.
As a consequence the ``load order bytes'' (_i.e_ the offset from page start) are represented by the offset component of effective addresses.
> [herd] Add the `lob-loc` cat pre-defined relation.

- herd/variant.ml
- herd/variant.mli
FEAT_ExS is a feature in AArch64 that controls the semantics of exception entry
and exception return.
> [herd] Add support for AArch64 FEAT_ExS

- lib/miscParser.ml
- tools/prettyProg.ml
+ Avoid untimely call to purposely failing ParsedConstant.compare in latex dumper.
+ Fix oversight in array definition dumping.
> [tools] Fix two glitches in dumper

- litmus/preSi.ml
Tests were failing due to locations such as `x+8`. Those are now identified as `x` in faults.
> [litmus] Fix global location identification.

- lib/AArch64PteVal.ml
- lib/AArch64PteVal.mli
- lib/parsedConstant.ml
- lib/parsedConstant.mli
- lib/pteVal.ml
- lib/pteVal.mli
- tools/archExtra_tools.ml
- tools/archExtra_tools.mli
- tools/madd.ml
- tools/mhash.ml
- tools/mmixer.ml
- tools/mprog.ml
- tools/mrcu.ml
- tools/mselect.ml
- tools/msort.ml
- tools/testInfo.ml
- tools/testInfo.mli
- tools/toolParse.ml
- tools/toolParse.mli
Normalisation applies for options `-mode text -alloc true`.
> [tools] Normalise pteval's in mprog output

- herd/machModelChecker.ml
Those sets were previously empty, they now correctly gather register reads and writes respectively.
> [herd] Correct pre-defined sets for Rreg and Wreg.

- tools/logState.ml
Oddly, the tools lexer could produce lists of outcomes with duplicates, due to the erasure of fault comments. Fix this by removing duplicates early, during normalisation.
> [tools] Remove duplicates from normalized lists of outcomes

- lib/faultType.ml
> [herd] Restore MMU fault types removed by an earlier commit

- herd/BellMem.ml
- herd/CMem.ml
- herd/MemCat.ml
- herd/MemWithCav12.ml
- herd/machModelChecker.ml
- herd/parseTest.ml
This feature is crucial for the LKMM and relevant for all high-level languages, where "instructions"  are composite. The feature is now controlled by configuring the `MachModelChecker` module
> [herd] Partially restore program-order for events from the same instruction

- lib/checkName.ml
- lib/checkName.mli
- tools/lexLog_tools.mli
- tools/lexLog_tools.mll
- tools/mcmp.ml
- tools/mcompare.ml
- tools/mdiff.ml
- tools/mfilter.ml
- tools/mlog2cond.ml
- tools/mlog2name.ml
- tools/moutcomes.ml
- tools/msum.ml
- tools/mtopos.ml
Command line option `-faulttype <bool>` commands reading of fault types in logs. When false, fault types are ignored, restoring old behaviour (_i.e._ before PR #457 ). Default is true.
> [tools] Add `-faulttype` option to tools that read logs

- herd/AArch64Sem.ml
- herd/event.ml
- herd/eventsMonad.ml
- herd/monad.mli
- lib/innerRel.ml
- lib/innerRel.mli
This PR implement combining the memory tag extension and kvm. Result looks satisfactory, some internal dependency links are not perfect though.
As an important side benefit of the PR, dependencies are now similar in both modes. Consider the case of a simple store instruction:
```
AArch64 MTE-W
{
0:X0=x;
}
P0         ;
MOV W1,#1   ;
STR W1,[X0] ;
forall [x]=1
```
The `0:R[W1]1` event (data port read of the store)  does not depend on the validity test  (PTE check or color check respectively) in both modes.
A potential follow-up would be a similar rewriting of the morello mode. Then, the `lift_mem_op` function could get rid of its `mv` argument.
> [herd] kvm and mte combination

- lib/AST.mli
- lib/ASTUtils.ml
- lib/interpreter.ml
- lib/modelLexer.mll
- lib/modelParser.mly
This change adds support for the logical operators '&&', '||' and 'not' in statements where the condition was previously a variant. This way, where previously we could use clauses of the form:
if VARIANT then ... else ...
now, we can use clauses of the form:
if VARIANT_COND then ... else ...
where VARIANT_COND is a VARIANT or a logical operation on multiple VARIANTs using the defined operators.
> [herd] Add cat support for logical operations on variants

- litmus/outUtils.ml
There is an issue with running litmus7 with “-variant self”. Upon running any litmus test, litmus7 complains at:
```
File "any-test.litmus" exception File "litmus/outUtils.ml", line 65, characters 7-13: Assertion failed
```
This is because a certain function is told to “assert false” when printing instructions.
This is an extremely ad-hoc attempt to get litmus7 running. Essentially, it just lets `litmus7` print `"nop"` in the place it needs to: when passing an `inst_t` variable storing the `NOP` instruction to the Assembly block in `codeX` functions.
> A ad-hoc fix for litmus7 with "-variant self"

- herd/Pretty.ml
- herd/event.ml
- herd/libdir/aarch64deps.cat
- herd/machModelChecker.ml
- herd/mem.ml
- herd/memUtils.ml
This new intra-instruction relation corresponds to the situation when some event must precede another even in the absence of output use (data) and existence dependence (control).
> [herd] Introduce relation intra_causality_order

- herd/tests/instructions/AArch64/L041.litmus
- herd/tests/instructions/AArch64/L041.litmus.expected
- herd/tests/instructions/AArch64/L042.litmus
- herd/tests/instructions/AArch64/L042.litmus.expected
- herd/tests/instructions/AArch64/L043.litmus
- herd/tests/instructions/AArch64/L043.litmus.expected
- herd/tests/instructions/AArch64/L044.litmus
- herd/tests/instructions/AArch64/L044.litmus.expected
- herd/tests/instructions/AArch64/L045.litmus
- herd/tests/instructions/AArch64/L045.litmus.expected
Previous definition of address ports, which are crucial to addr dependencies, was a bit too loose. The new definition considers that the address ports of an instruction are the read _register_ effects that are not data ports.
> [herd] New ADDR set for address ports

- litmus/ASMLang.ml
Fixes a small (annoying) glitch. For instance the following test did  _not_ output -2, as it should.
```
AArch64 A
{
int64_t 0:X0=-1;
}
P0           ;
LSL X0,X0,#1 ;
locations [0:X0;]
```
> [litmus] Cast register initial values with their type

- internal/herd_diycross_regression_test.ml
- internal/lib/shelf.ml
- internal/lib/shelf.mli
- internal/lib/tests/command_test.ml
This is a two features PR:
1. when executing tests (e.g. `make test`) on a machine where `python` does not exists, the test program falls back on to `python3`.
2. it is now possible to test with variants in `herd_diy_cross_regression_test` with the option `-variant`, as the other test programs in internal.
With 2, you can now run all the regression tests with a variant (here `T93`) in a simple command:
make test REGRESSION_TEST_MODE="-variant T93 test"
> Tests improvements

- catalogue/aarch64-VMSA/shelf.py
- herd/AArch64Sem.ml
- lib/op.ml
- lib/op.mli
- lib/symbValue.ml
`ToInteger(v1,v2)` yields v1 when v1 is an integer constant or v2 when when v1 is a non-integer constant and v2 is an integer constant. Notice that, when v1 is non-integer the operator fails when v2 is not an integer either.
This operator is used for the computation of flags not to fail when comparison is applied to non-integer constants
such as symbols or page table entries. Of course the N,C and V flags may not be correct w.r.t. hardware in those cases. However the Z flag is correct.
> [herd] Introduce and use the new `ToInteger` operator

- herd/libdir/aarch64hwreqs.cat
The AArch64 cat model is being fixed to restore intent for the hardware requirement arising from a combination of control dependencies and context synchronisation effects (for instance, ISB).
This test is intended to be forbidden, and the fix accounts for that.
```
AArch64 D15347-M-load-shoot+ctrlisb
Variant=precise
{
pte_x=(valid:0); (*invalid*)
0:X2=pte_x;
0:X1=(oa:phy_y); 
0:X3=x;
1:X3=x;
y=1;
pte_z=(af:1,db:1);
0:X8=z; 
1:X8=z;
}
P0              | P1;
STR X1,[X2]     | LDR W7,[X8] ;
DSB ISH         | CBZ W7,L1   ;
LSR X9,X3,#12   | ISB         ;
TLBI VAAE1IS,X9 |L0:          ;
DSB ISH         | LDR W4,[X3] ;
MOV W7,#1       |L1:          ;
STR W7,[X8]     |             ;
locations [1:X4;]
exists(1:X7=1 /\ fault(P1:L0,x))
```
> [AArch64 cat] a fix to the ctrl+isb ordering to restore intent

- herd/libdir/aarch64deps.cat
- herd/libdir/aarch64hwreqs.cat
The AArch64 cat model is being fixed to restore intent for the hardware requirement arising from a combination of address dependencies and TLBI instructions.
This following test is intended to be forbidden, and the fix implements that.
```
AArch64 MP+dmb.ish+addr-tlbi-dsb.ish-isb
{
z = y;
0:X0=(oa:PA(x),valid:0);
0:X1=pte_x; 0:X2=x; 0:X3=z;
1:X3=z;
}
P0           | P1              ;
STR X0,[X1]  | LDR X2,[X3]     ;
DMB ISH      | LSR X9,X2,#12   ;
STR X2,[X3]  | TLBI VAAE1IS,X9 ;
| DSB ISH         ;
| ISB             ;
| LDR X4,[X2]     ;
exists 1:X2=x /\ ~fault(P1,x,MMU:Translation)
```
> [AArch64 cat] a fix to the addr+tlbi ordering to restore intent

- herd/herd.ml
- herd/lexConf_herd.mll
- herd/opts.ml
- herd/opts.mli
- herd/parseTest.ml
- herd/prettyConf.ml
- herd/prettyConf.mli
- herd/show.ml
- herd/top_herd.ml
- herd/view.ml
- herd/view.mli
This option commands the tool used for displaying execution diagrams. Recognised viewers are gv, evince and preview. Options `-gv` and `-evince` are kept for backward compatibility.
> [herd] Add `-view <viewer>` command line option.

- lib/lexSplit.mli
- lib/lexSplit.mll
- tools/lexLog_tools.mll
- tools/logState.ml
Arrays were previously handled as strings in parsing, printing and comparison, resulting in printing inconsistencies and wrong comparisons in the case of arrays of integers.
Now, arrays are lexed as lists of their elements and integer elements are normalised and compared as integers.
The changes result in consistent output (all integers shown in hexadecimal when specified) and correct equality of arrays.
> [tools] Better management of arrays in tools

- lib/Archs.mli
- litmus/KSkel.ml
- litmus/dumpRun.ml
- litmus/litmus.ml
- litmus/option.ml
- litmus/option.mli
- litmus/preSi.ml
- litmus/skel.ml
- litmus/skelUtil.ml
- litmus/top_litmus.ml
- litmus/top_litmus.mli
It is now possible to compile C litmus tests without specifying a target architecture. However, in that case, the `-c11 true` option is mandatory. This simple feature is useful for a few quick, initial, tests on a new architecture, where a C11 compiler is available.
> [litmus] Compilation of C litmus tests with no `-carch <arch>` option.

- lib/mySet.ml
- lib/mySet.mli
Helper function takes lists of lists and gets the set of all elements
I use this function in a later commit, so I am uploading it first
> [lib]: Added uniq_lists to MySet

- lib/mySys.ml
- lib/mySys.mli
This function makes a linux call to `mkdir -p` to create a directory if it does not already exist.
I use this in a later commit and am uploading this first.
> [lib]: Added mkdir -p helper function

- lib/AArch64Base.ml
Consider the instruction `LDXP X1, X2, [X3]`
When printed using `pp_ldxp` in `lib/AArch64Base` the first register is printed as an `W`reg when it should be printed as an `X` reg.
This patch amends pretty printing to this effect.
Side effect: Hashes in tests are updated
> [lib]: LDXP Pretty Printing

- lib/constant.ml
- lib/constant.mli
This patch adds a helper function used in a later commit. `mk_sym_with_index` allows us to create symbolic location `v` with a specified offset `i`
> [lib]: added mk_sym_with_index helper function

- herd/libdir/aarch64hwreqs.cat
The AArch64 cat model is being fixed to restore intent in two ways. Firstly, Exception Entry Effects are Context Synchronisation Events __unconditionally__. Secondly, it is a hardware requirement to preserve the ordering induced by a control dependency to a hardware update of a dirty bit.
The following litmus test, now forbidden, illustrates the `[R & Exp]; ctrl; [HU]` fix.
```
AArch64 LB-HD+dmb.ld+ctrl
TTHM=P1:HD
{
x=0; z=0;
PTE(x)=(oa:PA(x),db:0,dbm:1);
0:X1=PTE(x);
0:X3=z;
1:X3=z; 1:X5=x;
}
P0          | P1            ;
LDR X0,[X1] |  LDR W2,[X3]  ;
DMB LD      |  CBNZ W2, L0  ;
MOV W2, #1  | L0:           ;
STR W2,[X3] |  MOV W4,#1    ;
|  STR W4,[X5]  ;
exists 0:X0=(oa:PA(x),db:1,dbm:1) /\ 1:X2=1
```
> [AArch64] Fixes for ctrl+HU and EXC-ENTRY-CSE to restore the intent

- herd/AArch64Sem.ml
- herd/libdir/asl-pseudocode/csel.asl
- herd/tests/instructions/AArch64.ASL/CSEL02.litmus
- herd/tests/instructions/AArch64.ASL/CSEL02.litmus.expected
- herd/tests/instructions/AArch64/L053.litmus
- herd/tests/instructions/AArch64/L053.litmus.expected
- lib/AArch64Base.ml
Notice that both the name "NZCV" and the semantics of the `MRS Xt,NZCV` and `MSR NZCV,Xt` instructions suggest that bit "N" is the high order bit, bit "Z" is the next bit etc. This entails changing the previous encoding, where "N" was the low order bit of an ad-hoc register that represents the N, Z, C and B bits of PSTATE.
As a tribute to how code was written, changes are minimal.
> [herd,litmus] Introduce NZCV argument to the MRS and MSR instructions

- tools/lexLog_tools.mll
However, as litmus cannot (yet?) output such values. The feature will be useful for comparing herd logs only.
> [tools] Handle name+offset value in logs

- gen/config.ml
- gen/diy.ml
- gen/diycross.ml
- gen/diyone.ml
- gen/dumpAll.ml
- gen/dumpAll.mli
- gen/top_gen.ml
This PR implements support for 2 new options. 
-stdout allows the user to output litmus tests to stdout
-cycleonly allows the user to output only the cycle name of a test and not the main body.
This code was written with support from @murzinv
> [diy7] support for stdout and cycle only output

- herd/libdir/aarch64util.cat
- herd/libdir/c11_cos.cat
Occurrences of `I` (for the set of initial writes) in cat files are deleted or replaced by `IW`.
> [herd] Get rid of the last two occurrences of cat variable `I`

- herd/CSem.ml
- herd/tests/instructions/C/C03.litmus
- herd/tests/instructions/C/C03.litmus.expected
- jingle/CArch_jingle.ml
- jingle/cDumper.ml
- lib/CBase.ml
- lib/CParser.mly
- lib/dune
- tools/mlisa2c.ml
- tools/mlock.ml
Consider the following test:
```
C C03
{}
P0 (int *y) {
atomic_fetch_add_explicit(y,1,memory_order_seq_cst);
}
forall y=1
```
This test cannot be parsed, since the grammar expects the result of the expression to be written to a local register (e.g. `r0 = ...`)
This patch allows the above to be parsed and simulated under herd
> [all]: Added C support for non-storing expressions

- gen/dumpAll.ml
all that was needed was a simple change, changing printf to print as the print variable is already defined previously to change depending on Config.stdout (line 440)
> [diy7] output generated number of tests to stderr when option -stdout true

- herd/AArch64Sem.ml
- herd/eventsMonad.ml
- herd/monad.mli
That one "lifts up" one arrow. This useful to fix the dependency of postfixed instruction in `-variant vmsa` mode. More precisely  the `iico_data` arrow from page table entry load to writeback is replaced by a `iico_data` from address register read to writeback.
> [herd] Another "scissor" monad combinator

- Makefile
- herd/RISCVParseTest.ml
- herd/RISCVParseTest.mli
- herd/parseTest.ml
- herd/tests/instructions/RISCV/A01.litmus
- herd/tests/instructions/RISCV/A01.litmus.expected
- herd/tests/instructions/RISCV/A02.litmus
- herd/tests/instructions/RISCV/A02.litmus.expected
- herd/tests/instructions/RISCV/A03.litmus
- herd/tests/instructions/RISCV/A03.litmus.expected
Fix a very unfortunate bug: RISCV was implemented by MIPS.
> Fix herd RISCV

- lib/miscParser.ml
This PR is to ensure that tests featuring different DIC/IDC requirements have different hashes.
> [ifetch] Use CacheType parameters in hashes

- gen/alt.ml
This patch rejects generation of cycle when -safe and -relax are used in a configuration file, but relaxations in -relax cannot generate cycles.
Currently, the generator still generates cycles from the safe list if this is the case.
an example of where this can occur is:
`diy7 -cycleonly true -arch AArch64 -safe "DMB.SYd** Rfe Fre Coe" -relax "[PodRR,PodWR]"`
The reason for this patch is that in our current flow, some composite relaxations are automatically generated to go into `-relax`, Occasionally junk relaxations are accidentally created (e.g. [PodRR, PodWR]), which cannot provide cycles, however the generator will still use relaxations in -safe. 
This patch introduces a fail safe to stop this behaviour.
> [gen] reject generation if -relax cannot provide cycles

- doc/common.tex
- doc/examples.tex
- doc/gen.tex
- gen/alt.ml
- gen/code.ml
- gen/code.mli
- gen/config.ml
- gen/cycle.ml
- gen/diy.ml
- gen/edge.ml
Change the default mode of the `diy` tool. The new mode is similar to the old `sc` mode. However the new `default` mode is such that adding "safe" relaxations cannot reduce the set of generated cycles. Also enhance `diy` mode documentation.
> [gen] Change the default mode of `diy`, simplify the sc mode

- herd/tests/instructions/AArch64.neon/V57.litmus
- herd/tests/instructions/AArch64.neon/V57.litmus.expected-failure
- herd/tests/instructions/AArch64.neon/V58.litmus
- herd/tests/instructions/AArch64.neon/V58.litmus.expected-failure
- herd/tests/instructions/AArch64/A127.litmus
- herd/tests/instructions/AArch64/A127.litmus.expected
- herd/tests/instructions/AArch64/A131.litmus
- herd/tests/instructions/AArch64/A131.litmus.expected
- herd/tests/instructions/AArch64/A135.litmus
- herd/tests/instructions/AArch64/A135.litmus.expected-failure
- herd/tests/instructions/AArch64/A136.litmus
- herd/tests/instructions/AArch64/A136.litmus.expected-failure
- herd/tests/instructions/AArch64/A137.litmus
- herd/tests/instructions/AArch64/A137.litmus.expected-failure
- herd/tests/instructions/AArch64/A138.litmus
- herd/tests/instructions/AArch64/A138.litmus.expected-failure
- herd/tests/instructions/AArch64/A140.litmus
- herd/tests/instructions/AArch64/A140.litmus.expected-failure
- lib/AArch64Base.ml
- lib/AArch64Parser.mly
Consider the following test (herd/tests/instructions/AArch64/A127):
```
AArch64 A127
(* MOV value from symbolic register into concrete reg *)
{ uint64_t X0; uint64_t %symbolic_reg = x; uint64_t x }
P0;
MOV X0, %symbolic_reg;
exists (0:X0 = x)
```
This fails when run in herd as `map_reg` and `fold_reg` are not implemented for `I_MOV` when the second argument (of type `'k kr`) is a register value (`RV`).
This patch fixes this. I have added tests for this which pass in herd and litmus on an Apple M1 machine.
Additionally I considered all other AArch64 instructions that have a `kr` element in their type and fixed those so they pass in both herd7, precisely for:
`LDG`, `STZG`, `STG`, `LDP_SIMD`, `STP_SIMD`, `LDP_SIMD`, `STR`, `ALIGND`, and `ALIGNU`
The tests I added for these instructions pass …
> [lib]: fixed map_reg, fold_reg for kr instructions

- herd/AArch64Sem.ml
- jingle/AArch64Arch_jingle.ml
- lib/AArch64Base.ml
- lib/AArch64Parser.mly
- litmus/AArch64Compile_litmus.ml
Instruction `LDP`, `STP` and `LPDSW` are simplified, avoiding non-implemented addressing modes.
This is an extension of PR #540.
> [all] Simplification of pair instruction address fields.

- herd/archExtra_herd.ml
- herd/machAction.ml
- jingle/CArch_jingle.ml
- lib/CBase.ml
- lib/constant.ml
- lib/constant.mli
- lib/symbConstant.ml
- lib/symbValue.ml
- lib/value.mli
- litmus/ASMLang.ml
- litmus/CArch_litmus.ml
- litmus/KSkel.ml
- litmus/LISALang.ml
- litmus/archExtra_litmus.ml
- litmus/compile.ml
- litmus/constr.ml
- litmus/outUtils.ml
- litmus/preSi.ml
- litmus/skel.ml
- litmus/switch.ml
- litmus/template.ml
- tools/alpha.ml
- tools/logConstr.ml
Symbolic values are instrumental to herd first phases, before determining concrete values.
In some circumstances, such as a in the final state of a LB+datas test with no OOTA provision, symbolic values can find their way to later stages. Then, it may be convenient to "freeze" them as constants. The transformation currently applies when symbolic values are stored in constant vectors in final values.
Consider the following test:
```
AArch64 LB+data+pairs
{
int64_t x[2]; int64_t y[2];
0:X0=x; 0:X3=y;
1:X0=y; 1:X3=x;
}
P0             | P1             ;
LDP X1,X2,[X0] | LDP X1,X2,[X0] ;
STP X2,X1,[X3] | STP X2,X1,[X3] ;
locations [x;y;]
```
Previous versions of herd with command line `herd7 -cat cos.cat` were failing. Now we have:
```
Test LB+data+pairs Required
States 4
x={0,0}; y={0,0}; …
```
> [all] Add frozen symbolic values as constants

- gen/typBase.ml
- herd/tests/instructions/C/C08.litmus
- herd/tests/instructions/C/C08.litmus.expected
- herd/tests/instructions/C/C11.litmus
- herd/tests/instructions/C/C11.litmus.expected
- herd/tests/instructions/C/c.cfg
- lib/CLexer.mll
- lib/CType.ml
- lib/stateLexer.mll
- lib/stateParser.mly
- lib/testType.ml
Motivation: Test int128 programs generated by diy are not parsed by herd.
This patch fixes the following bugs in the int128 implementation:
- `diy7` did not parse `-type uint128_t`
- litmus tests with the initial state `_Atomic __int128 x = 0` did not parse
- `diy` generates C/C++ litmus tests using the `(u)int128_t` which not valid in LLVM/GCC. Instead we generate tests using `__(u)int128`.
A future patch will fix `herd` so that it accepts `__int128` data in AArch64 (It is conceptually a separate patch that deals with Semantics).
Tests are provided in this patch
> [lib/gen]: fixed __int128 parsing

- tools/mlog2cond.ml
This commit implements the ability to negate the final condition when using mlog2cond7. 
The reason for implementing this is to catch cases where HW is completely unpredictable and breaks all the rules, such as memory/register corruption issues in HW. This would create a state that isn't included within the forbidden state of a litmus test, but we would still want to catch.
By negating the possible states from herd7 output (for forbidden tests), we would be able to catch the forbidden state as well as unpredictable states due to HW issues.
e.g.
Litmus test with following forbidden state:
`exists (1:X1=1 /\ 1:X2=1)`
has these possible states (from herd output)
`1:X1=1;1:X2=0;`
`1:X1=0;1:X2=1;`
we want as forbidden state
`~exists ((1:X1=1 /\ 1:X2=0) \/ (1:X1=0 /\ 1:X2=1))`
I tried to do …
> [tools] Implement option to negate final condition with mlog2cond

- herd/tests/instructions/AArch64.kvm/A017.litmus
- herd/tests/instructions/AArch64.kvm/A017.litmus.expected
- herd/top_herd.ml
- lib/fault.ml
- lib/fault.mli
Fix a glitch : some lines in outcomes with negative faults were printed more than once.
The root cause is the introduction of fault types in negative faults matching. More precisely, when the pattern contains some fault type A, and that there are two outcomes that are almost identical, except that  one has fault of type B and the other has no fault, then two identical lines with ~fault(...,A) were printed. The fix consists in discarding  the outcome with the fault of type B, as the observation of this fault is in fact not specified.
This PR  complements PR #473.
> [herd] Fix double neg fault

- asllib/tests/dune
- dune
- dune-project
- herdtools7.opam
Questions that need answer before merging:
> [asl] Fix build for dune<3.0

- defs-mini.sh
- defs.sh
- version-gen.sh
Gains 2s in every `make build` by making `./version.sh` instant.
This PR just divides `defs.sh` into two parts:
- `defs-mini.sh` which just defines what are needed by `version-gen.sh`, viz. `$REV` and `$VERSION`.
- `defs.sh` that parse dune files to find executables, using `defs-mini.sh`, and which is used by the other shell scripts
Before:
```shell
$ time ./version-gen.sh $HOME
./version-gen.sh $HOME  1.27s user 0.47s system 92% cpu 1.870 total
```
After:
```sh
$ time ./version-gen.sh $HOME
./version-gen.sh $HOME  0.01s user 0.02s system 67% cpu 0.043 total
```
> [build] Improve build time in ./version-gen.sh

- catalogue/aarch64-pick/shelf.py
- catalogue/aarch64-pick/tests/LB-ldxr-stxr-rel.litmus
- catalogue/aarch64-pick/tests/LB-swp-rel.litmus
- catalogue/aarch64-pick/tests/desired-kinds.txt
- herd/libdir/aarch64deps.cat
- herd/tests/instructions/AArch64/L035.litmus.expected
- herd/tests/instructions/AArch64/L037.litmus.expected
- herd/tests/instructions/AArch64/L038.litmus.expected
- herd/tests/instructions/AArch64/L040.litmus.expected
In aarch64deps.cat, the definition of Pick-Dependencies-Through-Registers-and-Memory (pick-dtrm) erroneously referenced iico_order. This entails that the following test LB-swp-rel was forbidden, against the architectural intent:
```
AArch64 LB-swp-rel
{
0:X1=x; 0:X3=y; 0:X10=z;
1:X1=y; 1:X3=x;
}
P0                 | P1           ;
LDR W0,[X1]        | LDR W0,[X1]  ;
SWP W0, W12, [X10] |              ;
EOR W22, W12, W12  |              ;
ADD W2, W22, #1    | MOV W2,#1    ;
STR W2,[X3]        | STLR W2,[X3] ;
exists
(0:X0=1 /\ 1:X0=1)
```
Indeed the following sibling test LB-ldxr-stxr-rel was and still is correctly allowed:
```
AArch64 LB-ldxr-stxr-rel
{
0:X1=x; 0:X3=y; 0:X10=z;
1:X1=y; 1:X3=x;
}
P0                 | P1           ;
LDR W0,[X1]        | LDR W0,[X1]  ;
LDXR W12,[X10]     | …
```
> [AArch64 cat] Adjust pick-dtrm definition to restore intent

- herd/libdir/aarch64.cat
- herd/libdir/aarch64bbm.cat
- herd/libdir/aarch64hwreqs.cat
- herd/libdir/aarch64util.cat
- herd/libdir/tlbi-after.cat
This PR performs the following adjustments:
* Gives a name to a relation already included into `ob` (`haz-ob`)
* Removes several redundant endpoint constraints in relations (for instance, in `tlbi-ca`)
* Renames the relation `si` into `sca-class` and refines its use in `lob` and `ob`
* Renames occurrences of the `PTE` set into `TTD`
* Reorders endpoint constraints from, say, `R & PTE & Imp` into `Imp & TTD & R`
> [AArch64] Adjustments to the VMSA model in sync with Arm ARM J.a

- litmus/libdir/_aarch64/kvm-headers.h
This is necessary after the upstream change:
https://gitlab.com/kvm-unit-tests/kvm-unit-tests/-/commit/25ea27e9b9be5d27bc1d682d201c39274586e488
> [litmus] Rename mmu_get_pte to follow_pte

- defs-mini.sh
- defs.sh
- dune
- dune-build.sh
- dune-install.sh
- herd-www/dune
- herd/dune
- herdtools7.opam
- version-gen.sh
This commit:
1. Changes the alias `@default` of dune to simply `@install` and `internal/all`. This takes the place of the alias `@zyva` which is deleted. This doesn't change anything for people using the Makefile. The rationale behind this is:
-  nothing else in the subdirectories needs to be built;
- `herd-www` does not feature anything installable;
- aliasing `@default` to `@install` was the behavior for `dune < 2.0.0` which just changed last week with #580;
- the `make test` part that uses executables that are not installable and not in internal are built with `dune runtest`;
- probably `make build` should not fail if `js_of_ocaml-ppx` is not installed, see 2.
2. The preprocessing in `herd-www` with `js_of_ocaml-ppx` is now optional, which should not change anything in our …
> [dune] Fix `dune build` when no js_of_ocaml

- litmus/preSi.ml
Emitted C code was not syntactically correct. Introduced by PR #583, probably while resolving conflicts.
> [litmus] Fix glitch

- litmus/ASMLang.ml
The cast fills  the gap from argument type (typically `* x_t`, when `x_t` is an array type) and register type (typically pointer to int).
Standard registers (_i.e._ non-stable) do not present the same difficulty because there is no C-level typing of inline assembly input and output.
> [litmus] Add a cast onto "stable registers" initial values.

- herd/AArch64ASLSem.ml
- herd/machModelChecker.ml
- herd/tests/instructions/C/C12.litmus
- herd/tests/instructions/C/C12.litmus.expected
- jingle/cDumper.ml
- lib/AArch64Parser.mly
- lib/ASLBase.ml
- lib/BellCheck.ml
- lib/CGenParser_lib.ml
- lib/CLexer.mll
- lib/CParser.mly
- lib/JavaGenParser_lib.ml
- lib/LISAParser.mly
- lib/dune
- lib/genParser.ml
- lib/miscParser.ml
- lib/miscParser.mli
- lib/outStd.ml
- lib/outTar.ml
- lib/outTests.mli
- litmus/compile.ml
- litmus/top_klitmus.ml
- litmus/top_litmus.ml
- tools/CDumper.ml
- tools/mlisa2c.ml
- tools/mlock.ml
- tools/transposeDumper.ml
Add region/scope parsing to C parser, made extra data list
This patch allows us to add region and scope information to C tests.
This also changes the extra_data parameter to store a list of data
so we can pass multiple things into the test.
For C tests, extra_data is where metadata about shared data is stored as
well as region information - we need to preserve both
> [all]: Add Region parsing to C Parser

- herd/AArch64Arch_herd.ml
- herd/AArch64Sem.ml
- herd/ARMArch_herd.ml
- herd/BellArch_herd.ml
- herd/GenericArch_herd.ml
- herd/JavaArch_herd.ml
- herd/MIPSArch_herd.ml
- herd/PPCArch_herd.ml
- herd/RISCVArch_herd.ml
- herd/X86Arch_herd.ml
- herd/X86_64Arch_herd.ml
- herd/arch_herd.mli
- herd/cmo.ml
- herd/cmo.mli
- herd/machAction.ml
- lib/AArch64Base.ml
This patches creates an architecture independent CMO action and uses it to encapsulate the DC and IC events (for AArch64). In parallel, it cleans up the relevant eventsets for AArch64, and similarly to what herd does for barriers, every DC and IC instruction will raise an eponymous event (a dc.cvau,Xt will raise a DC.CVAU event, etc).
> [herd] Refactor DC and IC actions into a common CMO

- lib/CParser.mly
As `atomic` is now a keyword and is also part of annotations (arguments of internal linux model primitives), change annotation parsing accordingly, Fixes regression introduced by PR #522.
> [herd] Fix C parser

- herd/archExtra_herd.ml
- herd/machAction.ml
- jingle/CArch_jingle.ml
- lib/CBase.ml
- lib/constant.ml
- lib/constant.mli
- lib/misc.ml
- lib/myMap.ml
- lib/symbConstant.ml
- lib/symbValue.ml
- litmus/ASMLang.ml
- litmus/CArch_litmus.ml
- litmus/KSkel.ml
- litmus/LISALang.ml
- litmus/archExtra_litmus.ml
- litmus/compile.ml
- litmus/constr.ml
- litmus/outUtils.ml
- litmus/preSi.ml
- litmus/skel.ml
- litmus/switch.ml
- litmus/template.ml
- tools/alpha.ml
- tools/logConstr.ml
This PR adds a new type of constants: records!
Those records are just a variation over vectors: instead of being a list of other constants, they map labels (`string`s) to other constants.
They will be used to implement records and exceptions in ASL.
> [lib] Add new record constants

- lib/stateLexer.mll
- tools/lexLog_tools.mll
A quick lex-level hack to enable running tools on some recent tests.
> [all] Accept "TTD" as a synomym for "PTE"

- litmus/libdir/_main.c
Fix is easy: perform feature check as soon as possible before allocating memory.
> [litmus] Fix space leak in _main.c

- herd/archExtra_herd.ml
- herd/herd.ml
- herd/lexConf_herd.mll
- herd/mem.ml
- herd/opts.ml
- herd/opts.mli
- herd/runTest.ml
- herd/runTest.mli
- herd/top_herd.ml
This change adds a new argument that changes herd7 behaviour to reports all faults that have occured in an execution. This is regardless of the post-condition of the test and whether it includes the relevant fault atom. For example, for the test:
```
AArch64 LDRaf0-noHA
{
[PTE(x)]=(af:0);
[x]=1;
0:X1=x;
}
P0          ;
LDR W2,[X1] ;
exists(0:X2=1)
```
```
$> herd7 -variant vmsa,fatal LDRaf0-noHA.litmus
Test LDRaf0-noHA Allowed
States 1
0:X2=0;
No
Witnesses
Positive: 0 Negative: 1
Condition exists (0:X2=1)
Observation LDRaf0-noHA Never 0 1
Time LDRaf0-noHA 0.01
Hash=4699e00b11f34b7adf65ba97458fdb7f
```
Whereas with the new argument:
```
$> herd7 -variant vmsa,fatal -dumpallfaults true LDRaf0-noHA.litmus est LDRaf0-noHA Allowed
States 1
0:X2=0; Fault(P0,x,MMU:AccessFlag);
No
Witnesses …
```
> [herd] Add -dumpallfaults argument

- Makefile
- herd/ARMArch_herd.ml
- herd/ARMSem.ml
- herd/libdir/aarch32.cat
- herd/tests/instructions/AArch32/A016.litmus
- herd/tests/instructions/AArch32/A016.litmus.expected
- herd/tests/instructions/AArch32/A016.litmus.expected-warn
- herd/tests/instructions/AArch32/A017.litmus
- herd/tests/instructions/AArch32/A017.litmus.expected
- herd/tests/instructions/AArch32/A017.litmus.expected-warn
- herd/tests/instructions/AArch32/A018.litmus
- herd/tests/instructions/AArch32/A018.litmus.expected
- herd/tests/instructions/AArch32/A018.litmus.expected-warn
- herd/tests/instructions/AArch32/A019.litmus
- herd/tests/instructions/AArch32/A019.litmus.expected
- herd/tests/instructions/AArch32/A019.litmus.expected-warn
- herd/tests/instructions/AArch32/aarch32.cfg
- jingle/ARMArch_jingle.ml
- lib/ARMBase.ml
- lib/ARMLexer.mll
- lib/ARMParser.mly
- litmus/ARMCompile_litmus.ml
This patch is required to assist Arm's Compiler team.
We wish to test the compilation of AArch32 code. In particular Load Acquire/Store Release (exclusive) instructions.
This patch adds `LDA{EX}` (register) and `STL{EX}` register.
Tests are provided.
This is a work in progress as:
- ~~I am testing these additions on AArch32 hardware (using litmus) as we speak.~~ Validated on Graviton 3
- ~~herd produces incorrect results under the arm.cat model (I have made changes to support acquire/release(exclusive) semantics but the outcomes of `A019` is allowed when it should be forbidden. @maranget do you have any advice on what I may have missed?~~ FIXED
> Add LDA/LDAEX, STL,STLEX Instructions to ARM

- herd/AArch64ASLSem.ml
- herd/ASLSem.ml
- herd/libdir/asl-pseudocode/implementations.asl
- herd/tests/instructions/AArch64.ASL/CSEL01.litmus.expected-warn
- herd/tests/instructions/AArch64.ASL/CSEL02.litmus.expected-warn
- herd/tests/instructions/AArch64.ASL/LDR02.litmus
- herd/tests/instructions/AArch64.ASL/LDR02.litmus.expected
- herd/tests/instructions/AArch64.ASL/STR02.litmus
- herd/tests/instructions/AArch64.ASL/STR02.litmus.expected
- herd/tests/instructions/AArch64.ASL/asl.cfg
- herd/tests/instructions/ASL/double-load.litmus
- herd/tests/instructions/ASL/double-load.litmus.expected
- herd/variant.ml
- herd/variant.mli
At the moment, tested accesses are the 32bits ones: `LDR W0,[X1]`, `STR W0,[X1]`.
The PR also includes two new variants `-variant warn` (warn if some feature is not implemented) and `-variant strict` (fail if some feature is not implemented). At the moment those variants apply to the ASL variant of AArch64.
> [asl] Memory accesses of various width

- herd/ARMArch_herd.ml
- herd/ARMSem.ml
- herd/tests/instructions/ARM/A020.litmus
- herd/tests/instructions/ARM/A020.litmus.expected
- herd/tests/instructions/ARM/A021.litmus
- herd/tests/instructions/ARM/A021.litmus.expected
- herd/tests/instructions/ARM/A022.litmus
- herd/tests/instructions/ARM/A022.litmus.expected
- herd/tests/instructions/ARM/A023.litmus
- herd/tests/instructions/ARM/A023.litmus.expected
- jingle/ARMArch_jingle.ml
- lib/ARMBase.ml
- lib/ARMLexer.mll
- lib/ARMParser.mly
- litmus/ARMCompile_litmus.ml
This patch adds new instructions including:
- LDR/STR Barrel shifter
- ARM Push/POP + FP Register
- ANDEQ
- MOVWEQ MOVTEQ
Tests are provided and tested on a Raspberry Pi2. This patch set is ready to go
> [ARM]: Add ARM instructions

- asllib/Interpreter.ml
- asllib/PP.ml
- asllib/PP.mli
- herd/tests/instructions/ASL/globals.litmus
- herd/tests/instructions/ASL/globals.litmus.expected
Before this PR the following test could not be executed:
```
ASL T
{ }
var x : integer = 1;
begin
let y = x;
return 0;
end
```
Executing `herd7 T.litmus` yielded:
```
Contradiction on reg 0:x: 1 vs. 0
Fatal: File "T.litmus" Adios
Fatal error: exception File "herd/mem.ml", line 820, characters 16-22: Assertion failed
```
Namely,  the read event of `x` emitted by the interpreter for executing `let y = x`, of which value is one, could not match the default initial write event of `x`  (value zero).
> [asl] Emit a write event for every global storage declaration

- asllib/AST.mli
- asllib/ASTUtils.ml
- asllib/ASTUtils.mli
- asllib/Interpreter.ml
- asllib/PP.ml
- asllib/Parser.mly
- asllib/Parser0.mly
- asllib/Serialize.ml
- asllib/StaticEnv.ml
- asllib/StaticEnv.mli
- asllib/Typing.ml
- asllib/tests/asl/required/assign-v0.asl
- asllib/tests/asl/required/typing-assign-v0.asl
- asllib/tests/asltests.ml
- asllib/tests/helpers.ml
In version V0, variable declaration is optional, this has consequences:
+ Typing is partial and some function calls may not get all their extra parameters.
+ Interpretation fails on first assignments of undeclared variables, flagging an "Undefined variable" error.
Fix this by considering first assignments of undeclared variables as declarations of (mutable) variables.
> [asl] Have first assignments in ASL version 0 behave as local declarations

- litmus/top_litmus.ml
- litmus/variant_litmus.ml
- litmus/variant_litmus.mli
The one effect is checking that option `-mode kvm` is given.
> [litmus] Accept `-variant vmsa`

- asllib/AST.mli
- asllib/ASTUtils.ml
- asllib/Interpreter.ml
- asllib/Lexer.mll
- asllib/PP.ml
- asllib/Parser.mly
- asllib/Parser0.mly
- asllib/Serialize.ml
- asllib/SimpleLexer0.mll
- asllib/Typing.ml
`DEBUG e;` prints the value of `e` to standard error.
One can use keyword `debug`  in ASLv1.
> [asl] DEBUG statement

- asllib/bitvector.ml
- asllib/tests/asl/required/concat01.asl
- asllib/tests/asl/required/concat02.asl
- asllib/tests/asl/required/concat03.asl
Tests `concat01.asl` and `concat02.asl` were failing. Test `concat03.asl` was failing during development .
Tests are in `directory asllib/tests/asl/required/`
> [asl] Fix bitvector concatenation

- herd/AArch64ASLSem.ml
- herd/tests/instructions/AArch64.ASL/ADD01.litmus
- herd/tests/instructions/AArch64.ASL/ADD01.litmus.expected
- lib/AArch64Base.ml
- lib/ARMBase.ml
- lib/ASLBase.ml
- lib/BellBase.ml
- lib/CBase.ml
- lib/JavaBase.ml
- lib/MIPSBase.ml
- lib/PPCBase.ml
- lib/RISCVBase.ml
- lib/X86Base.ml
- lib/X86_64Base.ml
- lib/archBase.mli
- lib/genParser.ml
- lib/pseudo.ml
This PR introduces a call to the  `A.is_valid` function just after test parsing, thereby providing the ability to check instructions beyond syntactic correctness early. For instance `ADD W0,WZR,#1` is illegal and is checked that way.
+ Instruction with negative constants are aliases. For instance,   `ADD W0,W0,#-1` is executed as `SUB W0,W0,#1`.
+ Using register `ZR` in some positions is not possible, as the encoded instruction reserve this place for the stack pointer. For instance `ADD W0,WZR,#1` is in fact illegal, was executed as `ADD W0,SP,#1` and was working by miracle.
> [asl,herd] Fix  the ADD/SUB immediate instructions implementation

- litmus/template.ml
The bug was considering that conditional branches with displacement arguments were behaving as always taken --- In other words, the "Next" control flow information was ignored for those instructions, resulting in wrong live-in information and finally missing initialisations.
Bug discovered on this test:
```
AArch64 A
{
int 1:X2=0;
0:X0=x;
1:X0=x;
}
P0          |  P1          ;
|L1:           ;
MOV W1,#1   | LDR W1,[X0]  ;
STR W1,[X0] | CBZ W1,.-4   ;
| ADD W2,W2,#2 ;
locations [1:X2;]
forall 1:X2=2
```
The litmus tool was not issuing an initialisation of the register `1:X2` resulting in random results.
> [litmus] Fix control flow for liveness

- herd/AArch64ASLSem.ml
There are still difficulties. with NZCV flags. The following test. crashes:
```
AArch64 T
{
int x=1;
0:X8=x;
}
P0           ;
MOV W0,#1     ;
LDR W1,[X8]   ;
ADDS W2,W1,W0 ;
ADDS W2,W1,W0 ;
locations [0:X2;]
```
> [herd,asl] Fix inversion of ADD and ADDS semantics.

- herd/AArch64Sem.ml
- herd/tests/instructions/AArch64/AK001.litmus
- herd/tests/instructions/AArch64/AK001.litmus.expected
- herd/tests/instructions/AArch64/AK002.litmus
- herd/tests/instructions/AArch64/AK002.litmus.expected
- herd/tests/instructions/AArch64/AK003.litmus
- herd/tests/instructions/AArch64/AK003.litmus.expected
This is a draft PR aimed at making indirect branches create control dependencies.
The idea is to simply let the indirect branches to create a "commit" type of an event; then the `aarch64deps.cat` should automatically draw `ctrl` edges.
A possible variation of the approach could be to create a separate kind of events for indirect branches and to alter `aarch64deps.cat` accordingly -- simply to keep the old and the new events separated.
> [herd,aarch64] Adding ctrl to indirect branches

- herd/libdir/asl.cat
The fix is simple: the showing of event set `AArch64_DATA` was missing in file `asl.cat`.
Notice that "showing" sets and relations is a flexible mean to transmit them from ASL to AArch64.
Also notice that `asl.cat` already showed the identity _relation_ over the same event set as `AArch64_DATA`. We leave it, as it apparently does not harm.
> [herd,asl] Fix transmission of data ports from ASL to AArch64

- asllib/aslseq.ml
- asllib/dune
The tool aslseq is now installed as "aslref". That way, changes are minimal.
> [asl] New public name "aslref" for the aslseq tool.

- asllib/aslref.ml
- asllib/dune
- asllib/tests/asl.t/division.t
- asllib/tests/asl.t/run.t
- asllib/tests/bad-types.t
- asllib/tests/division.t
- asllib/tests/dune
`grep aslseq` does not return anything anymore.
> [fix] [asl] Rename aslseq into aslref

- herd/AArch64Sem.ml
- lib/label.ml
- lib/label.mli
- litmus/AArch64Compile_litmus.ml
- litmus/ARMCompile_litmus.ml
- litmus/LISACompile.ml
- litmus/MIPSCompile_litmus.ml
- litmus/PPCCompile_litmus.ml
- litmus/RISCVCompile_litmus.ml
- litmus/X86Compile_litmus.ml
- litmus/X86_64Compile_litmus.ml
- litmus/XXXCompile_litmus.mli
- litmus/compile.ml
- litmus/variant_litmus.ml
- litmus/variant_litmus.mli
This variant specifies "telechat" idiosyncrasies for litmus
At the moment the one idiosyncrasy implemented consists in assimilating "return" instructions to "jump to end of code". Thereby, litmus and herd have compatible behaviours.
> [litmus] Implement the "telechat" variant

- litmus/ASMLang.ml
- litmus/compile.ml
- litmus/libdir/_instance.c
- litmus/preSi.ml
This PR implements an optimization identified while reviewing PR#589. Also, it removes some code duplication in how litmus7 uses labels to find the location of an instruction, for the purposes of recording a fault and reading from/writing to an instruction.
> [litmus] Cleanup the code that handles labels for ifetch and faults

- herd/AArch64Sem.ml
- herd/eventsMonad.ml
- herd/monad.mli
- herd/tests/instructions/AArch64.self/S25.litmus
- herd/tests/instructions/AArch64.self/S25.litmus.expected
- herd/tests/instructions/AArch64.self/S26.litmus
- herd/tests/instructions/AArch64.self/S26.litmus.expected-failure
- herd/tests/instructions/AArch64.self/S27.litmus
- herd/tests/instructions/AArch64.self/S27.litmus.expected
In mode `-variant self` overwriting an instruction with an `ADR` instruction whose second argument is not pointing to a labeled instruction always resulted in an `assert false` failure. We improve in two directions:
+ The failure is delayed, so as it disappears if the corresponding execution candidate is discarded.
+ More specific error message.
> [herd] fix adr herd self

- gen/RISCVArch_gen.ml
- herd/RISCVArch_herd.ml
- herd/RISCVSem.ml
- herd/tests/instructions/RISCV/A001.litmus
- herd/tests/instructions/RISCV/A001.litmus.expected
- herd/tests/instructions/RISCV/A003.litmus
- herd/tests/instructions/RISCV/A003.litmus.expected
- herd/tests/instructions/RISCV/A004.litmus
- herd/tests/instructions/RISCV/A004.litmus.expected
- herd/tests/instructions/RISCV/A005.litmus
- herd/tests/instructions/RISCV/A005.litmus.expected
- herd/tests/instructions/RISCV/A006.litmus
- herd/tests/instructions/RISCV/A006.litmus.expected
- herd/tests/instructions/RISCV/A007.litmus
- herd/tests/instructions/RISCV/A007.litmus.expected-failure
- herd/tests/instructions/RISCV/A008.litmus
- herd/tests/instructions/RISCV/A008.litmus.expected
- herd/tests/instructions/RISCV/A009.litmus
- herd/tests/instructions/RISCV/A009.litmus.expected
- herd/tests/instructions/RISCV/A010.litmus
- herd/tests/instructions/RISCV/A010.litmus.expected
- herd/tests/instructions/RISCV/A05.litmus
- herd/tests/instructions/RISCV/A05.litmus.expected
- jingle/RISCVArch_jingle.ml
- lib/RISCVBase.ml
- lib/RISCVLexer.mll
- lib/RISCVParser.mly
- litmus/RISCVCompile_litmus.ml
This patch adds support for RISCV instructions I have encountered whilst testing compilers. Motivations are in the commits for each one.
Tests are included which all pass in herd, but I do not have RISCV hardware so I cannot test litmus - I am trying to figure out how to run tests on QEMU.
> [RISCV]: Add support for RISCV instructions

- herd/AArch64Sem.ml
- herd/ARMSem.ml
- herd/tests/instructions/AArch64/A253.litmus
- herd/tests/instructions/AArch64/A253.litmus.expected
- herd/tests/instructions/ARM/A024.litmus
- herd/tests/instructions/ARM/A024.litmus.expected
Fix ARM indirect branch to handle rets
Consider the following litmus test - emitted by GCC:
```
ARM A024
Variant=telechat
{ [P1_r0]=0;[x]=0;[y]=0;
%P0_x=x;%P0_y=y;
%P1_P1_r0=P1_r0;
%P1_x=x;%P1_y=y }
(*****************************************************************)
(* Compiler:                                                     *)
(* arm-linux-gnueabi-gcc-10 -c -g -O2 -march=armv7-a --std=c11 -fno-section-anchors*)
(*****************************************************************)
P0               |  P1                   ;
MOV R0,#2       |   LDR R2,[%P1_y]      ;
MOV R1,#1       |   CMP R2,#1           ;
DMB ISH         |   BEQ L0x5c           ;
STR R0,[%P0_x]  |  L0x48:               ;
STR R1,[%P0_y]  |   STR R2,[%P1_P1_r0]  ;
BX LR           |   BX LR               ;
|  L0x5c: …
```
> [AArch64,ARM]: Indirect Branches working for GCC tests.

- herd/debug_herd.ml
- herd/debug_herd.mli
- herd/eventsMonad.ml
- herd/herd.ml
- herd/valconstraint.ml
This switch disables failure delaying and some exceptions handlers. As a result, exception backtraces are more informative.
**NB**: Exception backtraces are obtained by setting `OCAMLRUNPARAM=b` before herd command.
> [herd] New debug switch `-debug exception`

- lib/ASLOp.ml
- lib/ASLScalar.ml
There were two problems, fixed as follows:
+ Slicing a symbolic constant with position [63] is now accepted and returns the bitvector `0`.
+ Converting a Z.t to an int is now performed by
- Computing remainder by 2^64,
- Followed by sign adjustement.
> [herd,asl] Fix addition of symbolic constant and offset

- herd/AArch64Sem.ml
- lib/symbValue.ml
- lib/value.mli
This PR aims to prevent creating of implicit TTD effects when building the semantics for loads and stores to instruction locations.
Consider the following litmus test:
```
AArch64 MP.FR+dmb.st+po
{
TTD(x)=(oa:PA(x),valid:0);
0:X0=NOP; 0:X1=P1:Lself; 0:X4=(oa:PA(x),valid:1); 0:X5=TTD(x);
1:X1=P1:Lself; 1:X3=x;
}
P0           | P1            ;
STR X4,[X5]  | Lself:        ;
DMB ST       |   B Lnext     ;
STR W0,[X1]  |   MOV W9,#1   ;
| Lnext:        ;
|   LDR W2,[X3] ;
exists 1:X9=1 /\ fault(P1,x)
```
Currently it cannot be run with `herd7`, because the VMSA semantics for  `STR W0,[X1]` will create effects that `machModelChecker.ml` will then incorrectly process. This PR aims to disable the VMSA semantics for such accesses, which will allow studying straightforward interactions between the …
> [herd,aarch64] ignore VMSA semantics for explicit accesses to labels

- herd/mem.ml
- herd/test_herd.ml
- herd/tests/instructions/AArch64/AK004.litmus
- herd/tests/instructions/AArch64/AK004.litmus.expected-failure
- herd/tests/instructions/AArch64/AK005.litmus
- herd/tests/instructions/AArch64/AK005.litmus.expected-failure
This PR implements two very simple safeguards, both ifetch-specific in nature.
Firstly, whenever there is a label in the initialization list, raise a user error if it is not actually present in the code of the litmus test. This already is marked as an error if there is a load or a store with such an undefined location, but the following test, for instance, is still possible:
```
AArch64 AK004
{
0:X5=P0:Lself00;
}
P0         ;
MOV X4,X5  ;
locations [0:X4]
```
To remove a possibility of confusing errors in litmus tests, this PR inserts a simple check into `test_herd.ml` to ensure all labels in the precondition are actually defined.
Secondly, whenever there is a store into a label, raise a user error and inform the user that they may want to use `-variant ifetch`.
```
AArch64 AK005
{ …
```
> [herd] Minor user-interface suggestions for herd

- herd/AArch64Sem.ml
- herd/tests/instructions/AArch64.MTE/B004.litmus
- herd/tests/instructions/AArch64.MTE/B004.litmus.expected
- lib/AArch64Base.ml
This PR adds support for register `TFSR_ELx` for async MTE. When an async fault happens due to a tag mismatch we set the 0 bit of register `TFSR_ELx`. Note that we define `TFSR_ELx` which is a generic name for the registers `TFSR_EL01` `TFSR_EL1` etc. This is intentional and in order to avoid being specific about the exception level that the test runs in. For the test:
```
AArch64 B004
Variant=async
{
0:X1=x:red
}
P0          ;
MOV W0,#1   ;
STR W0,[X1] ;
forall([x]=1 /\ 0:TFSR_ELx=1)
```
The semantics are shown in this graph:
> [herd] Add support for AArch64 TFSR_ELx in async MTE

- herd/AArch64ASLSem.ml
- herd/AArch64Arch_herd.ml
- herd/AArch64Sem.ml
- herd/ASLSem.ml
- herd/tests/instructions/AArch64/L091.litmus
- herd/tests/instructions/AArch64/L091.litmus.expected
- herd/tests/instructions/AArch64/L092.litmus
- herd/tests/instructions/AArch64/L092.litmus.expected
- jingle/AArch64Arch_jingle.ml
- lib/AArch64Base.ml
- lib/AArch64Lexer.mll
- lib/AArch64Parser.mly
- lib/ASLScalar.ml
- lib/capabilityScalar.ml
- lib/int128.ml
- lib/int128Scalar.ml
- lib/op.ml
- lib/op.mli
- lib/scalar.mli
- lib/symbValue.ml
- lib/uint128Scalar.ml
- litmus/AArch64Compile_litmus.ml
Implementation of the AArch64 `ABS`  instruction (absolute value). We also seize the opportunity to implement the `NEG` and `NEGS` aliases.
The following litmus test illustrates the new (pseudo-)instructions:
```
AArch64 ABS
{
0:X1=6;
}
P0        ;
NEG W2,W1  ;
ABS W3,W2  ;
forall 0:X2=-6 /\ 0:X3=6
```
> [all, aarch64] ABS instruction

- Makefile
- herd/AArch64Sem.ml
- herd/ASLSem.ml
- herd/event.ml
- herd/eventsMonad.ml
- herd/libdir/asl.cat
- herd/machModelChecker.ml
- herd/mem.ml
- herd/monad.mli
- herd/semExtra.ml
- herd/slrc11.ml
- lib/InnerTransRel.ml
- lib/InnerTransRel.mli
- lib/innerRel.ml
- lib/innerRel.mli
The main goal of this pr can be summarized by the following test:
```
ASL test-po
{}
func main () => integer begin
let y = 0;
let x = y + y; // Here
return 0;
end
```
We want the two reads to `y` to not be related by `po`. This is not possible with herd as of today, because the program order is considered a total order on the effects of a thread.
This PR introduce the possibilities for an architecture to use a partial program order.
This is done by adding a field inside the `event_structure` graph, and adding new combinators that edit specially this fields.
That results in the following graph being produced for the above test:
We can see that there is no `partial_po` arrow between _b_ and _c_ when there is a `po` one.
> [herd, asl] Add a partial po field to account for ASL

- asllib/builder.ml
- asllib/builder.mli
- herd/ASLSem.ml
Function defined by ASL standard library take precedence, given file loading  order this means that definitions that would clash with those of the ASL standard library have to be removed at some point. A (partial) static test is replaced by a dynamic one.
Followup to PR #715.
> [herd,asl] Avoid name clashes between stdlib.asl and other libraries

- herd/AArch64ASLSem.ml
- herd/ASLSem.ml
- herd/libdir/asl.cat
- herd/memUtils.ml
- lib/InnerTransRel.ml
- lib/InnerTransRel.mli
- lib/innerRel.ml
- lib/innerRel.mli
- lib/interpreter.ml
ASL partial po was not propagated to AArch64+ASL, which caused iico_order to be empty.
This fixes the SWP AArch64.ASL regression tests.
> [asl] (fix) correctly propagate ASL po

- Makefile
- internal/dune
- internal/herd_promote.ml
- internal/herd_regression_test.ml
- internal/herd_test.ml
- internal/lib/command.ml
- internal/lib/testHerd.ml
- internal/lib/testHerd.mli
- tools/mapply.ml
The internal command now accepts and completely implements the command line option `-j <n>`, resulting in parallel execution limited to at most `<n>`  concurrent agents.
> [internal] Parallel `herd_regression_test.exe` command.

- herd/AArch64ASLSem.ml
- herd/AArch64Arch_herd.ml
- herd/AArch64Sem.ml
- herd/tests/instructions/AArch64/L094.litmus
- herd/tests/instructions/AArch64/L094.litmus.expected
- herd/tests/instructions/AArch64/L095.litmus
- herd/tests/instructions/AArch64/L095.litmus.expected
- herd/tests/instructions/AArch64/L096.litmus
- herd/tests/instructions/AArch64/L096.litmus.expected
- herd/tests/instructions/AArch64/L097.litmus
- herd/tests/instructions/AArch64/L097.litmus.expected
- jingle/AArch64Arch_jingle.ml
- lib/AArch64Base.ml
- lib/AArch64Lexer.mll
- lib/AArch64Parser.mly
- lib/op.ml
- lib/op.mli
- lib/rbit.ml
- lib/rbit.mli
- lib/symbValue.ml
- litmus/AArch64Compile_litmus.ml
Implement the REV instruction, as well as its variants REV16, REV32, REV64. LItmus test example:
```
AArch64 L094
{
uint32_t 0:X1=0x87654321;
uint32_t 0:X2;
uint64_t 0:X3=0xfedcba87654321;
uint64_t 0:X4;
}
P0       ;
REV W2,W1 ;
REV X4,X3 ;
forall 0:X2=0x21436587 /\ 0:X4=0x21436587badcfe00
```
> [all] Implement AArch64 "reverse bytes" instructions

- herd/AArch64ASLSem.ml
- herd/AArch64Arch_herd.ml
- herd/AArch64Sem.ml
- herd/tests/instructions/AArch64/L098.litmus
- herd/tests/instructions/AArch64/L098.litmus.expected
- jingle/AArch64Arch_jingle.ml
- lib/AArch64Base.ml
- lib/AArch64Lexer.mll
- lib/AArch64Parser.mly
- litmus/AArch64Compile_litmus.ml
Those instructions multiply two 32bit quantities resulting in a 64bit quantity. Additionally, the multiplication can be signed or unsigned. Moreover the multiplication result is added to or subtracted from another 64bit quantity.
For instance: considering signed multiplication and addition:
```
AArch64 MUL
{
int64_t 0:X1=1;
0:X2=2;
0:X3=3;
int64_t 0:X4;
int64_t 0:X5;
}
P0                ;
SMADDL X4,W3,W2,X1 ;
SMULL X5,W3,W2     ;
forall 0:X4=7 /\ 0:X5=6
```
We have 3\*2+1 = 7 and 3\*2+0 = 6. The alias `SMULL` stands for `SADDL` with the last register being the zero register `XZR`.
> [all] Implementing AArch64 wide multiplication instructions.

- herd/AArch64ASLSem.ml
- herd/AArch64Arch_herd.ml
- herd/AArch64Sem.ml
- herd/tests/instructions/AArch64/L099.litmus
- herd/tests/instructions/AArch64/L099.litmus.expected
- herd/tests/instructions/AArch64/L100.litmus
- herd/tests/instructions/AArch64/L100.litmus.expected
- herd/tests/instructions/AArch64/L101.litmus
- herd/tests/instructions/AArch64/L101.litmus.expected
- herd/tests/instructions/AArch64/L102.litmus
- herd/tests/instructions/AArch64/L102.litmus.expected
- jingle/AArch64Arch_jingle.ml
- lib/AArch64Base.ml
- lib/AArch64Lexer.mll
- lib/AArch64Parser.mly
- litmus/AArch64Compile_litmus.ml
This instruction loads a 32bit quantity, sign-extends it to a 64bit quantity, and stores it in a X register.
Example:
```
AArch64 LDRSW
{
int x=-7;
0:X0=x;
int64_t 0:X1;
}
P0          ;
LDRSW X1,[X0] ;
forall 0:X1=-7
```
Sign has been carried from the memory cell to the register.
> [all] Implement the AArch64 LDRSW instruction

- jingle/arch.ml
- lib/archDump.mli
- lib/simpleDumper.ml
- tools/dumper.ml
- tools/dumperMiscParser.ml
- tools/mprog.ml
The tools accepts the new command line option `-compat <bool>`. The new behaviour can be useful to find the reason why some hash has changed.
> [tools] Enhance mprog7 functionality,

- gen/config.ml
- gen/diy.ml
- gen/diycross.ml
- gen/diyone.ml
- gen/top_gen.ml
The new command line option `-metadata false` command _not_ to output the usual metadata or info fields in generated tests. The default, `-metadata true` corresponds to previous behaviour.
> [gen] New setting to control metadata output

- asllib/Interpreter.ml
- asllib/doc/ASLSemanticsReference.tex
- asllib/doc/ASLTypingReference.tex
- asllib/doc/Makefile
- asllib/tests/ASLSemanticsReference.t/SemanticsRule.ESlice.asl
- asllib/types.ml
This PR implements the following:
`asllib/types.ml` code
code
> [asldoc] New or fixed transliterations

- litmus/libdir/_hash.c
- litmus/libdir/_instance.c
- litmus/libdir/_main.c
- litmus/preSi.ml
- litmus/skelUtil.ml
Previous behaviour was exiting, which is not appropriate when the same executable performs several tests (mode `driver C`). New behaviour is going on and flagging a warning that the collection of outcomes is not complete.
> [litmus] Change behaviour for full hash tables

- litmus/dumpParams.ml
- litmus/libdir/_aarch64/cache.c
- litmus/libdir/aarch64.cfg
- litmus/litmus.ml
- litmus/preSi.ml
- litmus/skel.ml
- litmus/topology.ml
Affinity is no longer enabled by default for the "presi" mode.
However, affinity behavior  significantly departs  from standard  mode. In "presi" mode, system threads are first started started, which later are allocated changing test threads according to declared topology.
Affinity concerns system threads, which are mapped onto logical cores by following the `incr1` policy, whatever affinity policy is specified. Nevertheless, system thread allocation to logical cores can be changed by using the `-procs <ints>` setting.
As a motivation for this change, mode "presi" is now available on MacOS (with affinity disabled) and the mode can be run with no affinity control or with custom logical core mappings on platforms that provide affinity control.
The also include a few unrelated changes …
> [litmus] Explicit affinity control for `-mode presi`

- asllib/Lexer.mll
- asllib/tests/ASLTypingReference.t/TypingRule.CheckBinOp.asl
- asllib/tests/ASLTypingReference.t/run.t
Added a new keyword "XOR", which is mapped to the token EOR.
Added a new test.
Test plan: 
---------
asllib/tests/ASLTypingReference.t$ aslref --no-exec --type-check-strict TypingRule.CheckBinOp.asl
$ dune runtest asllib
$ make test-aarch64-asl
$ make test
> Added new XOR token to reflect change in LRM

- litmus/ASMLang.ml
- litmus/KSkel.ml
- litmus/preSi.ml
- litmus/skel.ml
- litmus/skelUtil.ml
1. Remove stable registers from the  list of clobbers in inline asssembly. Otherwise gcc protests.
2. Silently switch the `ascall` setting to true when computing code prelude size at runtime is needed for any reason.
Example of a test that triggered the two errors, while compiled as `litmus7 -mach vougeot -o /tmp/A.tar  BLR.litmus`:
```
AArch64 BLR-BL
Stable=X30
{
}
P0          ;
MOV W0,#1    ;
ADR X4,first ;
BLR X4       ;
BL first     ;
B end        ;
first:        ;
MOV X29,X30  ;
BL snd       ;
RET X29      ;
snd:          ;
ADD W0,W0,W0 ;
RET          ;
end:          ;
forall 0:X0=4 
```
> [litmus] Fix two small bugs in litmus

- asllib/Typing.ml
- asllib/doc/ASLRefProgress.tex
- asllib/doc/ASLTypingReference.tex
- asllib/instrumentation.ml
* Two new chapters for annotating global declarations and entire ASL specifications.
* Introduced shorthand notation for environment updates.
* Fixed definition of domains, which in particularly handles under-constrained integers.
Test plan:
$ make test
$ dune runtest asllib
> Annotating global declarations and entire specifications

- gen/AArch64Arch_gen.ml
- gen/AArch64Compile_gen.ml
- gen/ARMArch_gen.ml
- gen/BellArch_gen.ml
- gen/CArch_gen.ml
- gen/MIPSArch_gen.ml
- gen/PPCArch_gen.ml
- gen/RISCVArch_gen.ml
- gen/X86Arch_gen.ml
- gen/X86_64Arch_gen.ml
- gen/archExtra_gen.ml
- gen/archLoc.mli
- gen/atom.mli
- gen/code.ml
- gen/code.mli
- gen/cycle.ml
- gen/edge.ml
- gen/final.ml
- gen/genUtils.ml
- gen/machAtom.ml
- gen/namer.ml
- gen/normaliser.ml
- gen/topUtils.ml
- gen/top_gen.ml
- lib/AArch64Base.ml
- litmus/lexAffinity.mll
This PR implements a new syntax for generating Ifetch tests, using a new annotation. The I annotation is used to represent explicit memory events to instruction locations (i.e. LDR and STR of an instruction stored at a location identified by a label). This PR also introduces the possibility of generating explicit reads of an instruction. With this new implementation, Ifetch sequences are generated by using the plain annotation with a read to a Code location.
example tests:
```
diyone7 -arch AArch64 -variant self "RfeII Pod** Rfe Pod** FrePI"
AArch64 A
"RfeII PodRWIP Rfe PodRR FrePI"
Generator=diyone7 (version 7.56+03)
Com=Rf Rf Fr
Orig=RfeII PodRWIP Rfe PodRR FrePI
{
0:X0=instr:"NOP"; 0:X1=P2:Lself00;
1:X0=P2:Lself00; 1:X3=x;
2:X0=x;
}
P0          | P1          | P2          ;
STR W0,[X1] …
```
> [gen] implementation of Ifetch annotation

- gen/AArch64Arch_gen.ml
- gen/AArch64Compile_gen.ml
- gen/ARMCompile_gen.ml
- gen/BellCompile.ml
- gen/MIPSCompile_gen.ml
- gen/PPCCompile_gen.ml
- gen/RISCVCompile_gen.ml
- gen/X86Compile_gen.ml
- gen/X86_64Compile_gen.ml
- gen/XXXCompile_gen.mli
- gen/alt.ml
- gen/cycle.ml
- gen/edge.ml
- gen/top_gen.ml
- lib/AArch64Base.ml
This pull request implements the ability to generate DC CVAU and IC IVAU instructions as a fence instruction. This allows the user to implement these instructions with more fine-grain control into litmus tests.
This PR also implements the ability for dependencies to be generated before Insert relaxations.
The relaxations for DC CVAU and IC IVAU are:
```
DC.CVAU<n/p>
IC.IVAU<n/p>
```
where `n` and `p` allow the user to choose whether DC/IC act on the `p`revious location or the `n`ext location
examples that couldn't be generated previously:
```
diyone7 -moreedges true -arch AArch64 -variant self "PodWW DC.CVAUp DMB.ISH Rfe PodRR DSB.ISH IC.IVAUn DSB.ISH ISB Ifre"
AArch64 A
"PodWW DC.CVAUp DMB.ISH Rfe PodRR DSB.ISH IC.IVAUn DSB.ISH ISB Ifre"
Generator=diyone7 (version 7.56+03)
Com=Rf Ifr …
```
> [gen]DC CVAU and IC IVAU relaxations

- asllib/StaticInterpreter.ml
- asllib/Typing.ml
- asllib/tests/asl.t/named-types-in-slices.asl
- asllib/tests/asl.t/run.t
- asllib/types.ml
A bug reported by @maranget.
The following test did not type-check:
```
type pagros of integer{1,2,4,8,16};
var ones = Ones(64);
func f(sz:pagros) => bits(sz)
begin
return ones[sz-1:0];
end
begin
let x = f(8);
DEBUG(x);
return 0;
end
```
The cause was the use of named types inside slices, which were not correctly
handled. This has been fixed.
This PR is not a systematic fix nor a complete survey of correct handling of
named types.
The reported test has been added to the regression test set, and is now
accepted by the type-checker.
> [asl][fix] Use anonymous types before static analysis

- herd-www/README.md
- herd-www/dune
As long as ASL is not used, this dependency should be useless.
However, some zarith initialisation function is apparently called at startup, which enforces this new dependency.
> [www] Add dependency on zarith_stubs_js

- asllib/Lexer.mll
- asllib/tests/lexer.t
This depends/conflicts with PR #774, or at least with the patch I have submitted in #783. For ease of conflict resolution, I have cherry-picked my patch onto this PR.
This PR implements C-Style comments, without nesting, as required.
> [Asl] Support C-style comments

- gen/AArch64Arch_gen.ml
- gen/AArch64Compile_gen.ml
- herd/AArch64Arch_herd.ml
- herd/AArch64Sem.ml
- herd/tests/instructions/AArch64.neon/V65.litmus
- herd/tests/instructions/AArch64.neon/V65.litmus.expected
- herd/tests/instructions/AArch64.neon/V66.litmus
- herd/tests/instructions/AArch64.neon/V66.litmus.expected
- jingle/AArch64Arch_jingle.ml
- lib/AArch64Base.ml
- lib/AArch64Lexer.mll
- lib/AArch64Parser.mly
- litmus/AArch64Compile_litmus.ml
Hi All,
I've been adding capability to generate Neon load/store pair instruction and Neon load/store scalar (including ordered variants `LDAPUR` and `STLUR`). Generator now accepts new psudo relaxations:
- `NePa` for Neon `LDP`/`STP`
- `NePaN` for Neon `LDNP`/`STNP`
- `NeP` for Neon `LDUR`/`STUR` instructions
- `NeQ` and `NeL` for Neon `LDAPUR` and `STLUR` correspondingly
Additionally, identified some places for improvements and added support for Neon `LDAP1` and `STL1` in `herd` and `litmus`. 
Please, note that new Neon ordered instructions might not be supported by compilers yet.
> Generate Neon scalars

- litmus/preSi.ml
- litmus/variant_litmus.ml
This change makes two small fixes which are necessary to run:
* Tests that specify the fault handling variant as part of the test, for example:
$> litmus7 -a 4 -mach kvm-aarch64 -o ~/kvm-unit-tests/t catalogue/aarch64-faults/tests/3faults.litmus
* Tests that use the -variant self and do not use any memory locations, for example:
$> litmus7 -a 4 -mach kvm-aarch64 -o ~/kvm-unit-tests/t catalogue/aarch64-ifetch/tests/UDF+2FH.litmus
> [litmus] Correctly handle MTE precision and fix -variant ifetch

- gen/AArch64Compile_gen.ml
- herd/AArch64Arch_herd.ml
- herd/AArch64Sem.ml
- herd/tests/instructions/AArch64/A19.litmus.expected
- jingle/AArch64Arch_jingle.ml
- lib/AArch64Base.ml
- lib/AArch64Parser.mly
- litmus/AArch64Compile_litmus.ml
Currently Neon load/store is split in two instructions: one for handling immediate/register offset and another for handling post-index variant. The similar applies to Neon load/store pair. Note, missing support for pre-index variant for Neon load/store.
Let's refactor those instructions to take advantage of existing infrastructure for handling addressing modes. That removes need for special instruction for post-index variant and as a bonus naturally brings support for pre-index variant for Neon load/store.
> [all]: Rework Neon load/store and load/store pair

- asllib/Interpreter.ml
- asllib/Typing.ml
- herd/AArch64ASLSem.ml
- herd/ASLSem.ml
- herd/libdir/asl-pseudocode/patches.asl
Check for existing getter (resp. setter) when typing field access (resp .update).
This feature is useful to view subfields of bitfields as distinct objects. For instance, the fields `X` and `Y` below apparently belong to a single bitfield `STATE`, as we write `STATE.X` and `STATE.Y`. However they in fact correspond to different bitfields `_X` and `_STATE`.
```
type State of bits(2) {
[0] X,
[1] Y,
};
var _X:State;
var _STATE:State;
getter STATE[] => State
begin
return _STATE;
end
setter STATE[] = v : State
begin
_STATE = v;
end
getter STATE[n:integer] => bits(1)
begin
if n <= 0 then
return _X[n];
else
return _STATE[n];
end
end
setter STATE[n:integer] = v : bits(1)
begin
if n <= 0 then
_X[n] = v;
else
_STATE[n] = v;
end
end
begin
STATE.X = '1';
STATE.Y = '1'; …
```
> [asl]  get and set fields to call

- asllib/carpenter/test/dune
Add appropriate (?) `if_enabled` clause in `dune` file.
> [test] Do not test carpenter when dependencies are not available

- herd/AArch64Sem.ml
- herd/tests/instructions/AArch64.MTE/B009.litmus
- herd/tests/instructions/AArch64.MTE/B009.litmus.expected
- herd/tests/instructions/AArch64.MTE/B010.litmus
- herd/tests/instructions/AArch64.MTE/B010.litmus.expected
- herd/tests/instructions/AArch64.MTE/B011.litmus
- herd/tests/instructions/AArch64.MTE/B011.litmus.expected
- herd/tests/instructions/AArch64.MTE/B012.litmus
- herd/tests/instructions/AArch64.MTE/B012.litmus.expected
- herd/tests/instructions/AArch64.MTE/B013.litmus
- herd/tests/instructions/AArch64.MTE/B013.litmus.expected
- lib/machSize.ml
- lib/machSize.mli
The address used for these instructions is calculated from the base register and an immediate signed offset scaled by the Tag granule.
> [herd]: Fix address generation for STG, LDG and friends

- herd/AArch64Arch_herd.ml
- herd/AArch64Sem.ml
- herd/ARMArch_herd.ml
- herd/ASLAction.ml
- herd/BellAction.ml
- herd/CAction.ml
- herd/JavaAction.ml
- herd/action.mli
- herd/event.ml
- herd/explicit.ml
- herd/explicit.mli
- herd/machAction.ml
- herd/mem.ml
- herd/tests/instructions/AArch64.self/S28.litmus
- herd/tests/instructions/AArch64.self/S28.litmus.expected
- herd/tests/instructions/AArch64.self/S29.litmus
- herd/tests/instructions/AArch64.self/S29.litmus.expected
- herd/tests/instructions/AArch64/AK005.litmus.expected-failure
- lib/stateParser.mly
Matching of writes with instruction loads was too limited as stores with non-determined addresses were forgotten. This PR fixes this, also seizing the opportunity to fix a two minor glitches:
1. Characterise the instruction fetch loads with a specific annotation.
2. Extend parsing of label constants
> [herd] Better rf matching for instruction fetch

- herd/AArch64Sem.ml
- herd/branch.ml
- herd/mem.ml
- herd/tests/instructions/AArch64.kvm/A018.litmus
- herd/tests/instructions/AArch64.kvm/A018.litmus.expected
- herd/tests/instructions/AArch64.self/A017.litmus
- herd/tests/instructions/AArch64.self/A017.litmus.expected
- herd/tests/instructions/AArch64/A257.litmus
- herd/tests/instructions/AArch64/A257.litmus.expected
In sequences where the label is know, rather than setting the LR with an internal address we use the label. This means that in certain cases (-variant=ifetch) we can use it to address the instruction in that label.
> [herd] Write a label to LR (X30) when it is possible

- herd/tests/instructions/AArch64.ASL/STCLR00.litmus
- herd/tests/instructions/AArch64.ASL/STCLR00.litmus.expected
- lib/AArch64Parser.mly
> [all, aarch64] Parse ST<OP> on X registers

- Makefile
The Makefile used to offer an option to run all tests. As we added more tests, the overhead for running all tests becomes non-trivial. More notably, the vmsa-test and ets2-test targets include more litmus tests than any other. In addition, the fact that make test is invoked in the precommit hook makes it crucial that make test terminates as quickly as possible. This commit adds another target test-all which is inclusive of all tests.
> [Makefile] Add a test-all target

- herd/AArch64Sem.ml
- herd/Pretty.ml
- herd/eventsMonad.ml
- herd/mem.ml
- herd/partition.ml
- herd/partition.mli
- herd/tests/instructions/C/C13.litmus
- herd/tests/instructions/C/C13.litmus.expected
- herd/valconstraint.ml
- herd/variant.ml
- herd/variant.mli
- lib/innerRel.ml
- lib/innerRel.mli
- lib/misc.ml
- lib/misc.mli
- lib/symbValue.ml
- lib/value.mli
The new solver substitutes variables in equations following dependencies. It should be functionally equivalent to the previous solver.
his PR introduces an enhanced equation solver (step 2. below), which should run slightly  faster than the previous one and also follows equation structure more closely.
Equations produced by "semantic" modules are solved by a two step process:
1. Identify class of equivalent variables.  Variables in a class are replaced by a class representative.
As a result, sets of mutually dependent "variable = variable" equations are discarded during that step. Nevertheless the representative variable may be present in other, dependent, equations and in the final execution candidate.
2. Solve equations by substitution and computation. Previous step 2. proceeds by …
> [herd] New solver

- Makefile
Namely, releases of herdtools do not include the catalogue. As an untimely consequence `make test` was failing.
> [test] Check catalogue existence before running catalogue tests

- lib/CParser.mly
Add the remaining atomic instructions used by the linux kernel.
Tested by applying following diff to the linux-kernel.def in the kernel:
diff --git a/tools/memory-model/linux-kernel.def b/tools/memory-model/linux-kernel.def
index 88a39601f525..ae07e9acdff1 100644
--- a/tools/memory-model/linux-kernel.def
+++ b/tools/memory-model/linux-kernel.def
@@ -65,6 +65,9 @@ atomic_set_release(X,V) { smp_store_release(X,V); }
atomic_add(V,X) { __atomic_op(X,+,V); }
atomic_sub(V,X) { __atomic_op(X,-,V); }
+atomic_and(V,X) { __atomic_op(X,&,V); }
+atomic_or(V,X)  { __atomic_op(X,|,V); }
+atomic_xor(V,X) { __atomic_op(X,^,V); }
atomic_inc(X)   { __atomic_op(X,+,1); }
atomic_dec(X)   { __atomic_op(X,-,1); }
and created basic litmus tests of the kind:
C atomics
{
atomic_t t = ATOMIC_INIT(15);
} …
> herd: Linux: atomic_and, atomic_or, atomic_xor instructions.

- herd/tests/instructions/AArch64.sve/V22.litmus
- herd/tests/instructions/AArch64.sve/V22.litmus.expected
This test creates and uses an 0/1 alternating predicate for word vectors.
> [herd] One additional SVE test

- lib/CLexer.mll
- lib/CParser.mly
Implement `atomic_andnot()` for the linux kernel. `&~` has been chosen to represent this atomic operation and added to the C lexer. AndNot2 is already implemented so we can use it directly.
Testing
-------
`+atomic_andnot(V,X) { __atomic_op(X,&~,V); }`
was added to the linux-kernel.def in the kernel tree and the following litmus test was run:
```
C andnot
{ atomic_t u = ATOMIC_INIT(7)}
P0(atomic_t *u)
{
atomic_andnot(3, u);
smp_mb();
r1 = READ_ONCE(*u);
}
exists (0:r1=4)
```
This is doing:
```
u = 7;
u &= ~3;
```
which would clear the bit number 0 and 1 in 7 and that would mean the result should be 4:
```
Test andnot Allowed
States 1
0:r1=4;
Ok
Witnesses
Positive: 1 Negative: 0
Condition exists (0:r1=4)
Observation andnot Always 1 0
```
> herd: Linux: add atomic_andnot()

- asllib/Typing.ml
- asllib/doc/ASLFormal.tex
- asllib/doc/ASLSemanticsReference.tex
- asllib/doc/ASLSyntaxReference.tex
- asllib/doc/ASLTypingReference.tex
- asllib/doc/ASLmacros.tex
- asllib/error.ml
- asllib/instrumentation.ml
Work to get the ASL Typing Reference ready for another round of reviews on May 13th.
> [asl][typing] Typing Reference Pre-Beta step 3

- catalogue/aarch64-mixed/README.md
- catalogue/aarch64-mixed/tests/CoRW2+posq0q0+q0.litmus
- catalogue/aarch64-mixed/tests/CoRW2+posw0w0+w0.litmus
- catalogue/aarch64-mixed/tests/LB+dmb.sy+data-wsi-wsi+MIXED.litmus
- catalogue/aarch64-mixed/tests/MP+QAmo+AcqAmo.litmus
- catalogue/aarch64-mixed/tests/MP+dmb.syw0w4+dataw4w4-rfiw4q0.litmus
- catalogue/aarch64-mixed/tests/MP+popl.w0-posl.w0q0+poa.w4p.litmus
litmus7 and the compiler used for the source code produced by litmus7 emits warnings for some of the tests in aarch64-mixed catalogue.
In most cases, the type of the register is declared incorrectly (for example, uint64_t instead of uint32_t). In other cases, we need to trancate a register from 64bit to 32bit.
This commit fix these warnings. There should be no change to the semantics of any of these tests and for this reason their hash is changed to match that of the previous version of the tests.
There is one warning which is benign:
Warning: File "./tests/LB+dmb.sy+data-wsi-wsi+MIXED.litmus" Register x0 has different types: <int64_t> and <int>
In this case, litmus7 is being a little pedantic. gcc seems to be fine with its code.
> [catalogue] Fix litmus7 warnings for aarch64-mixed

- asllib/Interpreter.ml
- herd/ASLSem.ml
- herd/tests/instructions/ASL-pseudo-arch/frozen-tuple-arg.litmus
- herd/tests/instructions/ASL-pseudo-arch/frozen-tuple-arg.litmus.expected
- herd/tests/instructions/ASL-pseudo-arch/return-tuple.litmus
- herd/tests/instructions/ASL-pseudo-arch/return-tuple.litmus.expected
Fix various problems related to tuple bindings.
Two tests that illustrate the fixed problems are also added.
- Cyclic program order:
```
ASL return-tuple
{
}
func f() => (integer, integer)
begin
return (1,2);
end
begin
let (a,b) = f();
let c = a+b;
return 0;
end
forall 0:main.0.c=3
```
Before the fix, this test yielded no execution at all, because if the cyclic `po` introduced while evaluating `let (a,b) = f();`.
- Creating tuples with non-resolved arguments:
```
ASL frozen-tuple-arg
{
x=15;
0:X0=x;
}
begin
let x = read_register(0);  
let (a,b) = (1,UInt(read_memory(x,32)));
let c = a+b;
return 0;
end
forall 0:main.0.c=16
```
Before the fix, evaluation of `let (a,b) = (1,UInt(read_memory(x,32)));` was failing because the `read_memory` …
> [asl] Fix let binding of tuples

- herdtools7.opam
Some convenient functions such as `of_int64_unsigned` are introduced by this recent version.
> [build] Specify 1.13 as the minimal version for zarith

- gen/config.ml
Prior to 17eda0c637554cd709f28107119c93628b711ee0 -relaxlist was an alias for -safe. Restore this behaviour to avoid breaking existing .conf files like gen/libdir/forbidden.conf.
> [gen] Restore default behaviour where -relaxlist is an alias for -safe

- litmus/libdir/aarch64-qemu.cfg
- litmus/libdir/armv8.3-qemu.cfg
Handy, when no armv8  machine at hand.
> [litmus] Configuration files for armv8 qemu targets

- herd/AArch64Sem.ml
- herd/tests/instructions/AArch64.sve/V30.litmus
- herd/tests/instructions/AArch64.sve/V30.litmus.expected
Fix a small bug found by testing the implemented scatter store instruction.
> [herd] Demote scalar offsets before sign extending them.

- litmus/AArch64Arch_litmus.ml
Consider following example litmus test
```
AArch64 T
stable=x12
{
0:X0=x;
}
P0              ;
MOV X12,XZR     ;
LDR X1,[X0,X12] ;
```
which `litmus7` transforms into
```
register int64_t stable_x12 asm("x12");
asm __volatile__ (
"\n"
"#START _litmus_P0\n"
"#_litmus_P0_0\n\t"
"mov %[x12],xzr\n"
"#_litmus_P0_1\n\t"
"ldr %[x1],[%[x0],%[x12]]\n"
"#END _litmus_P0\n"
:[x1] "=&r" (trashed_x1),[x12] "=r" (stable_x12)
:[x0] "r" (&_a->x[_i])
:"cc","memory"
);
```
When build with with GCC 14.1.0 result code seems reuse `x12` as base register
```
cc:   aa1f03ec        mov     x12, xzr
d0:   f86c6980        ldr     x0, [x12, x12]
```
The way to fix that is to use the ‘&’ constraint modifier on stable reg as well so output operands not overlap an input.
> [litmus]: Use the ‘&’ constraint modifier in aarch64's reg_class_stable

- herd/AArch64ASLSem.ml
- herd/BellMem.ml
- herd/CMem.ml
- herd/MemCat.ml
- herd/MemWithCav12.ml
- herd/getModel.ml
- herd/herd.ml
- herd/machModelChecker.ml
- herd/model.ml
- herd/model.mli
Simply one more debug message at cat interpretation start, commanded by option `-debug model`.
> [herd] Add debug message at cat model interpretation start

- .github/workflows/check-format.yml
- .github/workflows/make-test.yml
Following [this](https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre), this PR cancels previous workflow on subsequent pushes to the PR.
> [ci] Cancel in progress CI workflows when pushing a new one

- litmus/AArch64Arch_litmus.ml
Constraint modifier we currently use for predicate register is
`Upa` - Any of the SVE predicate registers (P0 to P15)
That made a trick so far, yet with GCC 14.1.0 it seems that register allocation happens top to bottom, yet most of SVE instructions we support allow predicate register only in a range P0 to P7. So build fails.
Let's work it around by using `Upl` constraint modifier for predicate register:
`Upl` - One of the low eight SVE predicate registers (P0 to P7)
> [litmus]: Use 'Upl' constraint modifier for predicate register

- litmus/libdir/_instance.c
- litmus/libdir/_main.c
- litmus/libdir/_presi.c
- litmus/libdir/_presi.h
- litmus/libdir/_utils.c
- litmus/preSi.ml
This change adds support for the speedcheck parameter for -mode presi. This was already supported in -mode std. The user can provide the parameter "+sc" which will force the exit to as soon as the post-condition is observed.
> [litmus] Add support for speedcheck parameter for -mode presi

- herd/ASLSem.ml
- herd/tests/instructions/ASL-pseudo-arch/non-determinsitic.litmus
- herd/tests/instructions/ASL-pseudo-arch/non-determinsitic.litmus.expected
Before, the evaluation of the `somebool` primitive by "ASLSem" was yielding no candidate, because of some unsolved equations. Now, we have two candidates, as expected.
As an example the following litmus test now yields two candidates:
```
ASL non-deterministic
{ }
// Non deterministically returns 1 or 2
func g() => integer
begin
let b = SomeBoolean();
if b then
return 1;
end
return 2;
end
begin
let z = g();
return 0;
end
locations [0:main.0.z;]
```
> [asl] Fix the non-determinstic ASL primitive `somebool`

- asllib/doc/ASLTypingReference.tex
- asllib/tests/lca.t
- asllib/types.ml
Removed the requirement that elements of types must type-satisfy each other.
This means that the type of `if cond then (0, 63) else (0, 31)` is `(integer{0}, integer{63,31})`.
> [asl] Fix definition of Lowest Common Ancestor on tuples.

- asllib/StaticInterpreter.ml
- asllib/StaticInterpreter.mli
- asllib/Typing.ml
- asllib/instrumentation.ml
This is in order to avoid shadowing definitions from Instrumentation and to be able to mark code in StaticInterpreter.ml for typing rules. 
Marked static_eval with the new TypingRule.StaticEval
> [asl] Added StaticInterpreter.mli

- asllib/Interpreter.ml
- herd/tests/instructions/ASL-pseudo-arch/throw-assign.litmus
- herd/tests/instructions/ASL-pseudo-arch/throw-assign.litmus.expected
Monad argument was discarded bin the monad combinator `bind_env` when an exception was raised.
As for PR #902 and #899, any monad argument to combinators has to be used linearly. Here is a test that illustrates the bug:
```
ASL throw-assign
{}
var z = 0;
type Coucou of exception;
func f() => integer
begin
z = 2;
throw Coucou {};
end
begin
try
z = f();
catch
when Coucou => return 0;
end
end
forall 0:z=2
```
Before the fix the events related to the global assignment `z = 2` were discarded and the final value of `z` was zero.
> [herd,asl] Fix asl throw

- asllib/Interpreter.ml
- herd/tests/instructions/ASL-pseudo-arch/catch-exec-twice.litmus
- herd/tests/instructions/ASL-pseudo-arch/catch-exec-twice.litmus.expected
- herd/tests/instructions/ASL-pseudo-arch/throw-propagate.litmus
- herd/tests/instructions/ASL-pseudo-arch/throw-propagate.litmus.expected
Fix double execution of matched catcher statement. Here is an illustrative test:
```
ASL catch-exec-twice
{}
type Bonga of exception;
func g() => integer
begin
try
throw Bonga {};
catch
when Bonga =>
let coucou = 11 ;
__DEBUG__(coucou);
end
return 0;
end
begin  
return g();
end
```
Due to the implementation of the "_implicit re-throw_" mechanism, the catcher statement `let coucou = 11; __DEBUG__(coucou);` was executed twice, resulting in printing the debug message twice.
The bug originates  in a non-linear usage of a monad argument, similarly to PR #909, #902 and #899.
> [herd,asl] Fix duplicated execution of catcher statement

- herd/variant.ml
- herd/variant.mli
- lib/parseTag.ml
- lib/parseTag.mli
- litmus/litmus.ml
- litmus/variant_litmus.ml
- litmus/variant_litmus.mli
Now, `-variant asl+exp` suffices, in place of `-variant asl,asl+exp`.
> [herd,litmus] Variant `asl+exp` implies variant `asl`

- asllib/ASTUtils.ml
- asllib/ASTUtils.mli
- asllib/Parser0.mly
- asllib/Typing.ml
- asllib/tests/regressions.t/empty-getter-called-with-slices-2.asl
- asllib/tests/regressions.t/getter_sub_tuple.asl
- asllib/tests/regressions.t/getter_subfield.asl
- asllib/tests/regressions.t/getter_subfields.asl
- asllib/tests/regressions.t/getter_subslice.asl
- asllib/tests/regressions.t/pstate-exp.asl
- asllib/tests/regressions.t/run.t
- asllib/tests/regressions.t/setter_bitfields.asl
- asllib/tests/regressions.t/setter_sub_tuple.asl
- asllib/tests/regressions.t/setter_subfield.asl
- asllib/tests/regressions.t/setter_subslice.asl
- asllib/tests/regressions.t/single-slice.asl
- herd/libdir/asl-pseudocode/implementations.asl
- herd/tests/instructions/ASL/func3.litmus
- herd/tests/instructions/ASL/func3.litmus.expected
This PR improves the handling of getters and setters to support all wanted behaviours.
The only strange case is the following:
```
getter F => bits(3)
begin return '000'; end
func main () => integer
begin
let -: bits(0) = F[];
return 0;
end
```
Which now passes, as it's permitted to have 0-length bitvectors.
> [asl] Rework inlining of getter/setters

- gen/cycle.ml
This PR solves a bug where a print statement in check fetch is triggered when using **diy7**, generating unwanted output.
> [gen] bug in check_fetch causing unwanted output

- Makefile
- gen/CArch_gen.ml
- gen/CCompile_gen.ml
- herd/lexConf_herd.mll
- herd/tests/diycross/C/C.cfg
- herd/tests/diycross/C/LB+fetch.addrlxrlx-porlxrlxs.litmus.expected
- herd/tests/diycross/C/LB+porlxrlx+fetch.addrlxrlx-porlxrlx.litmus.expected
- herd/tests/diycross/C/LB+porlxrlx+posWrlxrlx-porlxrlx.litmus.expected
- herd/tests/diycross/C/LB+porlxrlx+rmwrlxrlx-porlxrlx.litmus.expected
- herd/tests/diycross/C/LB+posWrlxrlx-porlxrlx+fetch.addrlxrlx-porlxrlx.litmus.expected
- herd/tests/diycross/C/LB+rmwrlxrlx-porlxrlx+fetch.addrlxrlx-porlxrlx.litmus.expected
- herd/tests/diycross/C/MP+porlxrlx+fetch.addrlxrlx-porlxrlx.litmus.expected
- herd/tests/diycross/C/MP+porlxrlx+posWrlxrlx-porlxrlx.litmus.expected
- herd/tests/diycross/C/MP+porlxrlx+rmwrlxrlx-porlxrlx.litmus.expected
- herd/tests/diycross/C/RR+RW+fetch.addrlxrlx-porlxrlx+posWrlxrlx-porlxrlx.litmus.expected
- herd/tests/diycross/C/RR+RW+fetch.addrlxrlx-porlxrlx+rmwrlxrlx-porlxrlx.litmus.expected
- herd/tests/diycross/C/RR+RW+fetch.addrlxrlx-porlxrlxs.litmus.expected
- herd/tests/diycross/C/RR+RW+porlxrlx+fetch.addrlxrlx-porlxrlx.litmus.expected
- herd/tests/diycross/C/RR+RW+porlxrlx+posWrlxrlx-porlxrlx.litmus.expected
- herd/tests/diycross/C/RR+RW+porlxrlx+rmwrlxrlx-porlxrlx.litmus.expected
- herd/tests/diycross/C/RR+WR+fetch.addrlxrlx-porlxrlx+porlxrlx.litmus.expected
- herd/tests/diycross/C/RR+WR+posWrlxrlx-porlxrlx+porlxrlx.litmus.expected
- herd/tests/diycross/C/RR+WR+rmwrlxrlx-porlxrlx+porlxrlx.litmus.expected
- herd/tests/diycross/C/RW+WR+fetch.addrlxrlx-porlxrlx+porlxrlx.litmus.expected
- herd/tests/diycross/C/RW+WR+posWrlxrlx-porlxrlx+porlxrlx.litmus.expected
- herd/tests/diycross/C/RW+WR+rmwrlxrlx-porlxrlx+porlxrlx.litmus.expected
- herd/tests/diycross/C/S+porlxrlx+fetch.addrlxrlx-porlxrlx.litmus.expected
- herd/tests/diycross/C/S+porlxrlx+posWrlxrlx-porlxrlx.litmus.expected
- herd/tests/diycross/C/S+porlxrlx+rmwrlxrlx-porlxrlx.litmus.expected
- internal/lib/testHerd.ml
The `Rmw` or `Exch` edge produces a primitive call `atomic_exchange_explicit(...,<mo>)`, while `Fetch.Add` will produce a prinitive call to `atomic_fetch_add_explicit(...,<mo>)`.
The memory_order `<mo>` depends on the combination of anotations `<ar>` and `<aw>` from the sequence
`<ar> Rmw <aw>` with:
+ `Sc Rmw Sc` yields `memory_order_seq_cst`
+ `Rlx Rmw Rlx` yields `memory_order_relaxed`
+ `Acq Rmw Rlx` yields `memory_order_acquire`
+ `Rlx Rmw Rel` yields `memory_order_release`
+ `Acq Rmw Rel` yields `memory_order_acq_rel`
Other sequences yield a fatal error.
Try for instance: `diyone7 -arch C Acq Rmw Rel PodWW Rfe PodRW Rlx Rfe`
> [gen] Generate C atomic exchange.

- catalogue/aarch64/tests/@all
- catalogue/aarch64/tests/STABLE.litmus
- litmus/AArch64Arch_litmus.ml
- litmus/ARMArch_litmus.ml
- litmus/ASMLang.ml
- litmus/LISAArch_litmus.ml
- litmus/MIPSArch_litmus.ml
- litmus/PPCArch_litmus.ml
- litmus/RISCVArch_litmus.ml
- litmus/X86Arch_litmus.ml
- litmus/X86_64Arch_litmus.ml
- litmus/archExtra_litmus.ml
When given as output parameters to gcc inline assembly templates, _initialised_ stable registers should have constraint "+" (and not "=") for their initialisation not to be overlooked by gcc.
Here is an example of the difference between initialised and non-initialised stable registers:
```
AArch64 L
Stable=X2
{}
P0        | P1        ;
MOV W0,W2  | MOV W2,#1 ;
| MOV W0,W2 ;
forall 0:X0=0 /\ 1:X0=1
```
The `X2` register of `P0` is implicitly initialised to zero, while  the content of  `P1:X2` is overwritten by `P1` first instruction.
+ For `P0` the output constraint `=` is not adequate. Such a constraint would allow **gcc** _not_ to  emit initialisation code. And **gcc** does behave that way.
+ For `P1` he output constraint `=` is adequate, as the register `P1:X2` is overwritten before …
> [litmus] Fix wrong register class for initialised stable registers

- asllib/Interpreter.ml
- asllib/doc/ASL.bib
- asllib/doc/ASLFormal.tex
- asllib/doc/ASLSemanticsReference.tex
- asllib/doc/ASLSyntaxReference.tex
- asllib/doc/ASLTypingReference.tex
- asllib/doc/ASLmacros.tex
- asllib/tests/ASLSemanticsReference.t/SemanticsRule.ATCNotDynamicErrorIfFalse.asl
- asllib/tests/ASLSemanticsReference.t/SemanticsRule.ATCVariousErrors.asl
- asllib/tests/ASLSemanticsReference.t/SemanticsRule.EConcat2.asl
- asllib/tests/ASLSemanticsReference.t/SemanticsRule.SCond2.asl
- asllib/tests/ASLSemanticsReference.t/SemanticsRule.SCond3.asl
- asllib/tests/ASLSemanticsReference.t/SemanticsRule.SCond4.asl
> [asl][semantics reference] Addressing feedback

- herd/AArch64Sem.ml
- herd/mem.ml
- herd/tests/instructions/AArch64.vmsa+mte/A007.litmus
- herd/tests/instructions/AArch64.vmsa+mte/A007.litmus.expected
- herd/tests/instructions/AArch64.vmsa+mte/A008.litmus
- herd/tests/instructions/AArch64.vmsa+mte/A008.litmus.expected
- herd/tests/instructions/AArch64.vmsa+mte/A009.litmus
- herd/tests/instructions/AArch64.vmsa+mte/A009.litmus.expected
- herd/tests/instructions/AArch64.vmsa+mte/A010.litmus
- herd/tests/instructions/AArch64.vmsa+mte/A010.litmus.expected
- herd/tests/instructions/AArch64.vmsa+mte/A011.litmus
- herd/tests/instructions/AArch64.vmsa+mte/A011.litmus.expected
- herd/tests/instructions/AArch64.vmsa+mte/A012.litmus
- herd/tests/instructions/AArch64.vmsa+mte/A012.litmus.expected
- herd/tests/instructions/AArch64.vmsa+mte/A013.litmus
- herd/tests/instructions/AArch64.vmsa+mte/A013.litmus.expected
- herd/tests/instructions/AArch64.vmsa+mte/A014.litmus
- herd/tests/instructions/AArch64.vmsa+mte/A014.litmus.expected
- herd/tests/instructions/AArch64.vmsa+mte/A015.litmus
- herd/tests/instructions/AArch64.vmsa+mte/A015.litmus.expected
- lib/constant.ml
This PR fixes three different issues in herd7 when simulating with `-variant vmsa,mte`.
1. Tag locations in post-condition are Physical symbols when running with `-variant vmsa`.
2. Fixes the possible executions for `STZ{,2}G` when there is a fault.
3. Fixes `lift_kvm` to correctly handle cases where a checked instruction runs into a fault.
For the 3 fixes, this PR contributes unit tests that demonstrate the issue and serve as regressions after the fix is applied.
> [herd] Fixes for -variant vmsa,mte

- herd/AArch64Sem.ml
- herd/tests/instructions/AArch64.neon/V70.litmus
- herd/tests/instructions/AArch64.neon/V70.litmus.expected
Consider litmus test
```
AArch64 V70
{
int x=1;
0:X0=x; 0:X3=y;
}
P0                 ;
LDR S1,[X3]        ;
FMOV W1,S1         ;
LDR W2,[X0,W1,SXTW];
forall 0:X2=1
```
Currently `herd7` would refuse to run the test with
```
Warning: File "V70.litmus": operation sxt non-existent for wide integers
```
The reason is that `W1` holds `wide` integer value from `S1` which blocks `sxt` operation. General purpose registers don't require `wide` integer and work pretty well with `narrow` one, so `demote` result of Neon register read for `FMOV`
> [herd]: Demote result of Neon register read for `FMOV`

- .github/workflows/make-test.yml
- dune
Using our "dev" profile will trigger some error whenever our "release" flags a warning. As a result, warnings will not reach production code...
> [action] Use dev profile for CI

- asllib/AST.mli
- asllib/ASTUtils.ml
- asllib/Interpreter.ml
- asllib/Native.ml
- asllib/PP.ml
- asllib/Serialize.ml
- asllib/Typing.ml
- asllib/doc/ASLFormal.tex
- asllib/doc/ASLTypingReference.tex
- asllib/doc/ASLmacros.tex
- asllib/tests/regressions.t/run.t
- asllib/types.ml
> Updates to 'ASL Typing Refernce'

- herd/herd.ml
- lib/argUtils.ml
- lib/argUtils.mli
In place of `-debug solver -debug mem`, one can now write `-debug solver,mem`.
> [herd] Option `-debug` accepts several, comma separated, arguments.

- asllib/aslref.ml
- asllib/error.ml
- herd/ASLSem.ml
The solution to silence _all_ warnings may be a bit too radical. Notice that there are two warnings only for now.
> [herd,asl] Do not output ASL typing warnings for herd

- herd/AArch64Arch_herd.ml
- herd/AArch64Sem.ml
- herd/tests/instructions/AArch64.sve/Y01.litmus
- herd/tests/instructions/AArch64.sve/Y01.litmus.expected
- jingle/AArch64Arch_jingle.ml
- lib/AArch64Base.ml
- lib/AArch64Parser.mly
- lib/stateParser.mly
- litmus/AArch64Compile_litmus.ml
Similar to `I_ADD_SV`, the SVE EOR instruction is added as `I_EOR_SV`. Tested with `diy7` on `qemu-aarch64`.
> [aarch64,sve] Add support for SVE EOR vectors, unpredicated

- asllib/Typing.ml
- asllib/doc/ASLFormal.tex
- asllib/doc/ASLRefProgress.tex
- asllib/doc/ASLSemanticsReference.tex
- asllib/doc/ASLSyntaxReference.tex
- asllib/doc/ASLTypingReference.tex
- asllib/doc/ASLmacros.tex
* Updated the typing reference to reflect the implementation of symbolic ranges (see https://github.com/herd/herdtools7/pull/924 and https://github.com/herd/herdtools7/pull/943).
* Minor changes following feedback on the ASL references.
> [asl][typing] Updated ASL Typing Reference for symbolic ranges

- litmus/preSi.ml
All label related code should depend on the existence of the "instruction.h" file in the architecture specific sub-directory of `litmus/libdir`. The "instruction.h" file defines the C type of instructions `ins_t`.
In other words, the absence of this file means that we give up on implementing code addressing for a given architecture.
This PR fixes a bug discovered by testing PR #966 : although we gave up on implementing instruction offset computation in the complex case of the varying length instruction encoding of Intel processors, part of the instruction offset computation code was emitted, leading to systematic fatal compilation errors in `kvm` mode.
> [litmus] Emit label related code only when instruction type is defined

- asllib/ASTUtils.ml
- asllib/StaticModel.ml
- asllib/Typing.ml
- asllib/doc/.gitignore
- asllib/doc/ASLFormal.tex
- asllib/doc/ASLSemanticsReference.tex
- asllib/doc/ASLSyntaxReference.tex
- asllib/doc/ASLTypingReference.tex
- asllib/doc/ASLmacros.tex
- asllib/doc/Makefile
- asllib/instrumentation.ml
- asllib/types.ml
- asllib/types.mli
* Addressed comments on ASL Typing Reference.
* Merged some rules, for example, LELocalVar/LEGLobalVar are now just LEVar.
* Added notations to enable locating rules that correspond to helper functions defined in other functions. I'm using `(* RuleName( *)` as a start delimiter for the code for a rule named `RuleName` and `(* RuleName) *)` as an ending delimiter.
* Added StaticModel.ml, StaticModel.ml, ASTUtils.ml, and StaticEnv.ml to Make file for line number extraction to enable referring to code used by the corresponding typing rules.
* Change font used for functions and relations throughout all reference from teletype to mathematical+italics.
> [asl][references] Addressing feedback for the typing review

- Makefile
- herd/eventsMonad.ml
- herd/mem.ml
- herd/tests/instructions/AArch64/L103.litmus
- herd/tests/instructions/AArch64/L103.litmus.expected
- herd/tests/instructions/ASL-pseudo-arch/YL-01.litmus
- herd/tests/instructions/ASL-pseudo-arch/YL-01.litmus.expected
- lib/ASLScalar.ml
- lib/capabilityScalar.ml
- lib/constant.mli
- lib/extendScalar.ml
- lib/int128Scalar.ml
- lib/int32Scalar.ml
- lib/int64Scalar.ml
- lib/scalar.mli
- lib/symbValue.ml
- lib/uint128Scalar.ml
For XOR, the optimization when the two values are equal (`compare` returns 0) is to return `V.zero`. However, the actual result might be different for different scalar types. Thus `V.zero` should not be used in all the cases.
An example is the `ASLConstant` module, when XOR-ing two bitvectors, the result should be a zeroed bitvector of the same length, rather than `V.zero`, i.e. `S_Int Z.zero`.
This PR implements a fix by removing the optimization. An alternative fix would be to make `zero` generic over the scalar's type (and similarly `one` if it's used for generic optimization).
> [herd,asl] Fix unsound XOR optimization

- herd/event.ml
- herd/machModelChecker.ml
- herd/mem.ml
- herd/memUtils.ml
- lib/constant.ml
- lib/constant.mli
- lib/myMap.ml
- lib/symbValue.ml
- lib/value.mli
With ASL the cat interpreter now faces inputs of thousands events. This PR regroups attempts to avoid some quadratic behaviours in the computation of pre-defined relations such as the `loc` relation.
More precisely, we compute the `loc` relation by first computing a mapping from locations to event sets. Then we union all the subrelation made by applying the cartesian product to each  event set. Relations `same-low-order-bits`, `int` and `ext` are computed by a similar technique.
> [herd] Some optimisation aiming at faster Cat file interpretation

- doc/.gitignore
- doc/Makefile
- doc/SB.litmus
- doc/herd.tex
- doc/sc.cat
The simplified model matches the explanatory text of the manual --- see issue #985.
> [doc] Fix the explanatory sc.cat model

- lib/CType.ml
- lib/CType.mli
- litmus/AArch64Arch_litmus.ml
- litmus/ARMArch_litmus.ml
- litmus/ASMLang.ml
- litmus/CArch_litmus.ml
- litmus/CCompile_litmus.ml
- litmus/CLang.ml
- litmus/CTarget.ml
- litmus/CTarget.mli
- litmus/KSkel.ml
- litmus/LISAArch_litmus.ml
- litmus/LISALang.ml
- litmus/MIPSArch_litmus.ml
- litmus/PPCArch_litmus.ml
- litmus/RISCVArch_litmus.ml
- litmus/X86Arch_litmus.ml
- litmus/X86_64Arch_litmus.ml
- litmus/archExtra_litmus.ml
- litmus/arch_litmus.mli
- litmus/compile.ml
- litmus/language.ml
- litmus/preSi.ml
- litmus/skel.ml
- litmus/skelUtil.ml
- litmus/target.mli
- litmus/template.ml
- litmus/top_klitmus.ml
- litmus/top_litmus.ml
Since PR #483 the initial values of registers given as input parameters to the assembly template are casted to the type of the register as declared or to the default `int` type. In some cases the register type is wrong and the cast truncates the value. Consider:
```
AArch64 IntInit
{
0:X0=0x0101010101010101;
uint64_t x;
0:X1=x;
}
P0        ;
STR X0,[X1] ;
locations [x;]
```
The type of the `0:X0` register is the default `int`. Although **litmus7** flags a warning, one tends to neglect the problem, since the register is not printed. However, the cast to `int` destroys the higher order part of the value and the final output is wrong, although `x` type is correct:
```
...
Histogram (1 states)
40000 :>[x]=0x1010101;
...
```
Out test base contains many such tests and we cannot reject them. …
> [litmus] Change types of registers

- lib/mySet.ml
- lib/mySet.mli
Function `of_list` is now part of OCaml standard library. Also delete some unused functions.
> [lib] Simplify  the `mySet` module

- litmus/ASMLang.ml
The following test was compiled by **litmus7** to a C files that could not compile:
```
AArch64 NoPa
{
int x;
0:X1=PTE(x);
0:X2=(valid:0);
1:X1=x;
}
P0        | P1          ;
STR X2,[X1] | LDR W0,[X1] ;
exists fault(P1,x)
```
With this PR, **litmus7** now flags a fatal error:
```
% /opt/WIP/bin/litmus7 -mach kvm-aarch64 NoPa.litmus -o /tmp/A.tar
File "NoPa.litmus" litmus cannot handle pte initialisation with '(oa:PA(), valid:0)'
```
> [litmus] Fail on incomplete pte values

- asllib/ASTUtils.ml
- asllib/ASTUtils.mli
- asllib/StaticInterpreter.ml
- asllib/StaticModel.ml
- asllib/StaticModel.mli
- asllib/Typing.ml
- asllib/doc/ASLTypingReference.tex
- asllib/doc/ASLmacros.tex
- asllib/tests/static.ml
- asllib/tests/typing.t/run.t
- asllib/types.ml
This PR attempts to streamline static normalisation in a few ways:
- Avoid using both static evaluation and normalisation if one should suffice
- Weaken normalisation based on its usage
- Remove "affectations"
- Reduce the kinds of constraints it can track to just equality/inequality with zero
- Fix a couple of potential bugs
- Avoid reducing polynomials by maintaining a stronger invariant about the absence of 0-coefficients
- Limit catching of `ConjunctionBottomInterrupt` exception to within a single function, to simplify control flow
- Along the way, do various refactors - including a final significant refactor attempting to modularise the various moving parts in normalisation (monomials/polynomials/internal representation)
> Streamlining the static model

- herd/AArch64ASLSem.ml
- herd/ASLAction.ml
- herd/BellAction.ml
- herd/CAction.ml
- herd/CSem.ml
- herd/JavaAction.ml
- herd/action.mli
- herd/event.ml
- herd/eventsMonad.ml
- herd/machAction.ml
- herd/mem.ml
- herd/monad.mli
- herd/semExtra.ml
- herd/tests/instructions/AArch64.kvm/A018.litmus.expected
- herd/tests/instructions/AArch64.kvm/A018.litmus.expected-warn
- herd/top_herd.ml
- herd/variant.ml
- herd/variant.mli
Rename "tooFar" events into "CutOff", a better name. Also change the triggering of the "Some outcomes may be missing" warning:  rhe  warning is now emitted as soon as there is an execution candidate with a cutoff node.
> [herd] Rename toofar to cutoff

- herd/parseTest.ml
- lib/miscParser.ml
- lib/miscParser.mli
Implement `Unroll=<int>` metadata in test source. As usual, this in-test specification has the highest precedence.
> [herd] Unroll metadata

- asllib/AST.mli
- asllib/ASTUtils.mli
- asllib/Parser.mly
- asllib/StaticEnv.ml
- asllib/StaticEnv.mli
- asllib/Typing.ml
- asllib/doc/ASLReference.tex
- asllib/doc/ASLmacros.tex
- asllib/doc/AbstractSyntax.tex
- asllib/doc/GlobalDeclarations.tex
- asllib/doc/RelationsOnTypes.tex
- asllib/doc/Statements.tex
- asllib/doc/SubprogramCalls.tex
- asllib/doc/SubprogramDeclarations.tex
- asllib/doc/SymbolicEquivalenceTesting.tex
- asllib/doc/SymbolicSubsumptionTesting.tex
- asllib/doc/TypeChecking.tex
- asllib/doc/Types.tex
- asllib/tests/regressions.t/more-assignments-examples.asl
- asllib/tests/regressions.t/more-invocation-examples.asl
- asllib/tests/typing.t/CPositive9.asl
After receiving feedback on names and confusing terms, I'm going with the following renaming:
- (StaticEnv.global) Renamed `subprogram_renamings` to `overloaded_subprograms`.
- (AST) Renamed `int_constraints` to `constraint_kind`, which is more accurate and avoids confusion with `int_constraint`.
> [asl] Renamed terms for more clarity

- asllib/doc/ASLmacros.tex
I'm not sure which package define this macro and 
```
% latexdef --find \notbool
\notbool:
undefined
```
I'm therefore `\renewcommand`ing this to force LaTeX to accept it.
> [asl][reference] Fix LaTeX error on having \notbool defined twice

- asllib/doc/ASLmacros.tex
- asllib/doc/PrimitiveOperations.tex
The fix in #1009 didn't work for all configurations.
\notbool is defined in some configurations and not others so I'm renaming to \aslnotbool.
> [asl][reference] fix bug to enable making the ASL Reference

- asllib/Typing.ml
- asllib/Typing.mli
- asllib/aslref.ml
- asllib/doc/Statements.tex
- herd/ASLSem.ml
This PR adds type annotations to local and global declarations when `--print-typed` is specified on the command line.
This doesn't have any observable effect on the type system and semantics, but it allows reading the types inferred by ASLRef.
For example `% aslref --print-typed asllib/tests/ASLTypingReference.t/TypingRule.LDTuple.asl` makes the types inferred for `g`, `x`, and `y` visible:
```
var g = 3;
func main () => integer
begin
let (x, -, y): (integer {5}, integer {3}, boolean) = (5, 3, TRUE);
assert ((x == 5) && y);
return 0;
end
```
Also, a small fix to the documentation of `annotate_stmt` for declaration statements.
> [asl] Add types to local/global storage elements when given --print-typed

- asllib/StaticEnv.ml
There are two functions named `add_global_storage` - one in Typing.ml and another in StaticEnv.ml. I've dropeed the begin/end markers and TypingRule.AddGlobalStorage from the version in StaticEnv.ml, since it is only used by the version in Typing.ml.
> [asl][reference] Fix double declaration of add_global_storage

- herd/AArch64Sem.ml
- herd/event.ml
- herd/eventsMonad.ml
- herd/monad.mli
Supersedes #963.
- Add `iico_ctrl` to `AnyActiveElement` checks (for scatter load and gather store)
- Add `iico_ctrl` to `ActivePredicateElement` checks
- Add `iico_order` to SVE store[^1]
- Fix the semantics for the SVE `NEG` instruction
[^1]: Arm ARM B2.5 SVE memory ordering relaxations, R_CJHWV: "When a single SVE vector store instruction generates multiple writes to the same location, the instruction ensures that these writes appear in the coherence order for that location, in order of increasing vector element number. No other ordering restrictions apply to memory effects generated by the same SVE store instruction."
Example graph change for [`herd/tests/instructions/AArch64.sve/Y01.litmus`](https://github.com/herd/herdtools7/blob/39878681a0b8662d0fb740ad5b571d1a1ee0e8f1/herd/tests/in …
> Rework the intrinsic dependencies for SVE instructions

- gen/AArch64Arch_gen.ml
- gen/AArch64Compile_gen.ml
- gen/cycle.ml
- gen/edge.ml
- gen/final.ml
- gen/libdir/forbidden_ifetch.conf
- gen/top_gen.ml
This commit:
- changes the function of the I annotation to work on Reads instead of Writes.
- prevents Plain annotations from eating Instr annotations, allowing the user to specify whether a relaxation in diy7 can be followed/preceded by I or not. This is useful when trying to build relaxations from a cat file for lines specifying `[~(Imp & M)]`
- Remove explicit reads of Labels
> [gen] I annotation on reads, reject P becoming I

- asllib/doc/SubprogramCalls.tex
> [asl][reference] A minor fix to SemanticsRule.MatchFuncRes

- asllib/ASTUtils.mli
- asllib/Lexer.mll
- asllib/aslref.ml
- asllib/builder.ml
- asllib/builder.mli
- asllib/bundler.ml
- asllib/doc/ASLRefProgress.tex
- asllib/doc/LexicalStructure.tex
- asllib/tests/lexer.t
- herd/ASLParseTest.ml
- lib/ASLBase.ml
This PR also removes the following keywords from the reserved list:
```
access
advice
after
aspect
before
entry
expression
get
is
pattern
pointcut
replace
set
statements
watch
```
> [asl] Reserve variables starting with '__'

- Makefile
- asllib/doc/ASLmacros.tex
- asllib/doc/ErrorCodes.tex
- asllib/doc/Expressions.tex
- asllib/doc/PatternMatching.tex
* Made the necessary changes to syntax / AST building / Typing to synchronize with the implementation.
* Now that building an AST can result in a build error, that information needs to be propagated to the signatures of all builder functions that transitively depend on `build_expr`. I made some of these changes, but there are many left. I am deferring this until the changes to the syntax and AST stabilize a bit, to avoid having to resolve many conflicts with recent and upcoming PRs.
* the `clean` target of the main `Makefile` now invokes the clean target of `asllib/Makefile`. This solves the issue of `make asldoc` failing when `asllib` is not clean.
> [asl][reference] Synchronize reference for #1044

- asllib/tests/ASLDefinition.t/Bitfields_nested.asl
- asllib/tests/ASLDefinition.t/run.t
Issue: `dune exec aslref asllib/tests/ASLDefinition.t/Bitfields_nested.asl` generates the following error:
```
File asllib/tests/ASLDefinition.t/Bitfields_nested.asl, line 30,
characters 11 to 32:
ASL Execution error: Assertion failed: (common == common_fmt0).
```
Actually, to refer to the upper 16 bits, the slicing range should be `[31:16]`. Also add it to the cram test.
> [asl,test] Fix `Bitfields_nested` example

- asllib/tests/ASLDefinition.t/Bitfields_nested.asl
- asllib/tests/ASLDefinition.t/run.t
- lib/miscParser.ml
- lib/miscParser.mli
- litmus/klitmus.ml
- litmus/preSi.ml
- litmus/skel.ml
- litmus/test_litmus.ml
- litmus/top_klitmus.ml
- litmus/variant_litmus.ml
- litmus/variant_litmus.mli
The option disables memory location initialisation. It is useful for time measures, especially when arrays are involved.
> [litmus] New `-variant noinit` option.

- herd/AArch64Sem.ml
- herd/tests/instructions/AArch64.MTE/B009.litmus
- herd/tests/instructions/AArch64.MTE/B009.litmus.expected
- herd/tests/instructions/AArch64.MTE/B010.litmus
- herd/tests/instructions/AArch64.MTE/B010.litmus.expected
- herd/tests/instructions/AArch64.MTE/B011.litmus
- herd/tests/instructions/AArch64.MTE/B011.litmus.expected
- herd/tests/instructions/AArch64.MTE/B012.litmus
- herd/tests/instructions/AArch64.MTE/B012.litmus.expected
- herd/tests/instructions/AArch64.MTE/B013.litmus.expected
- herd/tests/instructions/AArch64.MTE/B014.litmus
- herd/tests/instructions/AArch64.MTE/B014.litmus.expected-failure
- lib/AArch64Base.ml
Partially revert c00eaf38b63 ("[herd]: Fix address generation for STG, LDG and friends").
Altough it is correct that address generation using immediate signed offset scaled by the Tag granule, it only applies to encoding of the instruction but immediate for assembler has different requirement:
```
<simm> Is the optional signed immediate offset, a multiple of 16
in the range -4096 to 4080, defaulting to 0 and encoded in the "imm9"
field.
```
and it is what assembler implements
```
Error: immediate value must be a multiple of 16 at operand 2 -- `stg X1,[X0,#1]'
Error: immediate value must be a multiple of 16 at operand 2 -- `ldg X3,[X0,#1]'
```
So roll back herd part and update MTE tests, also add extra check for immediate and dedicated litmus test to exercise the check.
> [herd]: Fix address generation for STG, LDG and friends (again)

- asllib/Parser.mly
- asllib/doc/Slicing.tex
- asllib/doc/Syntax.tex
- asllib/tests/regressions.t/run.t
- asllib/tests/regressions.t/slice-width-shorthand.asl
Desugar to `Slice_Length(0, wid)` during parsing, add a test, and update reference documentation.
> [asl] Add `[:wid]` shorthand for `[0+:wid]` slice

- asllib/Interpreter.ml
- asllib/Parser.mly
- asllib/Parser0.mly
- asllib/Typing.ml
- asllib/builder.ml
- asllib/bundler.ml
- asllib/doc/ASLFormal.tex
- asllib/doc/ASLReference.tex
- asllib/doc/ASLmacros.tex
- asllib/doc/AbstractSyntax.tex
- asllib/doc/AssignableExpressions.tex
- asllib/doc/ErrorCodes.tex
- asllib/doc/Expressions.tex
- asllib/doc/GlobalDeclarations.tex
- asllib/doc/RelationsOnTypes.tex
- asllib/doc/Slicing.tex
- asllib/doc/Specifications.tex
- asllib/doc/Statements.tex
- asllib/doc/Syntax.tex
- asllib/doc/TopLevel.tex
- asllib/doc/TypeSystemUtilities.tex
- asllib/doc/introduction.tex
- asllib/gparser0.ml
- asllib/instrumentation.ml
- asllib/tests/ASLDefinition.t/spec3.asl
- asllib/tests/ASLSemanticsReference.t/SemanticsRule.CatchNoThrow.asl
- asllib/tests/ASLSemanticsReference.t/run.t
- herd/ASLSem.ml
* Renamed the grammar non-terminal `ast` to `spec`.
* Added a new chapter that shows how scanning, parsing, type-checking, and semantic evaluation can be combined together to implement an ASL interpreter.
* Unified all typing rules for global declarations into a single rule with case rules.
* Started employing a `\ProseF` macro for a function/relation `\F` to standardize the prose for each occurrence of `\F` and to lower the chance of typos/errors.
* Reworked dependencies and topological ordering and added explanations.
* Fixed wording in disclaimer per request from Jade.
* Fixed Fibonaci example in introduction to include a recursion limit, per request from Chris January.
> ASL Reference: Top-level chapter and various fixes

- asllib/AST.mli
- asllib/ASTUtils.ml
- asllib/Native.ml
- asllib/PP.ml
- asllib/Parser.mly
- asllib/Serialize.ml
- asllib/Typing.ml
- asllib/doc/ASLmacros.tex
- asllib/doc/AbstractSyntax.tex
- asllib/doc/ErrorCodes.tex
- asllib/doc/LocalStorageDeclarations.tex
- asllib/doc/Specifications.tex
- asllib/doc/Syntax.tex
- asllib/doc/TypeAttributes.tex
- asllib/doc/Types.tex
- asllib/error.ml
- asllib/tests/regressions.t/inherit-integer-constraints-bad-basic.asl
- asllib/tests/regressions.t/inherit-integer-constraints-bad-tuple.asl
- asllib/tests/regressions.t/inherit-integer-constraints-bad-type.asl
- asllib/tests/regressions.t/inherit-integer-constraints.asl
- asllib/tests/regressions.t/run.t
- asllib/types.ml
This PR iterates on https://github.com/herd/herdtools7/pull/1056. In particular, that PR used the `integer{}` syntax (AST: `WellConstrained []`) to inherit integer constraints from right-hand sides to left-hand sides. However, `integer{}` could be confused with a hypothetical "empty" set of constraints, and the changes to the reference documents and AST did not help this.
This PR replaces this with the `integer{-}` syntax, which parses to a new AST node `PendingConstrained : constraint_kind`. Similarly, reference documentation refers to these integers as "pending constrained". This should avoid the confusion above. This therefore partially reverts the PR above, but not fully.
> [asl] Pending constrained integers

- herd/libdir/asl-pseudocode/implementations.asl
- herd/libdir/asl-pseudocode/implementations0.asl
As they have different type signatures, those functions can have the same names. Inspired by PR #1084.
> [herd,aarch64,asl] Simplify physical memory functions

- asllib/doc/ASLFormal.tex
- asllib/doc/AssignableExpressions.tex
- asllib/doc/PatternMatching.tex
- asllib/doc/RelationsOnTypes.tex
- asllib/doc/SubprogramCalls.tex
- asllib/doc/SymbolicEquivalenceTesting.tex
- asllib/doc/TypeDeclarations.tex
- asllib/doc/TypeDomains.tex
These are flagged by `pandoc` and may also make sense for the upstream LaTeX tool.
> Small fixes for ASL Reference

- herd/AArch64Arch_herd.ml
- herd/AArch64Sem.ml
- jingle/AArch64Arch_jingle.ml
- lib/AArch64Base.ml
- lib/AArch64Parser.mly
- litmus/AArch64Compile_litmus.ml
Currently sanity checks for vector instructions done during parsing and asserts if instruction is malformed - that definitely is not user-friendly and we could do better. Let's convert all asserts for vector instructions to checks in dedicated validation (`is_valid`) pass.
> Get rid of asserts in AArch64 instruction parser

- asllib/libdir/stdlib0.asl
Using V0 grammar changes in https://github.com/herd/herdtools7/pull/1074, the V0 standard library functions used for backwards compatibility can simply call their V1 versions with appropriate parameter instantiations.
> [asl] Simplify V0 standard library

- Makefile.aarch64
- catalogue/aarch64-VMSA/tests/newlob/@all
- catalogue/aarch64-VMSA/tests/order-via-faults/@all
- litmus/libdir/kvm-armv8.1+rcpc.cfg
Restore `make litmus-aarch64-test` functionality.
> [litmus,test] Fix a few glitches

- herd/AArch64Sem.ml
We want to update environment with pair `destination register=value` rather than `system register=value`
> [herd, aarch64]: fix nextSet for MRS instruction

- catalogue/bpf/shelf.py
- catalogue/bpf/tests/amo-sequence-1.litmus
- catalogue/bpf/tests/amo-sequence-2.litmus
- catalogue/bpf/tests/kinds.txt
- herd/libdir/bpf.cat
Language models such as LKMM and C11 allow so called "AMO sequences" to provide a certain form of cumulativity: for example,
$ cat lkmm-amo-sequence.litmus
C lkmm-amo-sequence
(*
* Result: Never *)
{}
P0(int *x, atomic_t *y)
{
WRITE_ONCE(*x, 1);
atomic_set_release(y, 1);
}
P1(atomic_t *y)
{
atomic_inc(y);
}
P2(int *x, atomic_t *y)
{
int r0;
int r1;
r0 = atomic_read_acquire(y);
r1 = READ_ONCE(*x);
}
exists (2:r0=2 /\ 2:r1=0)
$ herd7 -conf linux-kernel.cfg lkmm-amo-sequence.litmusTest lkmm-amo-sequence Allowed
States 5
2:r0=0; 2:r1=0;
2:r0=0; 2:r1=1;
2:r0=1; 2:r1=0;
2:r0=1; 2:r1=1;
2:r0=2; 2:r1=1;
No
Witnesses
Positive: 0 Negative: 9
Condition exists (2:r0=2 /\ 2:r1=0)
Observation lkmm-amo-sequence Never 0 9
Time lkmm-amo-sequence 0.01
Hash=ad9b6e1caa2fac8973b38ba285fa0d04
In contrast,
$ …
> BPF: Add amo-sequences

- asllib/Parser.mly
- herd/libdir/asl-pseudocode/implementations.asl
- herd/libdir/asl-pseudocode/patches.asl
- herd/tests/instructions/ASL-pseudo-arch/LB-02.litmus
- herd/tests/instructions/ASL-pseudo-arch/LB-03.litmus
- herd/tests/instructions/ASL-pseudo-arch/LB-04.litmus
- herd/tests/instructions/ASL-pseudo-arch/LB-05.litmus
- herd/tests/instructions/ASL-pseudo-arch/LB-06.litmus
- herd/tests/instructions/ASL-pseudo-arch/LB-07.litmus
- herd/tests/instructions/ASL-pseudo-arch/LB-08.litmus
- herd/tests/instructions/ASL-pseudo-arch/LB-09.litmus
- herd/tests/instructions/ASL-pseudo-arch/LB-10.litmus
- herd/tests/instructions/ASL-pseudo-arch/LB-11.litmus
- herd/tests/instructions/ASL-pseudo-arch/MP-01.litmus
- herd/tests/instructions/ASL-pseudo-arch/MP-02.litmus
- herd/tests/instructions/ASL-pseudo-arch/for-toofar.litmus
- herd/tests/instructions/ASL-pseudo-arch/repeat-toofar.litmus
- herd/tests/instructions/ASL-pseudo-arch/while-toofar.litmus
- herd/tests/instructions/ASL/assign2.litmus
- herd/tests/instructions/ASL/assign3.litmus
- herd/tests/instructions/ASL/bitfields1.litmus
- herd/tests/instructions/ASL/case1.litmus
- herd/tests/instructions/ASL/data-return-01.litmus
- herd/tests/instructions/ASL/data-return-02.litmus
- herd/tests/instructions/ASL/func1.litmus
- herd/tests/instructions/ASL/func2.litmus
- herd/tests/instructions/ASL/func3.litmus
- herd/tests/instructions/ASL/func4.litmus
- herd/tests/instructions/ASL/records.litmus
- herd/tests/instructions/ASL/unknown.litmus
I believe this is legacy support for prior ASL1 syntax, which is no longer in the language definition. As requested by @nigelito
> Remove `::` to denote types

- asllib/bitvector.ml
- asllib/tests/regressions.t/stdlib.asl
At the moment the expression `SInt('')` fails. Consider the following test:
```
begin
let x = SInt('');
println(x);
return 0;
end;
```
Execution yields:
```
% aslref sint0.asl 
Fatal error: exception Invalid_argument("index out of bounds")
```
As a fix, the expression now has value zero.
However the type of `SInt('')` is problematic. With `aslref` option `--print-typed`, we see:
```
...
let x: integer {(- (2 ^ (0 - 1)))..((2 ^ (0 - 1)) - 1)} = SInt{0}('');
...
```
This is problematic as `2^(0-1)` is illegal. Nevertheless, until this question is settled, avoiding a cryptic failure looks like a decent solution.
A specific exception is another option,  @relokin, @HadrienRenaud., @jalglave?
> [asl] Change 'SInt' behaviour on zero-length bitvector.

- asllib/Parser.mly
- asllib/doc/ASLmacros.tex
- asllib/doc/AbstractSyntax.tex
- asllib/doc/Expressions.tex
- asllib/doc/GlobalDeclarations.tex
- asllib/doc/GlobalStorageDeclarations.tex
- asllib/doc/PatternMatching.tex
- asllib/doc/Syntax.tex
This patch removes all inline derivations except for `binop` and `unop`, which need to be inlined for the lr(1) precedence derivations.
Some new production rules were added to resole shift/reduce conflicts explicitly.
> [asl][reference] Remove inlining of clist and storage_keyword

- Makefile
- internal/herd_diycross_regression_test.ml
- internal/herd_regression_test.ml
- internal/lib/args.ml
- internal/lib/args.mli
- internal/lib/testHerd.ml
- internal/lib/testHerd.mli
By popular demand, the `-nohash` option of the `mcompare` tool  now exists for regression tools.
When present, this option disables the check of hashes produced by herd during regression testing.
Option is set for ASL tests.
> [test] Add option `-nohash` to test tools.

- .github/workflows/run-litmus-x86_64.yml
Small change, useful, useful when something went wrong for the scheduled action.
> [ci] Add the "dispatch" property to the run-litmus action

- herd/AArch64Arch_herd.ml
- herd/AArch64Sem.ml
- herd/tests/instructions/AArch64/A259.litmus
- herd/tests/instructions/AArch64/A259.litmus.expected
- jingle/AArch64Arch_jingle.ml
- lib/AArch64Base.ml
- lib/AArch64Lexer.mll
- lib/AArch64Parser.mly
- lib/faultType.ml
- lib/faultType.mli
- litmus/AArch64Compile_litmus.ml
- litmus/libdir/_aarch64/kvm_fault_handler.c
- litmus/libdir/_aarch64/kvm_fault_type.c
This commit extends the herd7 model to support litmus tests with SVC instructions.
> [herd] Add support for SVC instruction

- asllib/Parser0.mly
@acjf3 found some unexpected behaviour with unary operator precedence in ASL0. In particular, for the following example of concrete syntax:
```
- 1 MOD 2
- 1 * 2
```
Running `aslref --print` gives:
```
- (1 MOD 2)
- (1 * 2)
```
This is not consistent with ASL1's precedence, and seems unexpected given the concrete syntax.
This PR ensures the above becomes:
```
(- 1) MOD 2
(- 1) * 2
```
> [asl] Fix unary operator precedence for ASL0

- asllib/doc/ASLmacros.tex
- asllib/doc/LocalStorageDeclarations.tex
- asllib/doc/Statements.tex
- asllib/doc/Syntax.tex
- asllib/doc/Types.tex
This PR fixes the following:
* Rename the `elseif` terminal to `elsif`
* Add a semicolon after a statement function call (`call` -> `call ;`)
* Correct a few instances where `\Nty` was used instead of `\Nasty` (missing `:`)
* Defined `build_as_ty` which was used in `opt_typed_identifier` but never described. Also modified the formal descriptions of the above rules to use it instead of `build_ty`
* Correct the statement no-else case - it should be empty, not `pass`
> [asl][reference] Fix minor bugs in grammar spec

- asllib/StaticOperations.ml
- asllib/doc/ASLmacros.tex
- asllib/doc/SymbolicSubsumptionTesting.tex
- asllib/tests/ASLTypingReference.t/TypingRule.ConstraintMod.bad.asl
- asllib/tests/ASLTypingReference.t/run.t
- asllib/tests/division.t/static-mod-intervals.asl
The inference of a constraint resulting from the `MOD` operation needed to subtract 1 from the upper bound.
Consider the following example (now added to the list of tests):
```
begin
var x : integer{0..10};
var y = 3;
var z = x MOD y;
z = 0;
z = 1;
z = 2;
z = 3; // Illegal: the type inferred for z is integer{0..2}
return 0;
end;
```
the last assignment to `z` should be illegal.
> [asl] Fix inference of constraints with MOD

- asllib/AST.mli
- asllib/ASTUtils.ml
- asllib/ASTUtils.mli
- asllib/Interpreter.ml
- asllib/PP.ml
- asllib/Parser.mly
- asllib/Parser0.mly
- asllib/Serialize.ml
- asllib/Typing.ml
- asllib/desugar.ml
- asllib/desugar.mli
- asllib/doc/ASLmacros.tex
- asllib/doc/AbstractSyntax.tex
- asllib/doc/Bitfields.tex
- asllib/doc/Makefile
- asllib/doc/Specifications.tex
- asllib/doc/Statements.tex
- asllib/doc/Syntax.tex
- asllib/tests/ASLSyntaxReference.t/ASTRule.Desugar_SCase1.asl
- asllib/tests/ASLSyntaxReference.t/ASTRule.Desugar_SCase2.asl
- asllib/tests/ASLSyntaxReference.t/run.t
* Moved desugaring of `case` statements to the AST building.
* Documented the desugaring in the ASL Reference.
* Added requirements for desugaring `case` statements to the ASL Reference.
* Added examples for desugaring `case` statements.
* Fixed pretty-printing of conditional and while statements by ending them with a ;
* Fixed pretty-printing of `-` patterns by surrounding them with braces.
* Optimized desugaring of case statements with an otherwise alternative by not adding an unnecessary condition with a call to `Unreachable()`.
> ASL: desugar case statement

- asllib/doc/ASLmacros.tex
- asllib/doc/ErrorCodes.tex
- asllib/doc/Expressions.tex
- asllib/doc/doclint.py
Updated SemanticsRule.EArbitrary to return a dynamic error when the domain of the given type is empty.
> [asl][reference] Synchronized the reference for #1130

- asllib/SideEffect.ml
- asllib/SideEffect.mli
- asllib/Typing.ml
- asllib/doc/ASLmacros.tex
- asllib/doc/AbstractSyntax.tex
- asllib/doc/ErrorCodes.tex
- asllib/doc/PatternMatching.tex
- asllib/doc/SideEffects.tex
- asllib/doc/Slicing.tex
- asllib/doc/Statements.tex
- asllib/doc/SubprogramCalls.tex
- asllib/doc/TypeDomains.tex
- asllib/doc/TypeSystemUtilities.tex
- asllib/doc/Types.tex
- asllib/instrumentation.ml
Note that we deliberately do not rename "static interpretation" (implementation in `StaticInterpreter.ml`) as this is actually doing static interpretation during type-checking.
We only rename the concept of "statically evaluable" to "symbolically evaluable" - i.e. anything which uses side-effect analysis to decide whether an expression can be evaluated deterministically without side-effects.
> [asl][reference] Rename "statically evaluable" -> "symbolically evaluable"

- herd/AArch64Sem.ml
- lib/symbValue.ml
When computing the status flags NZCV, it is important not to introduce actual booleans.
As a matter of fact, the code assumes the encoding of false as 0 and true as 1. If booleans are encoded differently the old code fails. In practice this untimely situation occurs where AArch64Sem code is executed in AArch64+ASL mode, which indeed occurs. The fix consists in introducing some explicit boolean to integer operations `(fun b -> b ? 1 : 0)`, and to change the readBit operation output.
> [herd,aarch64] Force integer encoding of booleans in NZCV computation

- herd/AArch64Sem.ml
- herd/eventsMonad.ml
- herd/monad.mli
- herd/tests/diycross/AArch64.mixed.strict/MP+dmb.syh2h0+amo.casa.w0w0-pow0w0.litmus.expected
- herd/tests/diycross/AArch64.mixed.strict/MP+dmb.syh2h2+amo.casa.w0w0-pow0w0.litmus.expected
- herd/tests/diycross/AArch64.mixed.strict/MP+dmb.syh2w0+amo.casa.h0h0-poh0w0.litmus.expected
- herd/tests/diycross/AArch64.mixed.strict/MP+dmb.syh2w0+amo.casa.h2h2-poh2w0.litmus.expected
- herd/tests/diycross/AArch64.mixed.strict/MP+dmb.syw0h0+amo.casa.w0w0-pow0h0.litmus.expected
- herd/tests/diycross/AArch64.mixed.strict/MP+dmb.syw0h2+amo.casa.w0w0-pow0h0.litmus.expected
- herd/tests/diycross/AArch64.mixed.strict/MP+dmb.syw0w0+amo.casa.h0h0-poh0h0.litmus.expected
- herd/tests/diycross/AArch64.mixed.strict/MP+dmb.syw0w0+amo.casa.h2h2-poh2h0.litmus.expected
- herd/tests/instructions/AArch64.kvm/A019.litmus
- herd/tests/instructions/AArch64.kvm/A019.litmus.expected
- herd/tests/instructions/AArch64.mixed/M008.litmus.expected
- herd/tests/instructions/AArch64/A242.litmus.expected
- herd/tests/instructions/AArch64/A243.litmus.expected
- herd/tests/instructions/AArch64/A244.litmus.expected
- herd/tests/instructions/AArch64/A245.litmus.expected
- herd/tests/instructions/AArch64/A246.litmus.expected
- herd/tests/instructions/AArch64/L007.litmus.expected
- herd/tests/instructions/AArch64/L056.litmus.expected
- herd/tests/instructions/AArch64/L057.litmus.expected
The objective of this PR is to amend the instruction semantics for CAS in case when its comparison fails. Broadly speaking, whenever a CAS fails its comparison, it is now allowed to read the original value in memory and then write the same value back. This has consequences: an Explicit Write Effect may be created, a Hardware Update might be created, (with FEAT_MTE_STOREONLY not supported by `herd7` presently) a TagCheck may be created.
The following kinds of executions are expected of a failed CAS:
- CAS generates an Explicit Write Effect of a value that is already in memory and, if `-variant vmsa` is enabled, that leads to generating a Hardware Update to the dirty bit.
- CAS does not generate an Explicit Write Effect and, if `-variant vmsa` is enabled, a candidate execution with a …
> [herd7,aarch64] A failed CAS may write back

- litmus/libdir/_aarch64/kvm_fault_handler.c
When EL0 mode is specified, SVC is executed normally to transit back from EL0 to EL1, do not override default behaviour.
Without the fix EL0 tests will not terminate. This applies for instance for this simple test:
```
AArch64 TST-EL0
Variant=precise
EL0=P0
{
int x=1;
pte_x=(el0:0);
0:X2=x;
1:X2=x;
}
P0        |  P1         ;
LDR W0,[X2] | LDR W0,[X2] ;
forall Fault(P0,x) /\ 0:X0=0 /\ ~Fault(P1,x) /\ 1:X0=1
```
Problem introduced by PR #1079. As a result of this fix, one can no longer run tests that execute `svc` as a test instruction in EL0 mode. Is this fixable ? @HadrienRenaud, @diaolo01.
> [litmus,aarch64] Fix SVC execution from EL0

- catalogue/aarch64/tests/@all
- catalogue/aarch64/tests/SB+dmb.sy+rel-acq.litmus
- catalogue/aarch64/tests/SB+dmb.sy+rel-acqpc.litmus
- catalogue/aarch64/tests/kinds.txt
This PR adds two tests to illustrate the clause in Barrier-ordered-before that is sensitive to the differences between the `LDAR` and `LDAPR` instructions.
> [catalogue,aarch64] 2 tests for release-to-acquire ordering

- herd/AArch64Sem.ml
Arm ARM's rule state
RDRGYL A single-copy atomic explicit memory access is Tag Unchecked
due to any of the following, otherwise it is Tag Checked:
• The access is:
...
— Due to a cache maintenance operation by VA other than DC ZVA
...
However, currently DC is Tag check. Let's align DC with the rule and make it Tag Unchecked
> [herd, aarch64]: Do not Tag Check cache maintenance operation(s)

- catalogue/aarch64/tests/@all
- catalogue/aarch64/tests/MP+rel+acq.litmus
- catalogue/aarch64/tests/MP+rel+acqpc.litmus
- catalogue/aarch64/tests/MP+rel+swp-acq.litmus
- catalogue/aarch64/tests/MP+rel+swp-acqpc.litmus
- catalogue/aarch64/tests/kinds.txt
Several tests forbidden with the baseline `aarch64.cat` memory model. They illustrate the cases of identical ordering for `LDAR` and `LDAPR`.
> [catalogue,aarch64] Four forbidden tests with acq/acqpc

- herd/tests/instructions/X86_64/A009.litmus
- herd/tests/instructions/X86_64/A009.litmus.expected
- herd/tests/instructions/X86_64/A010.litmus
- herd/tests/instructions/X86_64/A010.litmus.expected
- litmus/X86_64Compile_litmus.ml
The registers of this machine have several incarnations (64bits, 32bits,...). Litmus needs a precise knowledge of those to treat initial constants correctly.
Consider for instance this test:
```
X86_64 A010
{
uint64_t x;
0:RBX=0x202020202020202;
}
P0            ;
MOVQ %RBX,(x) ;
locations [x;]
forall [x] = 0x202020202020202
```
Before this PR, **litmus** fails on this test  as the constant `0x202020202020202` is casted into the default type `int`. With code typing  a correct, 64 bits, type is inferred.
Typing remains minimal and is probably insufficient.
> [litmus] Add some typing of registers in x86_64 code

- asllib/Parser.mly
- asllib/doc/.gitignore
- asllib/doc/PrimitiveOperations.tex
- asllib/tests/regressions.t/run.t
- asllib/tests/regressions.t/same-precedence2.asl
Bug report by @acjf3. Previously, `<->` was parsed to `EQ_OP` (like `==`), so some programs were accepted when they should have been rejected due to bad precedence, e.g.:
```
a --> b <-> c
```
Also add `__pycache__` to `asllib/doc/.gitignore`.
> [asl] Ensure `<->` is parsed to `BEQ`

- herd/AArch64Sem.ml
- herd/branch.ml
- herd/mem.ml
- herd/tests/instructions/AArch64.kvm/A020.litmus
- herd/tests/instructions/AArch64.kvm/A020.litmus.expected
- herd/tests/instructions/AArch64.kvm/A021.litmus
- herd/tests/instructions/AArch64.kvm/A021.litmus.expected
- herd/tests/instructions/AArch64.kvm/A022.litmus
- herd/tests/instructions/AArch64.kvm/A022.litmus.expected
- herd/tests/instructions/AArch64.kvm/F004.litmus
- herd/tests/instructions/AArch64.kvm/F004.litmus.expected
- litmus/libdir/_aarch64/kvm_fault_handler.c
In AArch64, the SVC instruction generates a specific fault for both **herd** and **litmus**.
When tools imitate "natural" behaviour (_i.e._ `-variant handled` or `-variant imprecise`), control returns to the instruction that follows the SVC instruction. Previous behaviour was to re-execute SVC, following the standard behaviour for synchronous faults.
As an example the following test passes on hardware, while it yielded no **herd** output previously, due the repetitive execution of `SVC`.
```
AArch64 A020
variant=vmsa,handled
{
0:X0=0;
}
P0          ;
L0:           ;
SVC #0       ;
ADD W0,W0,#1 ;
forall fault(P0:L0) /\ 0:X0=1
```
By contrast the test was already correct for **litmus**.
On a related note, we also changed the **litmus**  behaviour of  `-variant skip` to transfer control to …
> [herd.litmus] Fix svc return

- litmus/libdir/kvm-aarch64-qemu.cfg
The new file configures litmus for vmsa tests running on top of  qemu-system-aarch64 on a non-aarch64 system.
Notice that this is the final step after having
+ Installed the cross-compilation toolchain
+ Installed qemu-system-aarch64
+ Compiled kvm-unit-tests. on top of qemu
> [litmus] Add configuration file

- asllib/Parser.mly
- asllib/SideEffect.ml
- asllib/SideEffect.mli
- asllib/Typing.ml
- asllib/doc/ASLmacros.tex
- asllib/doc/GlobalDeclarations.tex
- asllib/doc/GlobalStorageDeclarations.tex
- asllib/doc/SideEffects.tex
- asllib/doc/Syntax.tex
- asllib/error.ml
- asllib/tests/print.t
- asllib/tests/side-effects.t/config-type-uses-let.asl
- asllib/tests/side-effects.t/config-uses-atc.asl
- asllib/tests/side-effects.t/config-uses-config-through-func.asl
- asllib/tests/side-effects.t/config-uses-config.asl
- asllib/tests/side-effects.t/config-uses-constant-through-func.asl
- asllib/tests/side-effects.t/config-uses-constant.asl
- asllib/tests/side-effects.t/config-uses-let-through-func.asl
- asllib/tests/side-effects.t/config-uses-let.asl
- asllib/tests/side-effects.t/config-uses-local-constant.asl
- asllib/tests/side-effects.t/config-uses-local-let.asl
- asllib/tests/side-effects.t/config-uses-local-var.asl
- asllib/tests/side-effects.t/config-uses-unknown.asl
- asllib/tests/side-effects.t/config-uses-var-through-func.asl
- asllib/tests/side-effects.t/config-uses-var.asl
- asllib/tests/side-effects.t/run.t
Make the following changes concerning global `config` declarations:
- All `config` declarations must:
- have an explicit type annotation
- be of a singular type
- refer to only constant-time expressions
- Remove configuration-time from side-effect analysis, and treat `config` declarations as execution-time
- Document the level of language support for `config`
> [asl] Updates to `config`s

- lib/checkName.ml
Diagnostics are now printed from verbosity level 2 (`-v -v`).
> [all] Less verbose name checking

- herd/eventsMonad.ml
- lib/symbValue.ml
Some general operations were still using explicit one and zero for true and false. Fix this.
This is a followup to PR #1129.
> [herd] Fix some remaining  integers-as-booleans

- Makefile
- catalogue/aarch64-pick/cfgs/asl.cfg
- catalogue/aarch64/cfgs/asl.cfg
- internal/herd_catalogue_regression_test.ml
Two new entries are added in the Makefile:
+ `make cata-aarch64-test-asl` for testing
the AArch64 catalogue in ASL mode
+ `make pick-test-asl` for pick test in ASL mode
With make `cata-test-asl` one runs both entries. The new entries are also run by `make test-all`.
Interestingly, the new tests reveal discrepancies with expected kinds:
```
% make cata-aarch64-test-asl 
...
Kinds differs: kinds file = catalogue/aarch64/tests/kinds.txt ; cat = "cats/aarch64.cat"
LB+rel+CAS-ok-RsRs-addr: expected=Allowed, actual=Forbidden
LB+rel+CAS: expected=Forbidden, actual=Allowed
MP+rel+CASacq-noret-ok: expected=Allowed, actual=Forbidden
MP+rel+CASnoret-ok-dmb.ld: expected=Allowed, actual=Forbidden
MP+rel+LDADDnoret-dmb.ld: expected=Allowed, actual=Forbidden
MP+rel+SWPnoret-dmb.ld: expected=Allowed, …
```
> [test] Regression test from  the catalogue in ASL mode

- catalogue/aarch64/cfgs/asl.cfg
- herd/AArch64ASLSem.ml
This fixes the test `MP+rel+CASacq-noret-ok` identified in #1178.
> [asl+aarch64] Fix noret decode for CAS

- herd/tests/instructions/AArch64.kvm/NORUN
- litmus/AArch64Arch_litmus.ml
- litmus/AArch64Compile_litmus.ml
- litmus/ASMLang.ml
- litmus/arch_litmus.mli
- litmus/compile.ml
- litmus/handler.ml
- litmus/handler.mli
- litmus/hardwareExtra.ml
- litmus/hardwareExtra.mli
- litmus/libdir/_aarch64/kvm_fault_handler.c
- litmus/libdir/_aarch64/kvm_user_stacks.c
- litmus/preSi.ml
- litmus/template.ml
We now systematically change the vector table of EL0 threads, by introducing an indirect jump in the slot for EL0 synchronous interruptions.
During test the indirection point to the appropriate fault handler. Just before leaving test code, the indirection is changed to point to the end of test code. This technique permits returning to EL1 at test end by using a `SVC` instruction.
Moreover, `SVC` instructions that may be present in test code are treated by the appropriate fault handler.
This PR is a followup to PR #1157.
> [litmus,aarch64] EL0 mode by vector table.

- asllib/doc/ASLmacros.tex
- asllib/doc/Bitfields.tex
- asllib/doc/RelationsOnTypes.tex
- asllib/doc/Types.tex
- asllib/doc/doclint.py
* Fixed a bug in `doclint.py` which effectively disabled the check for matching hyperlinks and hypertargets.
* FIxed 8 hyperlinks/hypertargets issues.
> [asl][reference] fixed a bug in doclint.py and added missing hypertargets

- asllib/Interpreter.ml
- asllib/doc/ASLmacros.tex
- asllib/doc/BlockStatements.tex
- asllib/tests/regressions.t/run.t
- asllib/tests/regressions.t/throw-local-env.asl
Thanks to @solswords for a bug report.
- Delete block-local variables after evaluating a block, even when an exception is thrown.
- Add a test using `--no-typecheck`. This previously passed, exposing that block-local variables were persisting across their block boundaries. Now it correctly fails with an "undefined identifier" error.
> [asl] Fixes for environments in evaluation of blocks

- asllib/Native.ml
- asllib/libdir/stdlib.asl
- asllib/tests/stdlib.t/align.asl
- asllib/tests/stdlib.t/ilog2.asl
- asllib/tests/stdlib.t/log2.asl
- asllib/tests/stdlib.t/no-primitives-test.asl
- asllib/tests/stdlib.t/rotate.asl
- asllib/tests/stdlib.t/run.t
- asllib/tests/stdlib.t/sint.asl
- asllib/tests/stdlib.t/uint.asl
- herd/ASLSem.ml
- Add `ROL` and `ROL_C`
- Add `FloorLog2`, `CeilLog2`; remove `Log2`
- Update signatures of `UInt` and `SInt`: parameter `N` now has constraints `integer{1..128}`. This also requires introducing the same constraint to `Align{Up,Down}Size`
> ASL-786, ASL-787, ASL-788: update standard library

- catalogue/aarch64/shelf.py
- catalogue/aarch64/tests/@all
- catalogue/aarch64/tests/MP+rel+addr-lrs-acq.litmus
- catalogue/aarch64/tests/MP+rel+addr-po-loc-addr.litmus
- catalogue/aarch64/tests/MP+rel+ctrl-lrs-acq.litmus
- catalogue/aarch64/tests/MP+rel+data-lrs-acq.litmus
- catalogue/aarch64/tests/MP+rel+rmw-lrs-acq.litmus
- catalogue/aarch64/tests/kinds.txt
This PR adds 5 new tests to the aarch64 catalogue:
- MP+rel+addr-po-loc-addr is allowed and shows why po & same-loc is not in ob.
- MP+rel+addr-lrs-acq, MP+rel+data-lrs-acq and MP+rel+rmw-lrs-acq are forbidden due to the dependency ordered before relation.
- MP+rel+ctrl-lrs-acq is allowed in contrast to MP+rel+addr-lrs-acq and MP+rel+data-lrs-acq.
> Add tests to the aarch64 catalogue for existing relations of the memory model

- asllib/Typing.ml
- asllib/doc/ASLmacros.tex
- asllib/doc/GlobalStorageDeclarations.tex
- asllib/doc/PatternMatching.tex
- asllib/doc/Semantics.tex
- asllib/doc/Statements.tex
- asllib/doc/SubprogramCalls.tex
- asllib/doc/TypeAttributes.tex
- asllib/doc/TypeDeclarations.tex
- asllib/doc/dictionary.txt
- asllib/doc/doclint.py
- asllib/tests/ASLSemanticsReference.t/SemanticsRule.DeclareGlobal.asl
- asllib/tests/ASLSemanticsReference.t/SemanticsRule.EvalGlobals.asl
- asllib/tests/ASLSemanticsReference.t/SemanticsRule.SCall.asl
- asllib/tests/ASLSemanticsReference.t/run.t
- asllib/tests/ASLTypingReference.t/TypingRule.DeclareGlobalStorage.asl
- asllib/tests/ASLTypingReference.t/TypingRule.DeclareGlobalStorage.bad1.asl
- asllib/tests/ASLTypingReference.t/TypingRule.DeclareGlobalStorage.bad2.asl
- asllib/tests/ASLTypingReference.t/TypingRule.DeclareGlobalStorage.bad3.asl
- asllib/tests/ASLTypingReference.t/TypingRule.DeclareGlobalStorage.config.asl
- asllib/tests/ASLTypingReference.t/TypingRule.DeclareGlobalStorage.non_config.asl
- asllib/tests/ASLTypingReference.t/TypingRule.UpdateGlobalStorage.config.asl
- asllib/tests/ASLTypingReference.t/TypingRule.UpdateGlobalStorage.config.bad.asl
- asllib/tests/ASLTypingReference.t/TypingRule.UpdateGlobalStorage.constant.asl
- asllib/tests/ASLTypingReference.t/run.t
* Added examples
* Addressed PDF review comments.
* Removed `try_add_global_constant` and inlined it.
> ASL-716 accessibility enhancements phase 10: examples and fixes

- catalogue/aarch64-faults/README.md
- catalogue/aarch64-faults/tests/SVC.litmus
When introducing the SVC instruction, as part of the following commit: https://github.com/herd/herdtools7/commit/62b1036808b0e0ce4d6ad306ba55b1b635d1fa6c, it became apparent that there is a significant difference between checking the address or label of the instruction that caused the fault and the return address of the fault. This distinction emerged since SVC handler returns to the instruction after the SVC, unlike most instructions which return to the instruction that caused the fault.
> [doc] Capturing convention about 'fault' predicate

- asllib/Typing.ml
- asllib/doc/SubprogramCalls.tex
- asllib/error.ml
The typechecker used to check that a given call expression matches at most one subprogram and emit a typing error if more than one candidate subprogram matches the call expression. However, if two candidate subprograms exist, it would mean their signatures clash, which would be detected upon their declaration.
This PR removes the check and adds an explanation to the ASL Reference why this check is not needed.
> [asl] remove check for multiple candidates for a call expression

- asllib/Interpreter.ml
- asllib/doc/ASLmacros.tex
- asllib/doc/Specifications.tex
- asllib/doc/dictionary.txt
- asllib/doc/doclint.py
- asllib/libdir/stdlib.asl
- asllib/tests/ASLTypingReference.t/TypingRule.AddSubprogramDecls.asl
- asllib/tests/ASLTypingReference.t/TypingRule.CheckGlobalPragma.asl
- asllib/tests/ASLTypingReference.t/TypingRule.CheckGlobalPragma.bad.asl
- asllib/tests/ASLTypingReference.t/TypingRule.DeclDependencies.asl
- asllib/tests/ASLTypingReference.t/TypingRule.DeclareSubprograms.asl
- asllib/tests/ASLTypingReference.t/TypingRule.DefDecl.asl
- asllib/tests/ASLTypingReference.t/TypingRule.DefEnumLabels.asl
- asllib/tests/ASLTypingReference.t/TypingRule.TypeCheckAST.asl
- asllib/tests/ASLTypingReference.t/TypingRule.TypeCheckMutuallyRec.bad.asl
- asllib/tests/ASLTypingReference.t/TypingRule.UseBitfield.asl
- asllib/tests/ASLTypingReference.t/TypingRule.UseConstraint.asl
- asllib/tests/ASLTypingReference.t/TypingRule.UseDecl.asl
- asllib/tests/ASLTypingReference.t/TypingRule.UseExpr.asl
- asllib/tests/ASLTypingReference.t/TypingRule.UseLexpr.asl
- asllib/tests/ASLTypingReference.t/TypingRule.UsePattern.asl
- asllib/tests/ASLTypingReference.t/TypingRule.UseSlice.asl
- asllib/tests/ASLTypingReference.t/TypingRule.UseStmt.asl
- asllib/tests/ASLTypingReference.t/TypingRule.UseTy.asl
- asllib/tests/ASLTypingReference.t/run.t
* Addex examples to the Specifications chapter.
* Fixed a couple of typos in `interpreter.ml` and `stdlib.asl`
> ASL-716 accessibility enhancements phase 11: examples and fixes

- asllib/doc/ASLmacros.tex
- asllib/doc/AssignableExpressions.tex
- asllib/doc/ErrorCodes.tex
- asllib/doc/Statements.tex
- asllib/doc/SubprogramCalls.tex
- asllib/doc/Types.tex
- asllib/doc/dictionary.txt
- asllib/doc/doclint.py
* The rule was not defined correctly in terms of the semantics of short-circuitting, as defined by the reference.
* PR #1236 removed a case but it was still referenced in the description of the corresponding error code. That description is now removed.
* Added a linter for finding LaTeX macros that are defined but never used.
* Removed LaTeX macros that are defined and never used.
* Removed `\hypertarget` instances without a corresponding `\hyperlink`
> [asl][reference] fixed TypingRule.InsertStdlibParam

- asllib/Typing.ml
- asllib/doc/ASLmacros.tex
- asllib/doc/Bitfields.tex
Simplified `interval_of_slice` and `to_singles` in `Typing.ml` by removing the cases for `Slice_Single`, `Slice_Range`, and `Slice_Star`. This is okay, since these functions are applied on annotated slices, which have all been converted to `Slice_Length`.
> [asl] simplified case matching for handling annotated slices

- asllib/DependencyAnalysis.ml
- asllib/doc/Specifications.tex
The recursion limit expression should be considered as a "used expression" for a subprogram declaration.
An example will be added to https://github.com/herd/herdtools7/pull/1249
* Updated implementation
* Updated ASL Reference
> [asl] add the recurselimit expression as a used expression

- asllib/doc/ASLmacros.tex
- asllib/doc/Bitfields.tex
- asllib/doc/Expressions.tex
- asllib/doc/GlobalStorageDeclarations.tex
- asllib/doc/Specifications.tex
- asllib/doc/Statements.tex
- asllib/doc/SubprogramCalls.tex
- asllib/doc/TypeSystemUtilities.tex
- asllib/doc/Types.tex
- asllib/doc/dictionary.txt
- asllib/doc/doclint.py
- asllib/tests/ASLSemanticsReference.t/SemanticsRule.AssignArgs.asl
- asllib/tests/ASLSemanticsReference.t/SemanticsRule.Call.asl
- asllib/tests/ASLSemanticsReference.t/SemanticsRule.CheckRecurseLimit.asl
- asllib/tests/ASLSemanticsReference.t/SemanticsRule.CheckRecurseLimit.limit_reached.asl
- asllib/tests/ASLSemanticsReference.t/SemanticsRule.CheckRecurseLimit.no_limit.asl
- asllib/tests/ASLSemanticsReference.t/run.t
- asllib/tests/ASLTypingReference.t/TypingRule.AnnotateCallActualsTyped.bad1.asl
- asllib/tests/ASLTypingReference.t/TypingRule.AnnotateCallActualsTyped.bad2.asl
- asllib/tests/ASLTypingReference.t/TypingRule.AnnotateCallActualsTyped.bad3.asl
- asllib/tests/ASLTypingReference.t/TypingRule.AnnotateRetTy.asl
- asllib/tests/ASLTypingReference.t/TypingRule.AnnotateRetTy.bad.asl
- asllib/tests/ASLTypingReference.t/TypingRule.SubstExpr.asl
- asllib/tests/ASLTypingReference.t/run.t
* Added examples to the Subprogram Calls chapter.
* Extended spellchecking to be applied to captions of code examples and fixed some spelling errors.
> ASL-716 accessibility enhancements phase 15: examples and fixes

- gen/AArch64Arch_gen.ml
- gen/AArch64Compile_gen.ml
- gen/ARMCompile_gen.ml
- gen/BellCompile.ml
- gen/CArch_gen.ml
- gen/CCompile_gen.ml
- gen/MIPSCompile_gen.ml
- gen/PPCCompile_gen.ml
- gen/RISCVCompile_gen.ml
- gen/X86Compile_gen.ml
- gen/X86_64Compile_gen.ml
- gen/code.ml
- gen/code.mli
- gen/cycle.ml
- gen/edge.ml
- gen/final.ml
- gen/machMixed.ml
- gen/machMixed.mli
- gen/rmw.mli
- gen/run_gen.ml
- gen/topUtils.ml
- gen/top_gen.ml
Change the type of `Code.v` from plain `int` to a customer type `NoValue | Plain of int`.  We did not use the standard `option` type as we will introduce fold more value type in the future.
In cycle building process, there are too many different value related field in the `node` data structure. The use of those fields are based on the `node` type and mode/variant of the `diy7`, e.g. `kvm` and `mte`. Those cause confusion and unnecessary complications when maintaining the code.
It is now a relatively trivial change, where `NoValue` collapses to previously default value `-1` via a new function `Code.value_to_int`. However, this leads to a future change that folds other value-related types, such as pte value, instruction value (for iFetch) and memory tag value (for MTE), which means simpler …
> [diy] Code improvement: upgrade the `Code.v` type

- asllib/README.mld
- asllib/doc/dictionary.txt
- asllib/doc/disclaimer.tex
As requested by some people, adding links on ASLRef to where the transliterated specs are published.
> Link ASLRef to Arm's ASL specs webpage

- asllib/Typing.ml
- asllib/doc/ASLmacros.tex
- asllib/doc/AssignableExpressions.tex
- asllib/doc/Bitfields.tex
- asllib/doc/dictionary.txt
- asllib/tests/ASLTypingReference.t/TypingRule.CheckSymbolicallyEvaluable.asl
- asllib/tests/ASLTypingReference.t/TypingRule.CheckSymbolicallyEvaluable.bad.asl
- asllib/tests/ASLTypingReference.t/TypingRule.EvalSliceExpr.asl
- asllib/tests/ASLTypingReference.t/run.t
There are conceptual categories of slices:
1. Static slices, which appear in bitfield definitions, and
2. Symbolic slices, which appear in slicing expressions.
Currently `disjoint_slices_to_positions` does not distinguish between the two and attempts to normalize expressions into integers. This works for symbolic slices, but not for static slices as int he following example where the expression `symbolic{4}(4)` should be statically evaluated:
```
func symbolic{N}(x: integer{N}) => integer{N}
begin
return x;
end;
type Data of bits(128) {
[symbolic{4}(4)] data
};
```
This PR adds a Boolean flag to `disjoint_slices_to_positions` to distinguish between the two categories of slices and apply normalization to symbolic slices and static evaluation to static slices.
* Added a new rule …
> [asl] changed how typechecker evaluates slices

- asllib/ASTUtils.ml
- asllib/doc/AbstractSyntax.tex
- asllib/doc/Literals.tex
- asllib/doc/Semantics.tex
- asllib/doc/SymbolicEquivalenceTesting.tex
`slice_equal` in `ASTUtils.ml` accepts annotated slices, which should only have the form `Slice_Length`.
* Put the other cases under `assert false`
* Updated the reference accordingly, explaining this.
> [asl] simplify slice_equal to only handle Slice_Length

- herd/variant.ml
This PR removes the implication `-variant AArch64+ASL+UDF` to `-variant ASL` on the architecture `AArch64`. This is because we want to be able to try the `UDF` specific tests without the `ASL` variant.
This comes from cdbacf6e600005d771a57c1fef435d1da478b629 and was spotted by @maranget.
Note: the variant `AArch64+ASL+UDF` does not have any effect if the variant `ASL` is not specified.
> [herd][AArch64+ASL] Do not force UDF variant to use ASL

- asllib/Parser.mly
- asllib/doc/ASLmacros.tex
- asllib/doc/GlobalDeclarations.tex
- asllib/doc/SubprogramDeclarations.tex
- asllib/doc/Syntax.tex
Made change to grammar of accessor declarations to match that of subprogram declarations:
* Changed 
`decl -> override "accessor" ID params_opt func_args "<=>" ty"begin" accessors "end" ";"`
into 
`decl -> override "accessor" ID params_opt func_args "<=>" ty" accessors_body`
and added
`accessors_body -> "begin" accessors "end" ";"`
* Updated ASL Reference.
> [asl] refactored accessors grammar

- herd/AArch64Arch_herd.ml
- herd/AArch64Sem.ml
- herd/branch.ml
- herd/tests/instructions/AArch64.sve/V31.litmus
- herd/tests/instructions/AArch64.sve/V31.litmus.expected
- herd/tests/instructions/AArch64/L104.litmus
- herd/tests/instructions/AArch64/L104.litmus.expected
- lib/AArch64Base.ml
This PR fixes a bug found by @murzinv while reviewing PR #1258.
Namely, herd crashes on the following test:
```
AArch64 NZCV-03
Variant=sve
{
uint64_t 0:X3;
0:X0=0; 0:X1=1;
}
P0               ;
CMP W0,W1          ;
WHILELT P0.S,W0,W1 ;
MRS X3,NZCV        ;
forall 0:X3=0xa0000000
```
The root cause of the crash is a discrepancy between the interpretation time  and solver time values of the `NZCV` flags. More precisely, the `MRS X3,NZCV ` uses the interpretation time value; while the `WHILELT` instruction does not signal that it destroys the previous values of the flags.
Instructions that write into the NZCV "register" must signal it as follows:
1. Include the `NZCV` into the kill list of the instruction, (function `killed` in AArch64Arch_herd.ml`)
2. Include the new binding as a result of …
> [herd] Complete tracking of the NZCV "register"

- asllib/doc/LexicalStructure.tex
Fixed the Lexical Structure chapter by replaceing 'symbols' to denote verbatim strings with "symbols".
> [asl][reference] impose proper formatting for Lexical Structure

- asllib/doc/ASLmacros.tex
Included `\usepackage[T1]{fontenc}` to make names with underscores searchable in the generated PDF.
For example, now, searching for "eval_expr" finds its instances whereas before one had to look for "eval expr".
> [asl][reference] make names with underscore PDF-searchable

- asllib/doc/ASLmacros.tex
- asllib/doc/LexicalStructure.tex
- asllib/doc/PatternMatching.tex
- asllib/doc/RelationsOnTypes.tex
- asllib/doc/Statements.tex
- asllib/doc/SubprogramCalls.tex
- asllib/doc/SymbolicEquivalenceTesting.tex
- asllib/doc/dictionary.txt
- asllib/doc/doclint.py
- asllib/tests/ASLSemanticsReference.t/SemanticsRule.PMask.asl
- asllib/tests/ASLTypingReference.t/TypingRule.BitwidthEqual.asl
- asllib/tests/ASLTypingReference.t/TypingRule.PMask.bad.asl
- asllib/tests/ASLTypingReference.t/TypingRule.SliceEqual.asl
- asllib/tests/ASLTypingReference.t/TypingRule.SlicesEqual.asl
- asllib/tests/ASLTypingReference.t/TypingRule.TypeClashes.bad.asl
- asllib/tests/ASLTypingReference.t/run.t
* Added examples to the Symbolic Equivalence Testing chapter.
* Fixed `SemanticsRule.PMask` to account for empty bitmasks.
* Fixed definition of identifiers and real literals - use `\underbracket` instead of the undefined quote notation.
* Fixed definition of whitespace.
* Applied `\anycharacter` more widely in `LexicalStructure.tex`.
> ASL-716 accessibility enhancements phase 17: examples and fixes

- asllib/doc/Semantics.tex
Added a paragraph to the Semantics Definitions chapter clarifying that the semantics does not make any statement about running time.
> [asl][reference] clarification on semantics & time

- asllib/Parser.mly
- asllib/ParserConfig.mli
- asllib/aslref.ml
- asllib/builder.ml
- asllib/builder.mli
- asllib/bundler.ml
- asllib/doc/ASLmacros.tex
- asllib/doc/Expressions.tex
- asllib/doc/PatternMatching.tex
- asllib/doc/Syntax.tex
- asllib/tests/regressions.t/no-expression-elsif.asl
- asllib/tests/regressions.t/run.t
- lib/ASLBase.ml
Remove support for the `elsif` keyword at the expression level. Guard this change behind a `--allow-expression-elsif` flag for backwards compatibility.
> [asl] Forbid expression-level `elsif`

- asllib/AST.mli
- asllib/Native.ml
- asllib/Operations.ml
- asllib/PP.ml
- asllib/Parser.mly
- asllib/Parser0.mly
- asllib/Serialize.ml
- asllib/Typing.ml
- asllib/carpenter/ASTEnums.ml
- asllib/carpenter/RandomAST.ml
- asllib/doc/ASLmacros.tex
- asllib/doc/AbstractSyntax.tex
- asllib/doc/PrimitiveOperations.tex
- asllib/doc/RelationsOnTypes.tex
- asllib/menhir2bnfc/tests/integration/cmp_binops.ml
- asllib/tests/ASLTypingReference.t/TypingRule.ApplyBinopTypes.asl
- asllib/tests/ASLTypingReference.t/TypingRule.BinopLiterals.strings_labels.asl
- asllib/tests/ASLTypingReference.t/run.t
- asllib/tests/regressions.t/run.t
- asllib/tests/regressions.t/string_concat.asl
- herd/ASLSem.ml
Support string concatenation by overloading the existing `::` binary operator (previously only bit vector concatenation).
> [asl] Binary operator for string concatenation

- asllib/ASTUtils.ml
- asllib/doc/ASLmacros.tex
- asllib/doc/SymbolicEquivalenceTesting.tex
- asllib/tests/ASLDefinition.t/Overriding.asl
Extended the slice equvalence test `slice_equal` to operate on untyped AST - that is all forms of slices. This is needed to equate subprogram signatures of `impdef`/`implementation` subprograms, which happend before the signatures are annotated.
> [asl][reference] extend slice_equal to untyped AST

- asllib/Typing.ml
- asllib/doc/ASLmacros.tex
- asllib/doc/Specifications.tex
- asllib/doc/dictionary.txt
- asllib/tests/ASLTypingReference.t/TypingRule.RenameSubprograms.asl
- asllib/tests/ASLTypingReference.t/run.t
- asllib/tests/overriding.t/run.t
- asllib/tests/overriding.t/type-check-impdef.asl
Rather than discarding overridden `impdef` subprograms, ensure they are type-checked. In particular, give them fresh names so that they are never referred to, but still appear in the final type-checked specification.
> [asl] Typecheck discarded `impdef` subprograms

- asllib/Native.ml
- asllib/Typing.ml
- asllib/doc/ASLmacros.tex
- asllib/doc/SubprogramDeclarations.tex
- asllib/libdir/stdlib.asl
- asllib/tests/ASLTypingReference.t/TypingRule.ParametersOfExpr.asl
- asllib/tests/ASLTypingReference.t/TypingRule.ParametersOfExpr.bad.asl
- asllib/tests/ASLTypingReference.t/run.t
- asllib/tests/stdlib.t/run.t
- asllib/tests/stdlib.t/sint.asl
- asllib/tests/stdlib.t/uint.asl
- herd/ASLSem.ml
The new signatures are:
```
func UInt{N} (x: bits(N)) => integer{0..2^N-1}
func SInt{N} (x: bits(N))
=> integer{(if N == 0 then 0 else -(2^(N-1))) .. (if N == 0 then 0 else 2^(N-1)-1)}
```
As a result, the constraints on the parameters `N` of `Align{Down,Up}Size` and `IsAlignedSize` are also removed.
> [asl] Update signatures of `UInt` and `SInt`

- asllib/Typing.ml
- asllib/doc/ASLmacros.tex
- asllib/doc/SymbolicSubsumptionTesting.tex
- asllib/tests/regressions.t/approx-expr-binop.asl
- asllib/tests/regressions.t/run.t
- asllib/types.ml
The following specification causes aslref to hand, since it tries to approximate `x + 10` for every value of `0..2^64 - 1`
```
begin
let x: integer{0..2^64 - 1} = ARBITRARY: integer{0..2^64 - 1};
constant offset = 10;
var x_offset: integer{x..x + 10} = x as integer{x..x + offset};
return 0;
end;
```
* The fix involves applying constraint approximation instead of the explicit Cartesian product.
* Updated the reference.
* Added the specification above to the regression tests.
> ASL fix expression approximation overflow bug

- asllib/doc/ASLmacros.tex
- asllib/doc/RelationsOnTypes.tex
- asllib/doc/SymbolicEquivalenceTesting.tex
- asllib/doc/SymbolicSubsumptionTesting.tex
- asllib/doc/TypeDomains.tex
- asllib/doc/dictionary.txt
- asllib/instrumentation.ml
- asllib/tests/ASLTypingReference.t/TypingRule.ApproxConstraint.asl
- asllib/tests/ASLTypingReference.t/run.t
- asllib/tests/types.ml
- asllib/types.ml
- asllib/types.mli
The new subsumption test converts each constraint in a list of constraints into a symbolic domain of its own, unlike previously where all resided in a single symbolic domain.
> [asl] new subsumption test

- asllib/ASTUtils.ml
- asllib/ASTUtils.mli
- asllib/Interpreter.ml
- asllib/Native.ml
- asllib/Typing.ml
- asllib/backend.mli
- asllib/tests/types.ml
- asllib/types.ml
- asllib/types.mli
- herd/ASLSem.ml
* Replaced some dummy source locations with source code locations.
* Added `add_pos_range_from` to enable source code locations that start with one construct and end at another.
* There are still some dummy source locations in the parsers.
> [ASL] added more source locations

- asllib/doc/ASLmacros.tex
- asllib/doc/AbstractSyntax.tex
- asllib/doc/BaseValues.tex
- asllib/doc/SideEffects.tex
- asllib/doc/SymbolicEquivalenceTesting.tex
- asllib/doc/dictionary.txt
- asllib/doc/doclint.py
- asllib/doc/introduction.tex
- asllib/tests/ASLTypingReference.t/TypingRule.ArrayLengthEqual.bad.asl
- asllib/tests/ASLTypingReference.t/TypingRule.BitFieldEqual.asl
- asllib/tests/ASLTypingReference.t/TypingRule.BitFieldEqual.bad1.asl
- asllib/tests/ASLTypingReference.t/TypingRule.BitFieldEqual.bad2.asl
- asllib/tests/ASLTypingReference.t/TypingRule.BitFieldsEqual.asl
- asllib/tests/ASLTypingReference.t/TypingRule.BitFieldsEqual.bad.asl
- asllib/tests/ASLTypingReference.t/TypingRule.ConstraintEqual.asl
- asllib/tests/ASLTypingReference.t/TypingRule.ConstraintsEqual.asl
- asllib/tests/ASLTypingReference.t/TypingRule.ExprEqual.asl
- asllib/tests/ASLTypingReference.t/TypingRule.Normalize.asl
- asllib/tests/ASLTypingReference.t/TypingRule.ReduceConstraint.asl
- asllib/tests/ASLTypingReference.t/TypingRule.SideEffectIsPure.asl
- asllib/tests/ASLTypingReference.t/TypingRule.ToIR.asl
- asllib/tests/ASLTypingReference.t/TypingRule.TypeEqual.asl
- asllib/tests/ASLTypingReference.t/TypingRule.UnitaryMonomialsToExpr.asl
- asllib/tests/ASLTypingReference.t/run.t
* Fixed example "Pure and Symbolically Evaluable Side Effect Descriptors" + an explanation why `factorial` is a pure function.
* Fixed a bug in `Typing.ToIR`.
* Added examples to the Symbolic Equivalence Testing chapter.
> ASL-716 accessibility enhancements phase 18: examples and fixes

- Makefile
- herd/AArch64ASLSem.ml
- herd/AArch64Arch_herd.ml
- herd/AArch64Sem.ml
- herd/libdir/asl-pseudocode/patches.asl
- herd/tests/instructions/AArch64.sve/V32.litmus
- herd/tests/instructions/AArch64.sve/V32.litmus.expected
- herd/tests/instructions/AArch64.sve/V33.litmus
- herd/tests/instructions/AArch64.sve/V33.litmus.expected
- herd/tests/instructions/AArch64.sve/V34.litmus
- herd/tests/instructions/AArch64.sve/V34.litmus.expected
- herd/tests/instructions/AArch64.sve/asl.cfg
- jingle/AArch64Arch_jingle.ml
- lib/AArch64Base.ml
- lib/AArch64Lexer.mll
- lib/AArch64Parser.mly
- lib/ASLScalar.ml
- litmus/AArch64Compile_litmus.ml
These SVE instructions are special as they alter some of the NZCV "flags" but not all of them.
> [all] Add CTERM{EQ,NE} instructions

- catalogue/aarch64-MTE/tests/RtWtRt+WztWzt.litmus
- catalogue/aarch64-MTE/tests/to-tagcheck-sync/2+2W+dmb.sttp+dsb.st--sync.litmus
- catalogue/aarch64-MTE/tests/to-tagcheck-sync/MP+dmb.sttp+dsb.sy--sync.litmus
Couple MTE tests in catalogue contained minor typos in their post condition checks, let's correct them.
> Fix typos in post conditions of few MTE tests

- asllib/Parser.mly
- asllib/desugar.ml
- asllib/desugar.mli
- asllib/doc/ASLRefALP3.1ChangeLog.tex
- asllib/doc/ASLmacros.tex
- asllib/doc/AssignableExpressions.tex
- asllib/doc/Statements.tex
- asllib/doc/Syntax.tex
- asllib/doc/dictionary.txt
- asllib/menhir2bnfc/tests/integration/parser_cmp.expected
- asllib/tests/ASLSyntaxReference.t/ASTRule.DesugarLHSAccess.asl
- asllib/tests/ASLSyntaxReference.t/ASTRule.DesugarLHSFieldsTuple.asl
- asllib/tests/ASLSyntaxReference.t/ASTRule.DesugarLHSTuple.asl
- asllib/tests/ASLSyntaxReference.t/run.t
- asllib/tests/regressions.t/lhs-expressivity.asl
- asllib/tests/regressions.t/lhs-tuple-same-var.asl
- asllib/tests/regressions.t/run.t
Relax restrictions on left-hand sides:
- for accesses on variables `x`:
- permit any nesting of field/array accesses - `x.fld`, `x[[idx]]`, `x.fld[[idx]]`, `x[[idx]].fld`, ...
- optionally followed by slices - `x.fld[slices]`, `x[[idx]][slices]`, `x.fld[[idx]][slices]`, `x[[idx]].fld[slices]`, ...
- for access on setters `Setter(args)`:
- permit nesting of field accesses - `Setter(args).fld`, `Setter(args).fld1.fld2`, ...
- optionally followed by slices - `Setter(args).fld[slices]`, `Setter(args).fld1.fld2[slices]`, ...
- for multi-assignments: allow multiple assignments to the same variable, relying on evaluation order: `(x.fld1, x.fld2) = rhs;`
This required updates to the grammar and intermediate forms for desugaring. Also slightly tidied `desugar.{ml,mli}` along the way.
> [asl] Permit more forms on left-hand sides

- asllib/ASTUtils.ml
- asllib/Typing.ml
- asllib/acl2/aslreftests/dune-project
- asllib/doc/ASLFormal.tex
- asllib/doc/ASLmacros.tex
- asllib/doc/GlobalDeclarations.tex
- asllib/doc/GlobalStorageDeclarations.tex
- asllib/doc/Specifications.tex
- asllib/doc/SubprogramCalls.tex
- asllib/doc/SubprogramDeclarations.tex
- asllib/doc/SymbolicEquivalenceTesting.tex
- asllib/doc/dictionary.txt
- asllib/tests/ASLTypingReference.t/TypingRule.PropagateRecursiveCallsSess.asl
- asllib/tests/ASLTypingReference.t/run.t
- herd/tests/instructions/ASL/concat.litmus.expected
* Rewrote the inference rule and prose for `TypingRule.PropagateRecursiveCallsSess` to closer match the impementation and fix some bugs.
* Use a new example for `TypingRule.PropagateRecursiveCallsSess`.
* Fixed bugs in `TypingRule.TypecheckDecl`
* Fixes to section `Configurable Global Storage Declarations`
* Fixed a bug in `SemanticsRule.Call`.
* Fixed a bug in `TypingRule.DeclareOneFunc`
* Fixed a reference to an example in `TypingRule.BitFieldsEqual`
* A fix to the transitive closure utility function in `ASTUtils.ml`
> [ASL][Reference] Fixed recursive side effects rule and some other rules

- asllib/bitvector.mli
- asllib/doc/ASLmacros.tex
- asllib/doc/AssignableExpressions.tex
- asllib/doc/CatchingExceptions.tex
- asllib/doc/GlobalDeclarations.tex
- asllib/doc/GlobalStorageDeclarations.tex
- asllib/doc/LocalStorageDeclarations.tex
- asllib/doc/PatternMatching.tex
- asllib/doc/Specifications.tex
- asllib/doc/Statements.tex
- asllib/doc/SubprogramCalls.tex
- asllib/doc/SubprogramDeclarations.tex
- asllib/doc/SymbolicSubsumptionTesting.tex
- asllib/doc/TopLevel.tex
- asllib/doc/TypeSystemUtilities.tex
- asllib/tests/ASLTypingReference.t/TypingRule.Normalize.asl
- asllib/tests/ASLTypingReference.t/TypingRule.ToIR.asl
* Fixed [asl][reference] fixed `\eqname` vs. `=` errors.
* Other fixed, following PDF review.
> [ASL][Reference] Fixes following PDF review - phase 2

- .github/workflows/menhir2bnfc.yml
- asllib/menhir2bnfc/tests/integration/parser_cmp.expected
New tests from https://github.com/herd/herdtools7/pull/1327 need to be added to the expected discrepancies.
This was missed as the `menhir2bnfc` CI did not trigger - so ensure that this runs whenever any `.asl` files change.
> [asl] Fix `menhir2bnfc` tests

- herd/Pretty.ml
- herd/prettyConf.ml
This mode is also selected by the synonyms `memfence` and `memfault`.
> [herd] Include faults in events displayed by mode `-showevents memf`

- .github/workflows/build-asl-reference.yml
- asllib/doc/Makefile
- asllib/doc/doclint.py
- asllib/doc/extended_macros.py
Always use the `-m` flag to make sure that the console outputs are synchronized with the ASL Reference.
This requires building and installing aslref so that it can be run from `doclint.py`.
Also a `--aslref` option was added to `doclint.py` to point to the aslref binary path.
> [asl][reference] Always make with -m option

- asllib/doc/AssignableExpressions.tex
- asllib/doc/Expressions.tex
- asllib/doc/LexicalStructure.tex
- asllib/doc/SemanticsUtilities.tex
- asllib/doc/Types.tex
The rules missed the cases where the index could be out of bounds, resulting in a dynamic error.
> [asl][reference] fixed SemanticsRule.GetIndex and SemanticsRule.SetIndex

- herd/AArch64Arch_herd.ml
- herd/ARMArch_herd.ml
- herd/BPFArch_herd.ml
- herd/BellArch_herd.ml
- herd/CArch_herd.ml
- herd/GenericArch_herd.ml
- herd/JavaArch_herd.ml
- herd/MIPSArch_herd.ml
- herd/PPCArch_herd.ml
- herd/RISCVArch_herd.ml
- herd/X86Arch_herd.ml
- herd/X86_64Arch_herd.ml
- herd/archExtra_herd.ml
- lib/Archs.ml
- lib/Archs.mli
Fail with an explicit error message when mixed size mode is specified for an architecture that does not implement it..
Currently, mixed size mode is implemented for AArch64 and X86_64.
This PR fixes a problem reported by Andrea Parri.
> [herd] Fail when `-variant mixed` is not implemented

- asllib/Typing.ml
- asllib/doc/ASLFormal.tex
- asllib/doc/ASLmacros.tex
- asllib/doc/SymbolicEquivalenceTesting.tex
* Defined missing function `polynomial_divide_by_term`
* Catch code that should be rejected by the parser with a safety-net exception.
> [ASL] Tying loose ends

- asllib/tests/regressions.t/noreturn.asl
- asllib/tests/regressions.t/run.t
Changed the value returned from `main` to be `0` as `1` indicates an error of which there is none here.
> [asl] successful main should always return 0

- asllib/ASTUtils.ml
- asllib/doc/ASLFormal.tex
- asllib/doc/ASLmacros.tex
- asllib/doc/Expressions.tex
- asllib/doc/TopLevel.tex
- asllib/doc/dictionary.txt
- asllib/doc/doclint.py
* Renamed `map_desc_st'` to `map_annotated` since it is generic and used for constructs other than statements.
* Added renaming for patterns and pattern statements, catchers and try statements, array indices and array types, parameterized integer types, and collection types.
> [ASL] Completed functionality for renaming locals in standard library subprograms

- litmus/answer.mli
- litmus/dumpRun.ml
- litmus/dumpRun.mli
- litmus/top_litmus.ml
The variant `self` impacts (1) the C code of a test and  (2) gcc compilation flags. Compilation flags are now changed as soon as one test is compiled in self mode.
This departs from previous behaviour where compilation  flags were changed only when the variant was specified on the command line.
Change is minor and only applies when
1. `-variant self` is *not* specified on the command line.
2. Some of the compiled tests meta-data specifies `Variant=self`.
In that situation the previous behaviour was *not* changing the compilation flags, while the new behaviour is changing them.
As a technical note, the functor  `DumpRun.Make` configuration argument does not longer include a `variant` member.
> [litmus] Change handling of the self variant

- asllib/Interpreter.ml
- asllib/doc/Statements.tex
- asllib/tests/loop-limits.t/run.t
- asllib/tests/loop-limits.t/while-for-repeat-comparison.asl
For-loops hit their limit one iteration too early - the following example produced a loop limit error.
```
for i = 1 to 1 looplimit 1 do
println i;
end;
```
This PR moves the check + decrement of loop limits - rather than executing unconditionally, it executes only if another loop iteration is to follow.
Thanks to Skye Aubrey for the bug report!
> [ASL-857] Fix a loop limit bug

- asllib/Native.ml
- asllib/Typing.ml
- asllib/doc/SubprogramDeclarations.tex
- asllib/error.ml
- asllib/libdir/stdlib.asl
- asllib/tests/ASLDefinition.t/run.t
- asllib/tests/ASLSemanticsReference.t/run.t
- asllib/tests/ASLSyntaxReference.t/run.t
- asllib/tests/ASLTypingReference.t/run.t
- asllib/tests/bad-types.t
- asllib/tests/collections.t/run.t
- asllib/tests/lexer.t
- asllib/tests/regressions.t/asciistr.asl
- asllib/tests/regressions.t/run.t
- asllib/tests/stdlib.t/run.t
- asllib/tests/typing.t/run.t
- Error messages
- Increase precision in some messages (e.g. "typing" vs. "grammar" errors)
- Change error message for non-symbolic base values
- Correct a previous error message where I had used `pp_print_text` instead of `fprintf`
- Primitive error messages for `HexStr` and `AsciiStr` were being reported as `DecStr`
- Fix a rule that overflowed into page margins
- Fix `AsciiStr` to make the right check on its input (`0 <= input <= 127`)
> [asl] Some superficial fixes

- asllib/dune
- diymicro/cycle.ml
- dune
- lib/AArch64Op.ml
- litmus/ASMLang.ml
- litmus/dumpRun.ml
- litmus/global_litmus.ml
- litmus/outUtils.ml
- litmus/preSi.ml
Warning 9 "missing-record-field-pattern" flags missing fields in a record pattern.
I view it as usefull to find missing fields in complete record patterns when some field is added to a record.
Notice that uncomplete record patterns are still possible by ending patterns with the wildcard `_`.
As there are numerous such uncomplete patterns in `asllib`, warning 9 remains disabled there.
> [build] Enable warning 9, except in asllib

- asllib/Typing.ml
- asllib/tests/regressions.t/asl1-calls-asl0-accessor.asl
Desugaring of read-modify-write produces an `ST_Getter` call, which was missed in #1402.
> [asl] Fix an omission in #1402

- lib/constant.ml
- lib/constant.mli
- lib/stateParser.mly
- litmus/ASMLang.ml
- litmus/compile.ml
- litmus/dumpRun.ml
- litmus/global_litmus.ml
- litmus/global_litmus.mli
- litmus/litmus.ml
- litmus/outUtils.ml
- litmus/skel.ml
- litmus/test_litmus.ml
- tools/dumperMiscParser.ml
This PR is inspired  PR #1371.  PR #1371 fixes array index problems with **herd7**, this PR will fix similar problems with **litmus7**.
The typical test is now compiled correctly in all litmus modes:
```
AArch64 T
{
int x[2];
0:X0=x[1]; (* Expect offset to 2nd element of x *)
}
P0;
MOV W1,#1  ;
STR W1,[X0];
forall x[1]=1
```
> [litmus] Fix array index anomalies in litmus

- lib/AArch64PteVal.ml
- lib/AArch64PteVal.mli
- lib/pteVal.ml
- lib/pteVal.mli
- litmus/preSi.ml
According to some comment in code introduced by PR #1117, some cache flush after test run is performed when there is a risk of writing to some location with non-default attributes.
This risk is identified the predicate `memattrs_change` that checks the following two properties:
1. The location PTE value is set to a non-default initial value. Notice that this check does not take attributes into account.
2. This initial value has some attributes.
Running a test on a Raspberry P5B, we experienced some deadlock, or extreme slowdown due to the extra cache flush. Notice that the test ignores memory attributes:
```
AArch64 MP+UpdateAF
TTHM=P0:HD
{
0:X1=x; 1:X1=x;
0:X3=y; 1:X3=y;
1:X2=1;
pte_x=(af:0);
1:X6=pte_x;
1:X4=(oa:phy_x,af:0)
}
P0          | P1              ;
LDR W0,[X1] | STR W2,[X3] …
```
> [litmus,vmsa] Less radical attribute change check

- internal/herd_catalogue_regression_test.ml
- internal/lib/index.ml
- internal/lib/index.mli
1. Specify tests with the new option -index-path. Using this option overrides the default behaviour of reading test names from the shelf file.
2. Better formatted error message when some errors occurred while running herd7.
> [tests] Two enhancements for catalogue regression test

- .github/workflows/static-binaries.yml
- asllib/dune
- dune
In particular, attempt to reintroduce the functionality reverted by #1421. Tested locally with minimum versions from the `.opam` file (except OCaml 4.10, as I can't install any lower locally).
> [ci] Attempt to fix static binaries build

- asllib/Parser0.mly
According to the V1 Parser binary `IN` binds tighter than unary `!`.
> [asl] Fix precedence for ASL V0

- herd/libdir/aarch64loc.cat
- herd/libdir/catdefinitions.tex
- tools/miaou.ml
* Fixes the way miaou7 handles indices and whenever possible reuses the same indices as per the behaviour prior to PR #1312.
* Minor fix in the definition of va-loc to improve its transliteration in English.
* Rename the Explicitly-Observed-by and Explicitly-Hazard-ordered-before to Explicit-Observed-by and Explicit-hazard-ordered-before
> Align the tranliteration of aarch64.cat with the Arm ARM issue L.b

- asllib/aslspec/AST.ml
- asllib/aslspec/PP.ml
- asllib/aslspec/SpecParser.mly
- asllib/aslspec/render.ml
- asllib/aslspec/spec.ml
- asllib/aslspec/tests.t/relations.spec
- asllib/aslspec/tests.t/run.t
- Added proper support for macro attributes in terms of pretty-printing.
- Added identation to attributes in pretty-printing.
- Allowed (optional) naming sub-terms for `option`, `list0`, `list1`, `powerset`, `fun`, and `partial`.
- Droped the check `check_only_top_level_types`, since it looks like we do want to use constants and types defined as variants in relations signatures.
- Removed extra spaces around `\BeginDefineConstant` and `\BeginDefineType`, since they create redundant extra spaces in the PDF.
> [aslspec] Minor improvements and fixes to aslspec

- asllib/AST.mli
- asllib/Interpreter.ml
- asllib/Interpreter.mli
- asllib/Native.ml
- asllib/Operations.ml
- asllib/StaticInterpreter.ml
- herd/ASLSem.ml
Thanks to Laurent for spotting this bug!
- Add `BIC` to the native interpreter
- Gate usage of `BIC` behind interpreter configuration
- Add comments clarifying it is internal, and not part of ASL1.0
Follows on from #916
> [asl] Tweaks around new internal `BIC` operator

- herd/AArch64Sem.ml
- herd/branch.ml
- herd/tests/instructions/AArch64.kvm/F005.litmus
- herd/tests/instructions/AArch64.kvm/F005.litmus.expected
- herd/tests/instructions/AArch64.kvm/F006.litmus
- herd/tests/instructions/AArch64.kvm/F006.litmus.expected
- herd/tests/instructions/AArch64.kvm/asl-vmsa.cfg
More specifically,  the instruction `ERET` was not accepting code addresses in the numeric form as introduced by PR #482.  This is now fixed. 
As a consequence a  label is no longer required after the instruction `SVC` or any faulting instruction for explicit handlers to return with `ERET`.
> [herd] No more mandatory label  after SVC for ERET to operate
